// Merge script: combines existing definitions with all new ones
import { readFileSync, writeFileSync } from "fs";

const existing = JSON.parse(readFileSync("./data/word-definitions.json", "utf-8"));
const answers = JSON.parse(readFileSync("./data/words-answer.json", "utf-8"));

// All new definitions for missing words
const newDefs = {
"accidental": [{"partOfSpeech": "adjective", "definition": "Occurring by chance or without intention rather than by design."}],
"accordance": [{"partOfSpeech": "noun", "definition": "The state of being in agreement or harmony with a rule, standard, or expectation."}],
"accountant": [{"partOfSpeech": "noun", "definition": "A professional whose occupation involves maintaining, auditing, and preparing financial records."}],
"accounting": [{"partOfSpeech": "noun", "definition": "The systematic process of recording, summarizing, and reporting financial transactions."}],
"accredited": [{"partOfSpeech": "adjective", "definition": "Officially recognized as meeting established standards of quality or competence."}],
"accusation": [{"partOfSpeech": "noun", "definition": "A formal claim or charge that someone has committed a wrongdoing or crime."}],
"accustomed": [{"partOfSpeech": "adjective", "definition": "Familiar with something through repeated experience or long exposure."}],
"activating": [{"partOfSpeech": "verb", "definition": "Causing something to begin functioning or to set a process in motion."}],
"activation": [{"partOfSpeech": "noun", "definition": "The process of making something operative or triggering it to begin functioning."}],
"activities": [{"partOfSpeech": "noun", "definition": "Pursuits, tasks, or events in which people engage, often for a particular purpose."}],
"adaptation": [{"partOfSpeech": "noun", "definition": "The process of changing to suit new conditions or a different environment."}],
"addictions": [{"partOfSpeech": "noun", "definition": "Conditions of compulsive dependence on harmful substances or behaviors."}],
"additional": [{"partOfSpeech": "adjective", "definition": "Extra or supplementary beyond what is already present or expected."}],
"addressing": [{"partOfSpeech": "verb", "definition": "Dealing with or giving attention to a matter, issue, or concern."}],
"adequately": [{"partOfSpeech": "adverb", "definition": "In a manner that is sufficient or satisfactory for a particular purpose."}],
"adjectives": [{"partOfSpeech": "noun", "definition": "Words in grammar that describe or modify nouns, indicating qualities such as size or color."}],
"adjustable": [{"partOfSpeech": "adjective", "definition": "Capable of being modified or repositioned to fit different requirements."}],
"adjustment": [{"partOfSpeech": "noun", "definition": "A small change or modification made to improve correctness, fit, or function."}],
"admiration": [{"partOfSpeech": "noun", "definition": "A feeling of warm respect, approval, and pleased wonder toward someone or something."}],
"admissible": [{"partOfSpeech": "adjective", "definition": "Accepted as valid or allowable, especially as evidence in a court of law."}],
"admissions": [{"partOfSpeech": "noun", "definition": "Acts of allowing entry, or statements acknowledging the truth of something."}],
"admittedly": [{"partOfSpeech": "adverb", "definition": "Used to acknowledge that something is true, often reluctantly or as a concession."}],
"adsorption": [{"partOfSpeech": "noun", "definition": "The process by which molecules from a gas or liquid adhere to the surface of a solid."}],
"advantages": [{"partOfSpeech": "noun", "definition": "Favorable conditions or benefits that give a superior position over others."}],
"adventurer": [{"partOfSpeech": "noun", "definition": "A person who seeks out exciting, daring, or risky experiences and expeditions."}],
"adventures": [{"partOfSpeech": "noun", "definition": "Exciting or unusual experiences involving risk, exploration, or bold undertakings."}],
"advertised": [{"partOfSpeech": "verb", "definition": "Promoted or publicized a product, service, or event through media."}],
"advertiser": [{"partOfSpeech": "noun", "definition": "A person or company that promotes products or services through public media channels."}],
"advisories": [{"partOfSpeech": "noun", "definition": "Official warnings or notices about potential dangers or important developments."}],
"advocating": [{"partOfSpeech": "verb", "definition": "Publicly supporting or recommending a particular cause or policy."}],
"aesthetics": [{"partOfSpeech": "noun", "definition": "The branch of philosophy concerned with beauty and taste, or the visual appeal of something."}],
"affiliated": [{"partOfSpeech": "adjective", "definition": "Officially connected to or associated with a larger organization or group."}],
"affiliates": [{"partOfSpeech": "noun", "definition": "Organizations or individuals formally connected to a larger body."}],
"affordable": [{"partOfSpeech": "adjective", "definition": "Reasonably priced and within the financial means of most people."}],
"afternoons": [{"partOfSpeech": "noun", "definition": "The periods of the day between noon and evening."}],
"afterwards": [{"partOfSpeech": "adverb", "definition": "At a later time; subsequently following a particular event."}],
"aggravated": [{"partOfSpeech": "adjective", "definition": "Made worse or more serious; involving circumstances that increase severity."}],
"aggregated": [{"partOfSpeech": "adjective", "definition": "Collected and combined from multiple sources into a unified total."}],
"aggregates": [{"partOfSpeech": "noun", "definition": "Totals or collections formed by combining individual elements into a whole."}],
"aggression": [{"partOfSpeech": "noun", "definition": "Hostile or violent behavior directed toward others with intent to harm."}],
"aggressive": [{"partOfSpeech": "adjective", "definition": "Displaying hostile, forceful, or assertively competitive behavior."}],
"agreements": [{"partOfSpeech": "noun", "definition": "Mutual arrangements between parties establishing shared terms and obligations."}],
"alcoholics": [{"partOfSpeech": "noun", "definition": "Persons suffering from chronic dependency on ethanol-containing beverages."}],
"algorithms": [{"partOfSpeech": "noun", "definition": "Step-by-step procedures or rules for solving problems or performing computations."}],
"alienation": [{"partOfSpeech": "noun", "definition": "A state of isolation, estrangement, or detachment from others or society."}],
"alignments": [{"partOfSpeech": "noun", "definition": "Arrangements in which things are set in correct relative order or orientation."}],
"allegation": [{"partOfSpeech": "noun", "definition": "A claim that someone has done something wrong, typically made without proof."}],
"allegiance": [{"partOfSpeech": "noun", "definition": "Loyalty or devotion pledged to a nation, sovereign, cause, or leader."}],
"allocating": [{"partOfSpeech": "verb", "definition": "Distributing or setting aside resources for a specific purpose."}],
"allocation": [{"partOfSpeech": "noun", "definition": "The distribution of resources, funds, or duties for particular purposes."}],
"allowances": [{"partOfSpeech": "noun", "definition": "Permitted amounts or sums of money given regularly for a specific purpose."}],
"alphabetic": [{"partOfSpeech": "adjective", "definition": "Arranged in the standard order of letters from A to Z."}],
"alteration": [{"partOfSpeech": "noun", "definition": "A change or modification made to something to improve or adjust it."}],
"alternator": [{"partOfSpeech": "noun", "definition": "A device that converts mechanical energy into electrical current."}],
"amendments": [{"partOfSpeech": "noun", "definition": "Formal changes or revisions made to a law, document, or constitution."}],
"ammunition": [{"partOfSpeech": "noun", "definition": "Projectiles, shells, and cartridges fired from weapons."}],
"amphibians": [{"partOfSpeech": "noun", "definition": "Cold-blooded vertebrates like frogs and salamanders that live both in water and on land."}],
"amplifiers": [{"partOfSpeech": "noun", "definition": "Devices that increase the strength of a signal, especially sound."}],
"amplitudes": [{"partOfSpeech": "noun", "definition": "Maximum extents of vibration measured from equilibrium positions in waves."}],
"amusements": [{"partOfSpeech": "noun", "definition": "Things that provide entertainment, pleasure, or lighthearted enjoyment."}],
"anatomical": [{"partOfSpeech": "adjective", "definition": "Relating to the bodily structure of humans, animals, or other organisms."}],
"animations": [{"partOfSpeech": "noun", "definition": "Sequences of images displayed rapidly to create the illusion of movement."}],
"annexation": [{"partOfSpeech": "noun", "definition": "The act of incorporating territory into an existing political unit."}],
"annotation": [{"partOfSpeech": "noun", "definition": "A note or comment added to a text to provide explanation."}],
"announcing": [{"partOfSpeech": "verb", "definition": "Making a public or formal declaration to inform others of something."}],
"antibodies": [{"partOfSpeech": "noun", "definition": "Proteins produced by the immune system that neutralize foreign substances."}],
"apartments": [{"partOfSpeech": "noun", "definition": "Self-contained residential units within a larger building, typically rented."}],
"apparently": [{"partOfSpeech": "adverb", "definition": "As far as one can tell; based on what seems to be the case."}],
"appearance": [{"partOfSpeech": "noun", "definition": "The way someone or something looks outwardly to observers."}],
"appellants": [{"partOfSpeech": "noun", "definition": "Persons who bring a case to a higher court seeking reversal of a decision."}],
"appendices": [{"partOfSpeech": "noun", "definition": "Supplementary sections at the end of a book containing extra information."}],
"appetizers": [{"partOfSpeech": "noun", "definition": "Small dishes served before the main course to stimulate hunger."}],
"appliances": [{"partOfSpeech": "noun", "definition": "Devices designed for specific household tasks such as cooking or cleaning."}],
"applicable": [{"partOfSpeech": "adjective", "definition": "Relevant or appropriate to a particular situation or set of circumstances."}],
"applicants": [{"partOfSpeech": "noun", "definition": "People who formally request something, especially a job or grant."}],
"applicator": [{"partOfSpeech": "noun", "definition": "A tool used for spreading or putting a substance onto a surface."}],
"appointing": [{"partOfSpeech": "verb", "definition": "Officially selecting or designating someone for a position or role."}],
"appraisals": [{"partOfSpeech": "noun", "definition": "Formal evaluations of the value, quality, or performance of something."}],
"appraisers": [{"partOfSpeech": "noun", "definition": "Professionals who assess the monetary worth of property or goods."}],
"approached": [{"partOfSpeech": "verb", "definition": "Came nearer in distance or time, or initiated contact with someone."}],
"approaches": [{"partOfSpeech": "noun", "definition": "Methods or ways of dealing with a situation or problem."}],
"arbitrator": [{"partOfSpeech": "noun", "definition": "An impartial person chosen to settle a dispute between parties."}],
"architects": [{"partOfSpeech": "noun", "definition": "Professionals who design buildings and oversee their construction."}],
"artificial": [{"partOfSpeech": "adjective", "definition": "Made by human beings rather than occurring through natural processes."}],
"aspiration": [{"partOfSpeech": "noun", "definition": "A strong hope, ambition, or goal that one desires to achieve."}],
"assemblies": [{"partOfSpeech": "noun", "definition": "Gatherings for a common purpose, or collections of parts fitted together."}],
"assembling": [{"partOfSpeech": "verb", "definition": "Gathering together or fitting component parts to construct a whole."}],
"assertions": [{"partOfSpeech": "noun", "definition": "Confident, forceful statements of fact or belief presented as true."}],
"assessment": [{"partOfSpeech": "noun", "definition": "The process of evaluating the nature, quality, or value of something."}],
"assignment": [{"partOfSpeech": "noun", "definition": "A task or piece of work given to someone as part of their job or studies."}],
"assistance": [{"partOfSpeech": "noun", "definition": "Help, support, or aid provided to someone in need."}],
"assistants": [{"partOfSpeech": "noun", "definition": "People who help others in their work, typically in a subordinate role."}],
"associated": [{"partOfSpeech": "adjective", "definition": "Connected or linked with something else in thought or occurrence."}],
"associates": [{"partOfSpeech": "noun", "definition": "Colleagues or people connected with others in work or business."}],
"assortment": [{"partOfSpeech": "noun", "definition": "A varied collection or mixture of different types of things."}],
"assumption": [{"partOfSpeech": "noun", "definition": "Something taken for granted or accepted as true without proof."}],
"assurances": [{"partOfSpeech": "noun", "definition": "Positive declarations intended to inspire confidence and remove doubt."}],
"astonished": [{"partOfSpeech": "adjective", "definition": "Greatly surprised or amazed by something unexpected."}],
"astounding": [{"partOfSpeech": "adjective", "definition": "Shockingly impressive or surprisingly remarkable."}],
"astronauts": [{"partOfSpeech": "noun", "definition": "People trained to travel and work in outer space."}],
"atrocities": [{"partOfSpeech": "noun", "definition": "Extremely cruel or horrifying acts, especially against civilians."}],
"attachment": [{"partOfSpeech": "noun", "definition": "An emotional bond, or a file joined to a message or document."}],
"attainment": [{"partOfSpeech": "noun", "definition": "The act of reaching or achieving a goal through effort."}],
"attempting": [{"partOfSpeech": "verb", "definition": "Making an effort to accomplish something difficult."}],
"attendance": [{"partOfSpeech": "noun", "definition": "The act of being present at a place or event."}],
"attendants": [{"partOfSpeech": "noun", "definition": "People employed to assist or look after others in a particular setting."}],
"attracting": [{"partOfSpeech": "verb", "definition": "Drawing interest, attention, or physical pull toward something."}],
"attraction": [{"partOfSpeech": "noun", "definition": "The power of evoking interest or the desire to draw closer."}],
"attractive": [{"partOfSpeech": "adjective", "definition": "Pleasing to look at or appealing in a way that draws interest."}],
"attributed": [{"partOfSpeech": "verb", "definition": "Regarded something as being caused by or credited to a source."}],
"attributes": [{"partOfSpeech": "noun", "definition": "Qualities or features regarded as belonging to a person or thing."}],
"authorised": [{"partOfSpeech": "adjective", "definition": "Given official permission or approval (British spelling)."}],
"authorized": [{"partOfSpeech": "adjective", "definition": "Given official permission or approval to carry out an action."}],
"authorizes": [{"partOfSpeech": "verb", "definition": "Grants official permission or power to someone."}],
"autographs": [{"partOfSpeech": "noun", "definition": "Handwritten signatures of famous people, often collected as keepsakes."}],
"automation": [{"partOfSpeech": "noun", "definition": "The use of machines to perform tasks with minimal human involvement."}],
"autonomous": [{"partOfSpeech": "adjective", "definition": "Self-governing or capable of operating independently."}],
"awakenings": [{"partOfSpeech": "noun", "definition": "Instances of becoming aware or conscious of something for the first time."}],
"backpacker": [{"partOfSpeech": "noun", "definition": "A person who travels on a budget with belongings in a large pack."}],
"backstreet": [{"partOfSpeech": "noun", "definition": "A minor road in a town, away from the main commercial areas."}],
"bargaining": [{"partOfSpeech": "noun", "definition": "The process of negotiating the terms of a deal or agreement."}],
"basketball": [{"partOfSpeech": "noun", "definition": "A team sport where players score by throwing a ball through an elevated hoop."}],
"battleship": [{"partOfSpeech": "noun", "definition": "A large, heavily armored warship equipped with powerful guns."}],
"beachfront": [{"partOfSpeech": "noun", "definition": "The area of land directly adjacent to a sandy shore."}],
"beforehand": [{"partOfSpeech": "adverb", "definition": "In advance; at an earlier time prior to a particular event."}],
"beginnings": [{"partOfSpeech": "noun", "definition": "The initial stages or earliest parts of something coming into existence."}],
"behavioral": [{"partOfSpeech": "adjective", "definition": "Relating to the way a person or animal acts and conducts themselves."}],
"behaviours": [{"partOfSpeech": "noun", "definition": "The ways in which people or animals conduct themselves (British spelling)."}],
"believable": [{"partOfSpeech": "adjective", "definition": "Capable of being accepted as true, real, or credible."}],
"belongings": [{"partOfSpeech": "noun", "definition": "Personal possessions or items owned by an individual."}],
"benchmarks": [{"partOfSpeech": "noun", "definition": "Standards or reference points against which things may be measured."}],
"beneficial": [{"partOfSpeech": "adjective", "definition": "Producing good results or helpful effects; favorable to well-being."}],
"bestiality": [{"partOfSpeech": "noun", "definition": "Savagely cruel or depraved conduct."}],
"bestseller": [{"partOfSpeech": "noun", "definition": "A book or product that sells in very large numbers."}],
"billboards": [{"partOfSpeech": "noun", "definition": "Large outdoor signs used to display promotional messages."}],
"binoculars": [{"partOfSpeech": "noun", "definition": "An optical instrument with two lenses for viewing distant objects."}],
"biological": [{"partOfSpeech": "adjective", "definition": "Relating to the science of living organisms and life processes."}],
"biologists": [{"partOfSpeech": "noun", "definition": "Scientists who study living organisms, their structure, and evolution."}],
"biomedical": [{"partOfSpeech": "adjective", "definition": "Relating to the application of life sciences to clinical medicine."}],
"biometrics": [{"partOfSpeech": "noun", "definition": "Technologies that measure unique physical traits for identification."}],
"biophysics": [{"partOfSpeech": "noun", "definition": "Science applying principles of physics to understand living systems."}],
"bioscience": [{"partOfSpeech": "noun", "definition": "Any science dealing with living organisms and their vital processes."}],
"bitterness": [{"partOfSpeech": "noun", "definition": "A sharp unpleasant taste, or a deep feeling of resentment and anger."}],
"blackberry": [{"partOfSpeech": "noun", "definition": "A dark purple edible fruit growing on thorny bramble bushes."}],
"blackboard": [{"partOfSpeech": "noun", "definition": "A dark surface used for writing on with chalk in classrooms."}],
"bloodhound": [{"partOfSpeech": "noun", "definition": "A large dog breed with an exceptional sense of smell, used for tracking."}],
"blueprints": [{"partOfSpeech": "noun", "definition": "Detailed technical drawings that serve as guides for construction."}],
"bookseller": [{"partOfSpeech": "noun", "definition": "A person or business that sells printed literary works."}],
"bookstores": [{"partOfSpeech": "noun", "definition": "Retail shops where printed publications are sold."}],
"borderline": [{"partOfSpeech": "adjective", "definition": "On the boundary between two categories; barely meeting a threshold."}],
"bottleneck": [{"partOfSpeech": "noun", "definition": "A point of congestion that slows down progress in a system."}],
"boundaries": [{"partOfSpeech": "noun", "definition": "Lines marking the edges of an area, or limits defining acceptable behavior."}],
"breakfasts": [{"partOfSpeech": "noun", "definition": "Morning meals typically consumed as the first food of the day."}],
"breakpoint": [{"partOfSpeech": "noun", "definition": "A point where execution pauses to allow debugging, or a critical threshold."}],
"breathable": [{"partOfSpeech": "adjective", "definition": "Allowing air to pass through, or safe to inhale."}],
"bridesmaid": [{"partOfSpeech": "noun", "definition": "A woman who accompanies the bride during a wedding ceremony."}],
"briefcases": [{"partOfSpeech": "noun", "definition": "Flat rectangular bags used for carrying documents and business materials."}],
"brightness": [{"partOfSpeech": "noun", "definition": "The quality or intensity of light emitted or reflected."}],
"brilliance": [{"partOfSpeech": "noun", "definition": "Exceptional intelligence or talent, or intense radiance of light."}],
"broadcasts": [{"partOfSpeech": "noun", "definition": "Programs sent out over radio or television for public reception."}],
"broadening": [{"partOfSpeech": "verb", "definition": "Making or becoming wider in scope, range, or extent."}],
"bronchitis": [{"partOfSpeech": "noun", "definition": "Inflammation of the tubes carrying air to and from the lungs."}],
"buccaneers": [{"partOfSpeech": "noun", "definition": "Pirates or seafaring raiders, especially in the Caribbean."}],
"businesses": [{"partOfSpeech": "noun", "definition": "Commercial enterprises engaged in trading goods or services for profit."}],
"calculated": [{"partOfSpeech": "adjective", "definition": "Determined by mathematical reckoning, or done with careful forethought."}],
"calculates": [{"partOfSpeech": "verb", "definition": "Determines a number or amount by using mathematical methods."}],
"calculator": [{"partOfSpeech": "noun", "definition": "An electronic device used for performing mathematical operations."}],
"calibrated": [{"partOfSpeech": "adjective", "definition": "Precisely adjusted or marked with standard measurements for accuracy."}],
"campground": [{"partOfSpeech": "noun", "definition": "An area designated for people to set up tents or park recreational vehicles."}],
"candidates": [{"partOfSpeech": "noun", "definition": "People who put themselves forward for a position, election, or opportunity."}],
"canterbury": [{"partOfSpeech": "noun", "definition": "A historic English cathedral city; also a stand for holding music or papers."}],
"capability": [{"partOfSpeech": "noun", "definition": "The power or ability to do something; the quality of being capable."}],
"capacities": [{"partOfSpeech": "noun", "definition": "The maximum amounts that something can contain or produce."}],
"capacitors": [{"partOfSpeech": "noun", "definition": "Electronic components that store electrical energy in an electric field."}],
"capitalism": [{"partOfSpeech": "noun", "definition": "An economic system based on private ownership of the means of production and free markets."}],
"capitalist": [{"partOfSpeech": "noun", "definition": "A person who owns wealth used in business, or a supporter of private enterprise."}],
"capitalize": [{"partOfSpeech": "verb", "definition": "To take advantage of a situation, or to write in uppercase letters."}],
"cardholder": [{"partOfSpeech": "noun", "definition": "A person who possesses a credit, debit, or membership card."}],
"caricature": [{"partOfSpeech": "noun", "definition": "A drawing that exaggerates features for comic or satirical effect."}],
"carpenters": [{"partOfSpeech": "noun", "definition": "Skilled workers who make and repair wooden structures and objects."}],
"cartridges": [{"partOfSpeech": "noun", "definition": "Containers holding material for insertion into a mechanism, such as ink or film."}],
"cartwright": [{"partOfSpeech": "noun", "definition": "A craftsperson who builds and repairs carts and wagons."}],
"casualties": [{"partOfSpeech": "noun", "definition": "People killed or injured in a war, accident, or disaster."}],
"cataloging": [{"partOfSpeech": "verb", "definition": "Systematically listing and classifying items in an organized record."}],
"catalogues": [{"partOfSpeech": "noun", "definition": "Complete lists of items arranged in a systematic order (British spelling)."}],
"categories": [{"partOfSpeech": "noun", "definition": "Classes or divisions of people or things sharing common characteristics."}],
"categorize": [{"partOfSpeech": "verb", "definition": "To place items into groups according to shared qualities."}],
"cautiously": [{"partOfSpeech": "adverb", "definition": "In a careful way that avoids potential problems or dangers."}],
"celebrated": [{"partOfSpeech": "adjective", "definition": "Widely known and praised; famous for notable achievements."}],
"celebrates": [{"partOfSpeech": "verb", "definition": "Marks a special occasion with enjoyable activities or ceremonies."}],
"cemeteries": [{"partOfSpeech": "noun", "definition": "Burial grounds where the dead are interred."}],
"censorship": [{"partOfSpeech": "noun", "definition": "The suppression or prohibition of speech, writing, or media deemed objectionable."}],
"centennial": [{"partOfSpeech": "noun", "definition": "A hundredth anniversary or its commemoration."}],
"centerline": [{"partOfSpeech": "noun", "definition": "A line that divides something into two equal halves, especially a road."}],
"ceremonial": [{"partOfSpeech": "adjective", "definition": "Relating to or used in formal rites or public occasions."}],
"ceremonies": [{"partOfSpeech": "noun", "definition": "Formal events performed on important social or religious occasions."}],
"certifying": [{"partOfSpeech": "verb", "definition": "Officially attesting or confirming that something meets a required standard."}],
"challenged": [{"partOfSpeech": "verb", "definition": "Questioned the truth of something, or invited someone to a contest."}],
"challenger": [{"partOfSpeech": "noun", "definition": "A person who disputes or competes against a current holder of a position."}],
"challenges": [{"partOfSpeech": "noun", "definition": "Difficult tasks or situations that test someone's abilities."}],
"chandelier": [{"partOfSpeech": "noun", "definition": "A decorative hanging light fixture with multiple branches for bulbs or candles."}],
"characters": [{"partOfSpeech": "noun", "definition": "People in a story, or the qualities that make a person distinctive."}],
"charitable": [{"partOfSpeech": "adjective", "definition": "Generous in giving to those in need; relating to aid for the disadvantaged."}],
"checklists": [{"partOfSpeech": "noun", "definition": "Lists of items or tasks to be verified or completed."}],
"checkpoint": [{"partOfSpeech": "noun", "definition": "A barrier or stopping point where travelers are inspected."}],
"cheesecake": [{"partOfSpeech": "noun", "definition": "A rich dessert made with a soft cheese filling on a biscuit base."}],
"chemically": [{"partOfSpeech": "adverb", "definition": "In a way that relates to the properties and reactions of substances."}],
"childbirth": [{"partOfSpeech": "noun", "definition": "The process of delivering a baby from the womb."}],
"chocolates": [{"partOfSpeech": "noun", "definition": "Confections made from roasted and ground cacao seeds, often sweetened."}],
"christians": [{"partOfSpeech": "noun", "definition": "Followers of the religion based on the teachings of Jesus of Nazareth."}],
"chronicles": [{"partOfSpeech": "noun", "definition": "Written accounts of historical events arranged in order of time."}],
"cigarettes": [{"partOfSpeech": "noun", "definition": "Thin cylinders of finely cut tobacco rolled in paper for smoking."}],
"circulated": [{"partOfSpeech": "verb", "definition": "Moved or spread widely among people or through a system."}],
"clarifying": [{"partOfSpeech": "verb", "definition": "Making a statement or situation less confused and more understandable."}],
"classified": [{"partOfSpeech": "adjective", "definition": "Arranged in categories, or designated as officially secret."}],
"classifier": [{"partOfSpeech": "noun", "definition": "A tool or system that sorts items into defined groups."}],
"classmates": [{"partOfSpeech": "noun", "definition": "Fellow members of the same school or university group."}],
"classrooms": [{"partOfSpeech": "noun", "definition": "Rooms in a school where lessons are taught."}],
"clearwater": [{"partOfSpeech": "noun", "definition": "A body of water that is transparent and free from sediment."}],
"clinically": [{"partOfSpeech": "adverb", "definition": "In a way relating to medical observation and treatment of patients."}],
"clinicians": [{"partOfSpeech": "noun", "definition": "Healthcare professionals who work directly with patients."}],
"clustering": [{"partOfSpeech": "verb", "definition": "Grouping similar items closely together."}],
"coalitions": [{"partOfSpeech": "noun", "definition": "Temporary alliances of distinct parties for joint action."}],
"collateral": [{"partOfSpeech": "noun", "definition": "Property pledged as security for repayment of a loan."}],
"colleagues": [{"partOfSpeech": "noun", "definition": "People with whom one works in a professional setting."}],
"collecting": [{"partOfSpeech": "verb", "definition": "Bringing or gathering things together from various sources."}],
"collection": [{"partOfSpeech": "noun", "definition": "A group of items gathered together, often of a particular type."}],
"collective": [{"partOfSpeech": "adjective", "definition": "Done by or shared among a group of people acting together."}],
"collectors": [{"partOfSpeech": "noun", "definition": "People who gather objects of a particular type as a hobby or profession."}],
"collisions": [{"partOfSpeech": "noun", "definition": "Instances where moving objects strike each other with force."}],
"columnists": [{"partOfSpeech": "noun", "definition": "Journalists who regularly write opinion pieces for a newspaper or magazine."}],
"combatants": [{"partOfSpeech": "noun", "definition": "Persons engaged in fighting during a conflict or war."}],
"combustion": [{"partOfSpeech": "noun", "definition": "The process of burning, involving a chemical reaction with oxygen that produces heat and light."}],
"comforters": [{"partOfSpeech": "noun", "definition": "Thick quilted bed coverings, or people who provide consolation."}],
"comforting": [{"partOfSpeech": "adjective", "definition": "Serving to ease grief or distress; providing reassurance."}],
"commanders": [{"partOfSpeech": "noun", "definition": "Officers in charge of a military unit or operation."}],
"commanding": [{"partOfSpeech": "adjective", "definition": "Having authority and control; impressive enough to inspire respect."}],
"commencing": [{"partOfSpeech": "verb", "definition": "Beginning or starting something."}],
"commentary": [{"partOfSpeech": "noun", "definition": "A spoken or written explanation accompanying an event or text."}],
"commenting": [{"partOfSpeech": "verb", "definition": "Expressing an opinion or remark about something."}],
"commercial": [{"partOfSpeech": "adjective", "definition": "Relating to or engaged in trade, buying and selling of goods."}],
"commission": [{"partOfSpeech": "noun", "definition": "A fee paid for a service, or an official group assigned a task."}],
"commitment": [{"partOfSpeech": "noun", "definition": "A pledge or obligation to carry out a particular course of action."}],
"committees": [{"partOfSpeech": "noun", "definition": "Groups of people appointed to perform a function on behalf of a larger body."}],
"committing": [{"partOfSpeech": "verb", "definition": "Carrying out or perpetrating an act, or pledging to a course of action."}],
"communists": [{"partOfSpeech": "noun", "definition": "Supporters of a political ideology favoring collective ownership of production."}],
"companions": [{"partOfSpeech": "noun", "definition": "People or animals who spend time with and accompany another."}],
"comparable": [{"partOfSpeech": "adjective", "definition": "Similar enough to allow meaningful comparison; of equivalent quality."}],
"comparison": [{"partOfSpeech": "noun", "definition": "The act of evaluating similarities and differences between things."}],
"compassion": [{"partOfSpeech": "noun", "definition": "Deep sympathy and concern for the suffering of others."}],
"compatible": [{"partOfSpeech": "adjective", "definition": "Able to exist or work together without conflict."}],
"compelling": [{"partOfSpeech": "adjective", "definition": "Evoking strong interest or attention; powerfully persuasive."}],
"compensate": [{"partOfSpeech": "verb", "definition": "To make up for a loss or deficiency, or to pay someone for work done."}],
"competence": [{"partOfSpeech": "noun", "definition": "The ability to do something successfully or efficiently."}],
"competency": [{"partOfSpeech": "noun", "definition": "A specific skill or ability needed to perform a task effectively."}],
"competitor": [{"partOfSpeech": "noun", "definition": "A person or organization that rivals another in a contest or market."}],
"complained": [{"partOfSpeech": "verb", "definition": "Expressed dissatisfaction or annoyance about something."}],
"complaints": [{"partOfSpeech": "noun", "definition": "Expressions of dissatisfaction or statements of grievance."}],
"complement": [{"partOfSpeech": "noun", "definition": "Something that completes or enhances something else when combined."}],
"completely": [{"partOfSpeech": "adverb", "definition": "To the greatest extent; totally and in every way."}],
"completing": [{"partOfSpeech": "verb", "definition": "Finishing or bringing something to an end."}],
"completion": [{"partOfSpeech": "noun", "definition": "The action of finishing something or the state of being finished."}],
"complexion": [{"partOfSpeech": "noun", "definition": "The natural color and texture of the skin on a person's face."}],
"compliance": [{"partOfSpeech": "noun", "definition": "The act of conforming to a rule, standard, or request."}],
"compliment": [{"partOfSpeech": "noun", "definition": "A polite expression of praise or admiration."}],
"components": [{"partOfSpeech": "noun", "definition": "Individual parts that make up a larger whole or system."}],
"composites": [{"partOfSpeech": "noun", "definition": "Materials made from two or more distinct substances combined together."}],
"composting": [{"partOfSpeech": "noun", "definition": "The process of decomposing organic waste into nutrient-rich soil material."}],
"compounded": [{"partOfSpeech": "verb", "definition": "Made worse by adding further difficulty, or mixed ingredients together."}],
"compressed": [{"partOfSpeech": "adjective", "definition": "Squeezed or pressed into a smaller space; reduced in size."}],
"compressor": [{"partOfSpeech": "noun", "definition": "A device that increases pressure on a gas to reduce its volume."}],
"comprising": [{"partOfSpeech": "verb", "definition": "Consisting of or being made up of certain parts or elements."}],
"compromise": [{"partOfSpeech": "noun", "definition": "An agreement reached by each side making concessions."}],
"compulsive": [{"partOfSpeech": "adjective", "definition": "Resulting from an irresistible urge, especially against one's will."}],
"compulsory": [{"partOfSpeech": "adjective", "definition": "Required by law or rule; mandatory."}],
"conception": [{"partOfSpeech": "noun", "definition": "The forming of an idea, or the moment when pregnancy begins."}],
"conceptual": [{"partOfSpeech": "adjective", "definition": "Relating to abstract ideas or mental concepts rather than physical things."}],
"concerning": [{"partOfSpeech": "preposition", "definition": "On the subject of; about; causing worry or anxiety."}],
"concession": [{"partOfSpeech": "noun", "definition": "Something yielded or granted in negotiations, or a right given by authority."}],
"concluding": [{"partOfSpeech": "adjective", "definition": "Coming at the end; serving to bring something to a close."}],
"conclusion": [{"partOfSpeech": "noun", "definition": "The end or final part of something, or a judgement reached by reasoning."}],
"conclusive": [{"partOfSpeech": "adjective", "definition": "Serving to settle an issue decisively; leaving no room for doubt."}],
"concurrent": [{"partOfSpeech": "adjective", "definition": "Existing, happening, or done at the same time."}],
"condiments": [{"partOfSpeech": "noun", "definition": "Substances such as salt, mustard, or ketchup used to add flavor to food."}],
"conditions": [{"partOfSpeech": "noun", "definition": "The circumstances affecting the way people live or work."}],
"conducting": [{"partOfSpeech": "verb", "definition": "Organizing and carrying out an activity, or directing an orchestra."}],
"conduction": [{"partOfSpeech": "noun", "definition": "The transmission of heat or electricity through a substance."}],
"conductive": [{"partOfSpeech": "adjective", "definition": "Having the property of allowing heat or electricity to pass through."}],
"conductors": [{"partOfSpeech": "noun", "definition": "Materials that transmit energy, or people who direct an orchestra."}],
"conference": [{"partOfSpeech": "noun", "definition": "A formal meeting for discussion, especially among professionals."}],
"confession": [{"partOfSpeech": "noun", "definition": "A formal statement admitting guilt or wrongdoing."}],
"confidence": [{"partOfSpeech": "noun", "definition": "A feeling of self-assurance, or trust in someone or something."}],
"configured": [{"partOfSpeech": "verb", "definition": "Arranged or set up the parts of something in a particular way."}],
"confirming": [{"partOfSpeech": "verb", "definition": "Establishing the truth or correctness of something previously uncertain."}],
"confluence": [{"partOfSpeech": "noun", "definition": "The junction of two rivers, or a coming together of people or ideas."}],
"conforming": [{"partOfSpeech": "verb", "definition": "Acting in accordance with established rules, standards, or norms."}],
"conformity": [{"partOfSpeech": "noun", "definition": "Behavior in accordance with socially accepted standards or rules."}],
"confronted": [{"partOfSpeech": "verb", "definition": "Faced up to and dealt with a difficult situation or person."}],
"congenital": [{"partOfSpeech": "adjective", "definition": "Present from birth, especially referring to a medical condition."}],
"congestion": [{"partOfSpeech": "noun", "definition": "Overcrowding causing slow movement, as in traffic or nasal passages."}],
"congestive": [{"partOfSpeech": "adjective", "definition": "Relating to an abnormal buildup of fluid in body tissues or organs."}],
"congresses": [{"partOfSpeech": "noun", "definition": "Formal meetings of delegates, or national legislative bodies."}],
"conjecture": [{"partOfSpeech": "noun", "definition": "An opinion or conclusion formed on the basis of incomplete information."}],
"conjugated": [{"partOfSpeech": "verb", "definition": "Gave the different forms of a verb, or joined things together."}],
"connecting": [{"partOfSpeech": "verb", "definition": "Joining or linking two or more things together."}],
"connection": [{"partOfSpeech": "noun", "definition": "A link or relationship between things or people."}],
"connective": [{"partOfSpeech": "adjective", "definition": "Serving to join or link things together."}],
"connectors": [{"partOfSpeech": "noun", "definition": "Devices or components used to join things together."}],
"conscience": [{"partOfSpeech": "noun", "definition": "An inner sense of right and wrong that guides behavior."}],
"consequent": [{"partOfSpeech": "adjective", "definition": "Following as a result or effect of something."}],
"conserving": [{"partOfSpeech": "verb", "definition": "Protecting from harm, decay, or loss; using resources carefully."}],
"considered": [{"partOfSpeech": "adjective", "definition": "Thought about carefully, or regarded in a specified way."}],
"consistent": [{"partOfSpeech": "adjective", "definition": "Unchanging in behavior or quality; not contradictory."}],
"consisting": [{"partOfSpeech": "verb", "definition": "Being composed or made up of specified elements."}],
"conspiracy": [{"partOfSpeech": "noun", "definition": "A secret plan by a group to do something unlawful or harmful."}],
"constantly": [{"partOfSpeech": "adverb", "definition": "Continuously; without stopping or changing."}],
"constitute": [{"partOfSpeech": "verb", "definition": "To be a component part of something; to form or make up."}],
"constraint": [{"partOfSpeech": "noun", "definition": "A limitation or restriction on what is possible or allowed."}],
"constructs": [{"partOfSpeech": "noun", "definition": "Ideas or theories built from various conceptual elements."}],
"consultant": [{"partOfSpeech": "noun", "definition": "An expert who provides professional advice in a particular field."}],
"consulting": [{"partOfSpeech": "noun", "definition": "The business of giving expert advice to professionals."}],
"consumable": [{"partOfSpeech": "adjective", "definition": "Intended to be used up and then replaced."}],
"contacting": [{"partOfSpeech": "verb", "definition": "Getting in touch or communicating with someone."}],
"contagious": [{"partOfSpeech": "adjective", "definition": "Able to be spread from one person to another by close proximity."}],
"containers": [{"partOfSpeech": "noun", "definition": "Objects used for holding or transporting things."}],
"containing": [{"partOfSpeech": "verb", "definition": "Having something inside; holding within its bounds."}],
"contention": [{"partOfSpeech": "noun", "definition": "Heated disagreement; an assertion maintained in argument."}],
"contestant": [{"partOfSpeech": "noun", "definition": "A person who takes part in a competition or game show."}],
"contextual": [{"partOfSpeech": "adjective", "definition": "Depending on or relating to the circumstances that surround something."}],
"contiguous": [{"partOfSpeech": "adjective", "definition": "Sharing a common border; touching or adjacent."}],
"continents": [{"partOfSpeech": "noun", "definition": "The large land masses of the Earth, such as Africa, Asia, or Europe."}],
"contingent": [{"partOfSpeech": "adjective", "definition": "Dependent on certain conditions being met; not certain."}],
"continuing": [{"partOfSpeech": "verb", "definition": "Persisting in an activity without stopping."}],
"continuous": [{"partOfSpeech": "adjective", "definition": "Forming an unbroken whole without interruption."}],
"contracted": [{"partOfSpeech": "verb", "definition": "Entered into a formal agreement, or became smaller in size."}],
"contractor": [{"partOfSpeech": "noun", "definition": "A person or firm hired to carry out building or other work."}],
"contradict": [{"partOfSpeech": "verb", "definition": "To assert the opposite of a statement made by someone."}],
"contribute": [{"partOfSpeech": "verb", "definition": "To give something in order to help achieve a purpose."}],
"controlled": [{"partOfSpeech": "adjective", "definition": "Managed or regulated; kept within certain limits."}],
"controller": [{"partOfSpeech": "noun", "definition": "A person or device that directs or regulates something."}],
"convection": [{"partOfSpeech": "noun", "definition": "Heat transfer through the movement of fluid or air currents."}],
"convenient": [{"partOfSpeech": "adjective", "definition": "Fitting in well with needs or plans; involving little trouble."}],
"convention": [{"partOfSpeech": "noun", "definition": "A large formal meeting, or an accepted standard of behavior."}],
"conversely": [{"partOfSpeech": "adverb", "definition": "In an opposite way; used to introduce a contrasting statement."}],
"conversion": [{"partOfSpeech": "noun", "definition": "The process of changing from one form, use, or state to another."}],
"converters": [{"partOfSpeech": "noun", "definition": "Devices that change something from one form to another."}],
"converting": [{"partOfSpeech": "verb", "definition": "Changing the form, character, or function of something."}],
"conveyance": [{"partOfSpeech": "noun", "definition": "The act of transporting something, or a means of transport."}],
"conviction": [{"partOfSpeech": "noun", "definition": "A firmly held belief, or a formal declaration of guilt in court."}],
"convincing": [{"partOfSpeech": "adjective", "definition": "Able to cause someone to believe something is true or real."}],
"copyrights": [{"partOfSpeech": "noun", "definition": "Legal rights giving creators exclusive control over their original works."}],
"coronation": [{"partOfSpeech": "noun", "definition": "The ceremony of crowning a new king or queen."}],
"correcting": [{"partOfSpeech": "verb", "definition": "Putting right an error or inaccuracy."}],
"correction": [{"partOfSpeech": "noun", "definition": "A change that fixes an error or makes something more accurate."}],
"corrective": [{"partOfSpeech": "adjective", "definition": "Designed to put right something that is wrong or inaccurate."}],
"correlated": [{"partOfSpeech": "adjective", "definition": "Having a mutual relationship or connection between two things."}],
"correlates": [{"partOfSpeech": "verb", "definition": "Has a mutual relationship or shows a connection with something."}],
"correspond": [{"partOfSpeech": "verb", "definition": "To match or be equivalent; to exchange letters or messages."}],
"corrugated": [{"partOfSpeech": "adjective", "definition": "Shaped into alternating ridges and grooves for added strength."}],
"corruption": [{"partOfSpeech": "noun", "definition": "Dishonest conduct by those in power, typically involving bribery."}],
"cosponsors": [{"partOfSpeech": "noun", "definition": "Organizations or people who jointly fund or support an event or bill."}],
"cottonwood": [{"partOfSpeech": "noun", "definition": "A North American poplar tree with seeds that bear cottony tufts."}],
"councilman": [{"partOfSpeech": "noun", "definition": "A male member of an elected local governing body."}],
"counseling": [{"partOfSpeech": "noun", "definition": "Professional guidance on personal or psychological matters."}],
"counselors": [{"partOfSpeech": "noun", "definition": "People trained to give guidance on personal or emotional problems."}],
"courageous": [{"partOfSpeech": "adjective", "definition": "Not deterred by danger or pain; brave and fearless."}],
"courthouse": [{"partOfSpeech": "noun", "definition": "A building in which judicial proceedings are held."}],
"covariance": [{"partOfSpeech": "noun", "definition": "A statistical measure of how two variables change together."}],
"creatively": [{"partOfSpeech": "adverb", "definition": "In an original and imaginative manner."}],
"creativity": [{"partOfSpeech": "noun", "definition": "The use of imagination to produce original ideas or things."}],
"credential": [{"partOfSpeech": "noun", "definition": "A qualification or achievement proving a person's capability."}],
"critically": [{"partOfSpeech": "adverb", "definition": "In a way that involves careful analysis, or at a crucial point."}],
"criticised": [{"partOfSpeech": "verb", "definition": "Expressed disapproval of someone or something (British spelling)."}],
"criticisms": [{"partOfSpeech": "noun", "definition": "Expressions of disapproval based on perceived faults or mistakes."}],
"criticized": [{"partOfSpeech": "verb", "definition": "Expressed disapproval of someone or something based on faults."}],
"crossroads": [{"partOfSpeech": "noun", "definition": "An intersection of two or more roads, or a crucial point of decision."}],
"crosswords": [{"partOfSpeech": "noun", "definition": "Word puzzles consisting of a grid to be filled using given clues."}],
"cultivated": [{"partOfSpeech": "adjective", "definition": "Refined and well educated, or prepared and used for growing crops."}],
"culturally": [{"partOfSpeech": "adverb", "definition": "In ways relating to the ideas, customs, and arts of a society."}],
"cumbersome": [{"partOfSpeech": "adjective", "definition": "Large, heavy, and difficult to carry or use; unwieldy."}],
"cumulative": [{"partOfSpeech": "adjective", "definition": "Increasing by successive additions over time."}],
"currencies": [{"partOfSpeech": "noun", "definition": "Systems of money in general use in particular countries."}],
"curricular": [{"partOfSpeech": "adjective", "definition": "Relating to the subjects and courses taught in a school program."}],
"cushioning": [{"partOfSpeech": "noun", "definition": "Soft padding that absorbs impact or provides comfort."}],
"customized": [{"partOfSpeech": "adjective", "definition": "Modified or built according to individual specifications."}],
};

// The file is getting very large - we'll continue with D-Z in separate batch files
// For now, write just the A-C batch
const merged = { ...existing, ...newDefs };

// Count coverage
const answerSet = new Set(answers);
const defSet = new Set(Object.keys(merged));
const covered = answers.filter(w => defSet.has(w));
console.log(`Coverage: ${covered.length}/${answers.length} (${(covered.length/answers.length*100).toFixed(1)}%)`);
console.log(`Still missing: ${answers.length - covered.length}`);

// Write intermediate result
writeFileSync("./data/word-definitions.json", JSON.stringify(merged, null, 2) + "\n");
console.log("Written to word-definitions.json");
