import { readFileSync, writeFileSync } from "fs";
const existing = JSON.parse(readFileSync("./data/word-definitions.json", "utf-8"));
const newDefs = {
  "galvanized": [{"partOfSpeech": "verb", "definition": "Shocked or excited someone into taking action, or coated iron or steel with a protective zinc layer"}],
  "gatekeeper": [{"partOfSpeech": "noun", "definition": "A person or system that controls access to something, deciding who is allowed entry or participation"}],
  "gatherings": [{"partOfSpeech": "noun", "definition": "Assemblies or meetings of people who come together for a shared purpose or social occasion"}],
  "generality": [{"partOfSpeech": "noun", "definition": "A broad statement or concept lacking specific details; the quality of being applicable to most cases"}],
  "generating": [{"partOfSpeech": "verb", "definition": "Producing or creating something, such as electricity, ideas, or revenue"}],
  "generation": [{"partOfSpeech": "noun", "definition": "A group of people born and living around the same time, or the act of producing something"}],
  "generators": [{"partOfSpeech": "noun", "definition": "Machines or devices that convert mechanical energy into electrical power"}],
  "generously": [{"partOfSpeech": "adverb", "definition": "In a way that shows willingness to give more than is expected or necessary; liberally"}],
  "geographic": [{"partOfSpeech": "adjective", "definition": "Relating to the physical features and regions of the earth's surface"}],
  "geological": [{"partOfSpeech": "adjective", "definition": "Relating to the science of the earth's physical structure, substance, and history"}],
  "geophysics": [{"partOfSpeech": "noun", "definition": "The branch of science concerned with physical properties and processes of the earth and its surroundings"}],
  "geothermal": [{"partOfSpeech": "adjective", "definition": "Relating to or produced by the internal heat of the earth"}],
  "geriatrics": [{"partOfSpeech": "noun", "definition": "The branch of medicine focused on health care of elderly people"}],
  "girlfriend": [{"partOfSpeech": "noun", "definition": "A female romantic partner in a relationship, or a close female companion"}],
  "glittering": [{"partOfSpeech": "adjective", "definition": "Shining with a bright, shimmering, reflected light; impressively successful or glamorous"}],
  "glossaries": [{"partOfSpeech": "noun", "definition": "Alphabetical lists of terms with definitions, typically found at the end of a book or document"}],
  "goalkeeper": [{"partOfSpeech": "noun", "definition": "A player positioned in front of the net whose role is to prevent the opposing team from scoring"}],
  "governance": [{"partOfSpeech": "noun", "definition": "The system or process of directing and controlling an organization, country, or institution"}],
  "government": [{"partOfSpeech": "noun", "definition": "The ruling body of a nation, state, or community that exercises authority and performs functions of administration"}],
  "gracefully": [{"partOfSpeech": "adverb", "definition": "In an elegant, smooth, and attractive manner; with poise and dignity"}],
  "graduating": [{"partOfSpeech": "verb", "definition": "Successfully completing an academic degree or course of study at an educational institution"}],
  "graduation": [{"partOfSpeech": "noun", "definition": "The ceremony or process of receiving an academic degree or diploma upon completing studies"}],
  "grapefruit": [{"partOfSpeech": "noun", "definition": "A large round citrus fruit with a slightly bitter, tangy pulp, typically yellow or pink inside"}],
  "grasslands": [{"partOfSpeech": "noun", "definition": "Large open areas of terrain covered primarily with grasses rather than tall shrubs or trees"}],
  "grassroots": [{"partOfSpeech": "adjective", "definition": "Relating to ordinary people in a community, especially as the basis of a political or social movement"}],
  "gratefully": [{"partOfSpeech": "adverb", "definition": "In a manner expressing thanks and appreciation for something received or experienced"}],
  "greenhouse": [{"partOfSpeech": "noun", "definition": "A glass or plastic structure used for growing plants in controlled warm conditions"}],
  "grievances": [{"partOfSpeech": "noun", "definition": "Formal complaints about unfair treatment or perceived wrongs, especially in a workplace context"}],
  "groundwork": [{"partOfSpeech": "noun", "definition": "Preliminary or basic work done as preparation and foundation for something more advanced"}],
  "guaranteed": [{"partOfSpeech": "verb", "definition": "Provided a formal promise or assurance that certain conditions would be fulfilled"}],
  "guarantees": [{"partOfSpeech": "noun", "definition": "Formal promises or assurances that certain conditions will be fulfilled, often legally binding"}],
  "guesthouse": [{"partOfSpeech": "noun", "definition": "A small lodging establishment or a private house offering accommodation to paying visitors"}],
  "guidebooks": [{"partOfSpeech": "noun", "definition": "Books of information about a place, designed to help travelers or tourists navigate and explore"}],
  "guidelines": [{"partOfSpeech": "noun", "definition": "Recommended rules or instructions that indicate how something should be done or what conduct is expected"}],
  "gymnastics": [{"partOfSpeech": "noun", "definition": "A sport involving physical exercises and routines requiring balance, strength, flexibility, and coordination"}],
  "hairstyles": [{"partOfSpeech": "noun", "definition": "Particular ways in which a person's locks are cut, arranged, or worn"}],
  "handspring": [{"partOfSpeech": "noun", "definition": "An acrobatic move in which a person flips forward or backward onto the hands and then onto the feet"}],
  "happenings": [{"partOfSpeech": "noun", "definition": "Events or occurrences, especially ones that are interesting, significant, or unusual"}],
  "harassment": [{"partOfSpeech": "noun", "definition": "Aggressive pressure or intimidation directed at someone, causing distress or discomfort"}],
  "harmonious": [{"partOfSpeech": "adjective", "definition": "Forming a pleasing or consistent whole; free from disagreement or conflict"}],
  "harvesting": [{"partOfSpeech": "verb", "definition": "Gathering crops or other natural resources when they are ripe or ready for collection"}],
  "headlights": [{"partOfSpeech": "noun", "definition": "Powerful lamps mounted on the front of a vehicle to illuminate the road ahead at night"}],
  "headphones": [{"partOfSpeech": "noun", "definition": "A pair of small speakers worn on or over the ears for listening to audio privately"}],
  "healthiest": [{"partOfSpeech": "adjective", "definition": "Superlative form indicating the greatest degree of physical well-being or beneficial quality"}],
  "heartbreak": [{"partOfSpeech": "noun", "definition": "Overwhelming distress or grief, especially caused by the end of a love affair or deep disappointment"}],
  "heightened": [{"partOfSpeech": "adjective", "definition": "Made more intense, increased, or elevated beyond the normal level"}],
  "hemorrhage": [{"partOfSpeech": "noun", "definition": "An escape of blood from a ruptured vessel, especially when profuse and potentially dangerous"}],
  "herbicides": [{"partOfSpeech": "noun", "definition": "Chemical substances used to destroy unwanted plants or inhibit their growth"}],
  "hesitation": [{"partOfSpeech": "noun", "definition": "The action of pausing or delaying before saying or doing something, often due to uncertainty"}],
  "heuristics": [{"partOfSpeech": "noun", "definition": "Practical problem-solving approaches or mental shortcuts that employ experience-based techniques"}],
  "highlander": [{"partOfSpeech": "noun", "definition": "A person who lives in or comes from a mountainous region, especially the Scottish uplands"}],
  "highlights": [{"partOfSpeech": "noun", "definition": "The most interesting, memorable, or important parts of an event or period of time"}],
  "historians": [{"partOfSpeech": "noun", "definition": "Scholars who study and write about events and developments of the past"}],
  "historical": [{"partOfSpeech": "adjective", "definition": "Relating to or concerning events, people, or things from the past"}],
  "hitchhiker": [{"partOfSpeech": "noun", "definition": "A person who travels by getting free rides in passing vehicles along a road"}],
  "homecoming": [{"partOfSpeech": "noun", "definition": "A return to one's place of origin, or an annual celebration at a school welcoming back former students"}],
  "homeowners": [{"partOfSpeech": "noun", "definition": "People who own the house or apartment in which they live"}],
  "homologous": [{"partOfSpeech": "adjective", "definition": "Having a similar position, structure, or evolutionary origin, though not necessarily identical in function"}],
  "homosexual": [{"partOfSpeech": "adjective", "definition": "Relating to or characterized by romantic or sexual attraction to people of one's own sex"}],
  "honeymoons": [{"partOfSpeech": "noun", "definition": "Vacations taken by newlywed couples after their wedding ceremony"}],
  "honourable": [{"partOfSpeech": "adjective", "definition": "Deserving of respect and admiration; adhering to ethical principles and moral integrity"}],
  "hoodwinked": [{"partOfSpeech": "verb", "definition": "Deceived or tricked someone through cunning or dishonest means"}],
  "horizontal": [{"partOfSpeech": "adjective", "definition": "Parallel to the plane of the ground; at right angles to the vertical direction"}],
  "horoscopes": [{"partOfSpeech": "noun", "definition": "Astrological forecasts based on the position of celestial bodies at the time of a person's birth"}],
  "horsepower": [{"partOfSpeech": "noun", "definition": "A unit of measurement for the rate at which work is done, commonly used for engine output"}],
  "households": [{"partOfSpeech": "noun", "definition": "Units consisting of the people living together in a single dwelling or home"}],
  "housewares": [{"partOfSpeech": "noun", "definition": "Small items used in the kitchen and for other domestic purposes, such as utensils and containers"}],
  "housewives": [{"partOfSpeech": "noun", "definition": "Women whose primary occupation is managing their family's domestic affairs and running the home"}],
  "humanities": [{"partOfSpeech": "noun", "definition": "Academic disciplines that study aspects of human society and culture, including literature, philosophy, and history"}],
  "humidifier": [{"partOfSpeech": "noun", "definition": "A device that adds moisture to indoor air to prevent dryness and maintain comfortable conditions"}],
  "hurricanes": [{"partOfSpeech": "noun", "definition": "Severe tropical storms with violent winds exceeding 74 mph, forming over warm ocean waters"}],
  "hydraulics": [{"partOfSpeech": "noun", "definition": "The branch of science and technology concerned with using pressurized liquids to generate mechanical force"}],
  "hydrolysis": [{"partOfSpeech": "noun", "definition": "A chemical reaction in which a compound is broken down by reacting with water molecules"}],
  "hypotheses": [{"partOfSpeech": "noun", "definition": "Proposed explanations or educated assumptions made on limited evidence as starting points for investigation"}],
  "hypothesis": [{"partOfSpeech": "noun", "definition": "A proposed explanation for a phenomenon, serving as a starting point for further investigation and testing"}],
  "hysterical": [{"partOfSpeech": "adjective", "definition": "Affected by or deriving from wildly uncontrolled emotion, or extremely funny and amusing"}],
  "identified": [{"partOfSpeech": "verb", "definition": "Established or recognized who or what someone or something is"}],
  "identifier": [{"partOfSpeech": "noun", "definition": "A sequence of characters or label used to uniquely distinguish one entity from another"}],
  "identifies": [{"partOfSpeech": "verb", "definition": "Establishes or recognizes who or what someone or something is"}],
  "identities": [{"partOfSpeech": "noun", "definition": "The distinguishing characteristics, qualities, or conditions that make a person or group recognizable"}],
  "ideologies": [{"partOfSpeech": "noun", "definition": "Systems of ideas and ideals forming the basis of economic or political theory and policy"}],
  "illiterate": [{"partOfSpeech": "adjective", "definition": "Unable to read or write; lacking knowledge in a particular subject or field"}],
  "imaginable": [{"partOfSpeech": "adjective", "definition": "Possible to think of or conceive; within the scope of what can be envisioned"}],
  "immigrants": [{"partOfSpeech": "noun", "definition": "People who come to live permanently in a foreign country different from their place of birth"}],
  "impairment": [{"partOfSpeech": "noun", "definition": "The state of being diminished, weakened, or damaged in strength, value, or quality"}],
  "impeccable": [{"partOfSpeech": "adjective", "definition": "In accordance with the highest standards of propriety; faultless and flawless"}],
  "imperative": [{"partOfSpeech": "adjective", "definition": "Of vital importance; crucial and urgent, demanding immediate attention or action"}],
  "implements": [{"partOfSpeech": "verb", "definition": "Puts a plan, decision, or agreement into effect; carries out or executes"}],
  "implicated": [{"partOfSpeech": "verb", "definition": "Shown to be involved in or connected to something, typically a crime or wrongdoing"}],
  "implicitly": [{"partOfSpeech": "adverb", "definition": "In a way that is suggested but not directly expressed; without question or reservation"}],
  "importance": [{"partOfSpeech": "noun", "definition": "The quality of being significant, valuable, or having great worth or consequence"}],
  "imposition": [{"partOfSpeech": "noun", "definition": "The act of forcing something unwelcome or unfamiliar to be accepted or put in place"}],
  "impossible": [{"partOfSpeech": "adjective", "definition": "Not able to occur, exist, or be done; beyond the realm of feasibility"}],
  "impression": [{"partOfSpeech": "noun", "definition": "An idea, feeling, or opinion formed about someone or something, often without conscious thought"}],
  "impressive": [{"partOfSpeech": "adjective", "definition": "Evoking admiration through size, quality, skill, or some other notable attribute"}],
  "imprisoned": [{"partOfSpeech": "verb", "definition": "Kept in a jail or confined space; deprived of liberty and freedom of movement"}],
  "improbable": [{"partOfSpeech": "adjective", "definition": "Not likely to be true or to happen; unexpected and seemingly beyond reasonable chance"}],
  "improperly": [{"partOfSpeech": "adverb", "definition": "In a way that is not in accordance with accepted rules, standards, or procedures"}],
  "impurities": [{"partOfSpeech": "noun", "definition": "Substances mixed into something that reduce its quality, cleanliness, or purity"}],
  "imputation": [{"partOfSpeech": "noun", "definition": "The act of attributing something, especially blame or a quality, to someone or something"}],
  "inaccurate": [{"partOfSpeech": "adjective", "definition": "Not correct or exact; containing errors or deviating from the truth"}],
  "inactivity": [{"partOfSpeech": "noun", "definition": "The state of not engaging in physical movement or productive effort; idleness"}],
  "inadequate": [{"partOfSpeech": "adjective", "definition": "Lacking the quality or quantity required; insufficient for a particular purpose"}],
  "incapacity": [{"partOfSpeech": "noun", "definition": "The physical or mental inability to do something or to manage one's own affairs"}],
  "incentives": [{"partOfSpeech": "noun", "definition": "Things that motivate or encourage someone to act in a particular way, often rewards or benefits"}],
  "incidental": [{"partOfSpeech": "adjective", "definition": "Occurring as a minor consequence of something else; not essential or deliberate"}],
  "inclusions": [{"partOfSpeech": "noun", "definition": "The acts of including something as part of a group, set, or total; items added within"}],
  "incomplete": [{"partOfSpeech": "adjective", "definition": "Not having all the necessary or expected parts; not fully finished or whole"}],
  "increasing": [{"partOfSpeech": "adjective", "definition": "Becoming progressively greater or more in size, amount, intensity, or degree"}],
  "incredible": [{"partOfSpeech": "adjective", "definition": "Extraordinarily great or extreme; difficult to believe due to being so remarkable"}],
  "incredibly": [{"partOfSpeech": "adverb", "definition": "To a great or extraordinary degree; in a manner hard to believe"}],
  "increments": [{"partOfSpeech": "noun", "definition": "Regular, usually small, increases in amount, number, or value over successive stages"}],
  "incubation": [{"partOfSpeech": "noun", "definition": "The process of keeping eggs warm for hatching, or the period during which an infection develops before symptoms appear"}],
  "indefinite": [{"partOfSpeech": "adjective", "definition": "Lasting for an unknown or unstated length of time; not clearly defined or determined"}],
  "indicating": [{"partOfSpeech": "verb", "definition": "Pointing out, showing, or serving as a sign or signal of something"}],
  "indication": [{"partOfSpeech": "noun", "definition": "A sign or piece of information that suggests something is the case"}],
  "indicative": [{"partOfSpeech": "adjective", "definition": "Serving as a sign or signal; suggestive of a particular condition or trend"}],
  "indicators": [{"partOfSpeech": "noun", "definition": "Things that serve as signs, signals, or measures showing the state or level of something"}],
  "indictment": [{"partOfSpeech": "noun", "definition": "A formal charge or accusation of a serious crime, or something that serves as severe criticism"}],
  "indigenous": [{"partOfSpeech": "adjective", "definition": "Originating or occurring naturally in a particular place; native to a region"}],
  "indirectly": [{"partOfSpeech": "adverb", "definition": "In a way that is not straight or immediate; through an intermediary or secondary means"}],
  "individual": [{"partOfSpeech": "noun", "definition": "A single human being as distinct from a group, class, or family"}],
  "indulgence": [{"partOfSpeech": "noun", "definition": "The act of allowing oneself enjoyment of pleasures, or tolerance of someone's wishes"}],
  "industrial": [{"partOfSpeech": "adjective", "definition": "Relating to or characterized by manufacturing, factories, and the production of goods"}],
  "industries": [{"partOfSpeech": "noun", "definition": "Sectors of economic activity concerned with the processing of raw materials and manufacturing of goods"}],
  "ineligible": [{"partOfSpeech": "adjective", "definition": "Not qualified or entitled to be chosen or to participate; disqualified"}],
  "inevitable": [{"partOfSpeech": "adjective", "definition": "Certain to happen; unavoidable and impossible to prevent from occurring"}],
  "inevitably": [{"partOfSpeech": "adverb", "definition": "As is certain to happen; in a way that cannot be avoided or prevented"}],
  "infarction": [{"partOfSpeech": "noun", "definition": "The death of tissue due to an inadequate blood supply, commonly occurring in the heart"}],
  "infections": [{"partOfSpeech": "noun", "definition": "Invasions of body tissues by disease-causing organisms that multiply and produce toxins"}],
  "infectious": [{"partOfSpeech": "adjective", "definition": "Capable of being transmitted from one person to another through contact or proximity"}],
  "inferences": [{"partOfSpeech": "noun", "definition": "Conclusions reached on the basis of evidence and reasoning rather than explicit statements"}],
  "infinitely": [{"partOfSpeech": "adverb", "definition": "To an unlimited or immeasurably great extent or degree; without bounds"}],
  "inflatable": [{"partOfSpeech": "adjective", "definition": "Capable of being filled with air or gas to expand to full size and shape"}],
  "influenced": [{"partOfSpeech": "verb", "definition": "Had an effect on the character, development, or behavior of someone or something"}],
  "influences": [{"partOfSpeech": "noun", "definition": "Effects or impacts that one person or thing has on the character or behavior of another"}],
  "informally": [{"partOfSpeech": "adverb", "definition": "In a relaxed, casual manner without official status or strict adherence to rules"}],
  "infrequent": [{"partOfSpeech": "adjective", "definition": "Not occurring often; rare and happening at long intervals"}],
  "infringing": [{"partOfSpeech": "verb", "definition": "Actively breaking the terms of a law, agreement, or right; violating or transgressing"}],
  "inhalation": [{"partOfSpeech": "noun", "definition": "The act of breathing in air, gas, or other substances into the lungs"}],
  "inherently": [{"partOfSpeech": "adverb", "definition": "In a permanent, essential, or characteristic way; by its very nature"}],
  "inhibiting": [{"partOfSpeech": "verb", "definition": "Hindering, restraining, or preventing an action or process from occurring"}],
  "inhibition": [{"partOfSpeech": "noun", "definition": "A feeling of self-consciousness that restrains behavior, or the slowing or prevention of a process"}],
  "inhibitors": [{"partOfSpeech": "noun", "definition": "Substances or agents that slow down or prevent a particular chemical reaction or biological process"}],
  "inhibitory": [{"partOfSpeech": "adjective", "definition": "Having the effect of restraining, blocking, or suppressing a physiological or chemical activity"}],
  "initiating": [{"partOfSpeech": "verb", "definition": "Causing a process or action to begin; setting something in motion"}],
  "initiation": [{"partOfSpeech": "noun", "definition": "The act of beginning something, or a ceremony admitting someone into a group or society"}],
  "initiative": [{"partOfSpeech": "noun", "definition": "The ability to assess and act on opportunities independently; a new plan or strategy to address a need"}],
  "injections": [{"partOfSpeech": "noun", "definition": "Acts of introducing a substance into the body using a syringe and needle"}],
  "injunction": [{"partOfSpeech": "noun", "definition": "A judicial order restraining a person from a specific act, or an authoritative warning or command"}],
  "innovation": [{"partOfSpeech": "noun", "definition": "The introduction of new methods, ideas, or products; a creative change in established practices"}],
  "innovative": [{"partOfSpeech": "adjective", "definition": "Featuring new methods or ideas; advanced, original, and creatively forward-thinking"}],
  "innovators": [{"partOfSpeech": "noun", "definition": "People who introduce new methods, ideas, or products that change established practices"}],
  "insecurity": [{"partOfSpeech": "noun", "definition": "A state of uncertainty or anxiety about oneself; lack of confidence or a condition of being unsafe"}],
  "insertions": [{"partOfSpeech": "noun", "definition": "Acts of placing or adding something into a particular position within something else"}],
  "insightful": [{"partOfSpeech": "adjective", "definition": "Having or showing an accurate and deep understanding; perceptive and discerning"}],
  "insistence": [{"partOfSpeech": "noun", "definition": "The act of demanding something firmly and refusing to accept refusal or compromise"}],
  "insolvency": [{"partOfSpeech": "noun", "definition": "The state of being unable to pay debts owed; financial failure or bankruptcy"}],
  "inspecting": [{"partOfSpeech": "verb", "definition": "Looking at something closely and carefully to assess its condition, quality, or compliance"}],
  "inspection": [{"partOfSpeech": "noun", "definition": "A careful examination or scrutiny of something to assess its condition or verify standards"}],
  "inspectors": [{"partOfSpeech": "noun", "definition": "Officials who examine and verify that rules, standards, and regulations are being followed"}],
  "installers": [{"partOfSpeech": "noun", "definition": "People or programs that set up equipment, software, or systems for use"}],
  "installing": [{"partOfSpeech": "verb", "definition": "Setting up equipment, software, or a system so it is ready for use"}],
  "instituted": [{"partOfSpeech": "verb", "definition": "Set in motion or established a system, policy, or course of action"}],
  "institutes": [{"partOfSpeech": "noun", "definition": "Organizations or establishments devoted to a particular purpose, especially research or education"}],
  "instructed": [{"partOfSpeech": "verb", "definition": "Directed or commanded someone to do something; taught or trained a person in a subject"}],
  "instructor": [{"partOfSpeech": "noun", "definition": "A person who teaches a skill or subject; a trainer or educator"}],
  "instrument": [{"partOfSpeech": "noun", "definition": "A tool or device used for a particular purpose, especially for delicate or scientific work, or for making music"}],
  "insulating": [{"partOfSpeech": "verb", "definition": "Protecting something by surrounding it with material that prevents the loss of heat, sound, or electricity"}],
  "insulation": [{"partOfSpeech": "noun", "definition": "Material used to prevent the passage of heat, electricity, or sound between surfaces"}],
  "insurgency": [{"partOfSpeech": "noun", "definition": "An active revolt or uprising against an established authority or ruling power"}],
  "insurgents": [{"partOfSpeech": "noun", "definition": "Rebels who rise up against an established civil authority or ruling power"}],
  "intangible": [{"partOfSpeech": "adjective", "definition": "Unable to be touched or grasped physically; not having a concrete or material form"}],
  "integrated": [{"partOfSpeech": "adjective", "definition": "Combined or unified into a whole; having various parts or aspects linked together seamlessly"}],
  "integrates": [{"partOfSpeech": "verb", "definition": "Combines one thing with another so that they become a unified whole"}],
  "integrator": [{"partOfSpeech": "noun", "definition": "A person or entity that combines different components or systems into a functioning unified whole"}],
  "intentions": [{"partOfSpeech": "noun", "definition": "Aims or plans that a person has in mind as a purpose or goal for action"}],
  "interested": [{"partOfSpeech": "adjective", "definition": "Showing curiosity or concern about something; wanting to learn more or become involved"}],
  "interfaces": [{"partOfSpeech": "noun", "definition": "Points where two systems, subjects, or organizations meet and interact with each other"}],
  "internally": [{"partOfSpeech": "adverb", "definition": "Within the inside of something; relating to affairs within an organization rather than outside"}],
  "internship": [{"partOfSpeech": "noun", "definition": "A temporary position offering practical work experience in a professional field, often for students"}],
  "interprets": [{"partOfSpeech": "verb", "definition": "Explains the meaning of something, or translates spoken words from one language to another"}],
  "interrupts": [{"partOfSpeech": "verb", "definition": "Stops the continuous progress of an activity or speech by breaking in"}],
  "interstate": [{"partOfSpeech": "adjective", "definition": "Existing or carried on between states, especially of the US; a highway connecting multiple states"}],
  "interviews": [{"partOfSpeech": "noun", "definition": "Formal meetings in which someone is asked questions for a job, by the media, or for research"}],
  "intestinal": [{"partOfSpeech": "adjective", "definition": "Relating to or affecting the long tubular organ in the abdomen where digestion is completed"}],
  "intimately": [{"partOfSpeech": "adverb", "definition": "In a closely personal or private manner; with detailed and thorough knowledge"}],
  "intramural": [{"partOfSpeech": "adjective", "definition": "Taking place within a single institution, especially sports or activities among its own members"}],
  "intriguing": [{"partOfSpeech": "adjective", "definition": "Arousing great curiosity or interest; fascinating and captivating"}],
  "introduced": [{"partOfSpeech": "verb", "definition": "Brought something into use or operation for the first time; presented one person to another"}],
  "introduces": [{"partOfSpeech": "verb", "definition": "Brings something into use or operation for the first time; presents one person to another"}],
  "invaluable": [{"partOfSpeech": "adjective", "definition": "Extremely useful and essential; too great in worth to be estimated or measured"}],
  "invariably": [{"partOfSpeech": "adverb", "definition": "In every case or on every occasion; always without exception"}],
  "inventions": [{"partOfSpeech": "noun", "definition": "New devices, methods, or processes developed from study and experimentation; creative creations"}],
  "investment": [{"partOfSpeech": "noun", "definition": "The allocation of money or resources with the expectation of achieving a profit or beneficial return"}],
  "invincible": [{"partOfSpeech": "adjective", "definition": "Too powerful to be defeated or overcome; unconquerable"}],
  "invitation": [{"partOfSpeech": "noun", "definition": "A written or verbal request asking someone to go somewhere or to do something"}],
  "invocation": [{"partOfSpeech": "noun", "definition": "The act of calling upon a higher power, authority, or principle for aid, support, or inspiration"}],
  "ionization": [{"partOfSpeech": "noun", "definition": "The process by which atoms or molecules gain or lose electrons to form charged particles"}],
  "ironically": [{"partOfSpeech": "adverb", "definition": "In a manner contrary to what was expected; used to denote a paradoxical or unexpected outcome"}],
  "irradiated": [{"partOfSpeech": "verb", "definition": "Exposed to radiation, especially for sterilization, medical treatment, or scientific purposes"}],
  "irrational": [{"partOfSpeech": "adjective", "definition": "Not logical or reasonable; based on emotions rather than clear thinking"}],
  "irrelevant": [{"partOfSpeech": "adjective", "definition": "Not connected with or relating to the matter at hand; beside the point"}],
  "irrigation": [{"partOfSpeech": "noun", "definition": "The artificial supply of water to land or crops to assist growth, typically through channels or pipes"}],
  "irritating": [{"partOfSpeech": "adjective", "definition": "Causing annoyance, impatience, or mild anger; provoking discomfort"}],
  "irritation": [{"partOfSpeech": "noun", "definition": "The state of feeling annoyed, impatient, or slightly angry; inflammation of a body part"}],
  "italicized": [{"partOfSpeech": "adjective", "definition": "Printed or displayed in a slanted typeface, typically used for emphasis or titles"}],
  "iterations": [{"partOfSpeech": "noun", "definition": "Repeated cycles or versions of a process, each building on the results of the previous one"}],
  "janitorial": [{"partOfSpeech": "adjective", "definition": "Relating to the work of cleaning and maintaining buildings and their facilities"}],
  "journalism": [{"partOfSpeech": "noun", "definition": "The activity or profession of writing, editing, and reporting news for media outlets"}],
  "journalist": [{"partOfSpeech": "noun", "definition": "A person who writes, investigates, and reports news stories for media outlets"}],
  "judgements": [{"partOfSpeech": "noun", "definition": "Opinions or conclusions formed after careful consideration; official decisions made by a court"}],
  "justifying": [{"partOfSpeech": "verb", "definition": "Showing or proving that something is right, reasonable, or warranted"}],
  "kidnapping": [{"partOfSpeech": "noun", "definition": "The criminal act of taking someone away illegally by force, typically to obtain a ransom"}],
  "kilometers": [{"partOfSpeech": "noun", "definition": "Units of measurement equal to 1,000 meters, used to express distances"}],
  "kingfisher": [{"partOfSpeech": "noun", "definition": "A brightly colored bird with a large head and long sharp bill that dives to catch fish"}],
  "laboratory": [{"partOfSpeech": "noun", "definition": "A room or building equipped for scientific experiments, research, or the manufacture of chemicals"}],
  "laminating": [{"partOfSpeech": "verb", "definition": "Covering a surface with a thin protective layer of plastic or another material"}],
  "landowners": [{"partOfSpeech": "noun", "definition": "People who own plots of land, especially large areas used for farming or development"}],
  "landscaped": [{"partOfSpeech": "adjective", "definition": "Made more attractive by altering the existing terrain with plants, paths, and decorative features"}],
  "landscapes": [{"partOfSpeech": "noun", "definition": "Visible features of an area of terrain, including physical elements and natural scenery"}],
  "laundering": [{"partOfSpeech": "verb", "definition": "Washing and ironing clothes, or concealing the origins of illegally obtained money"}],
  "leadership": [{"partOfSpeech": "noun", "definition": "The action of guiding a group or organization; the state or position of being in charge"}],
  "legislator": [{"partOfSpeech": "noun", "definition": "A person who makes laws; a member of a legislative body such as a parliament or congress"}],
  "legitimacy": [{"partOfSpeech": "noun", "definition": "The quality of being lawful, justified, or conforming to accepted rules and standards"}],
  "legitimate": [{"partOfSpeech": "adjective", "definition": "Conforming to the law or rules; able to be defended with logic or justification"}],
  "letterhead": [{"partOfSpeech": "noun", "definition": "A printed heading on stationery stating a person's or organization's name and address"}],
  "leveraging": [{"partOfSpeech": "verb", "definition": "Using a resource or advantage to maximum effect to achieve a desired outcome"}],
  "liberalism": [{"partOfSpeech": "noun", "definition": "A political and social philosophy that promotes individual rights, civil liberties, and progressive reform"}],
  "liberation": [{"partOfSpeech": "noun", "definition": "The act of setting someone or something free from imprisonment, oppression, or foreign control"}],
  "librarians": [{"partOfSpeech": "noun", "definition": "People trained to manage and organize collections of books and other informational resources"}],
  "lifestyles": [{"partOfSpeech": "noun", "definition": "The typical ways of living of individuals or groups, reflecting attitudes, habits, and values"}],
  "lighthouse": [{"partOfSpeech": "noun", "definition": "A tower or structure containing a beacon light to warn and guide ships at sea"}],
  "likelihood": [{"partOfSpeech": "noun", "definition": "The state or fact of something being probable; the chance that an event will occur"}],
  "limitation": [{"partOfSpeech": "noun", "definition": "A restriction or constraint that sets boundaries on what is possible or permissible"}],
  "limousines": [{"partOfSpeech": "noun", "definition": "Large, luxurious automobiles, typically driven by a chauffeur for special occasions"}],
  "literature": [{"partOfSpeech": "noun", "definition": "Written works, especially those considered to have artistic merit, or published material on a subject"}],
  "litigation": [{"partOfSpeech": "noun", "definition": "The process of taking legal action through the court system to resolve disputes"}],
  "liturgical": [{"partOfSpeech": "adjective", "definition": "Relating to the prescribed forms and rituals of public worship in religious services"}],
  "livelihood": [{"partOfSpeech": "noun", "definition": "A means of securing the necessities of life; a way of earning money to support oneself"}],
  "localities": [{"partOfSpeech": "noun", "definition": "Particular areas, neighborhoods, or districts within a larger region"}],
  "locomotive": [{"partOfSpeech": "noun", "definition": "A powered rail vehicle used for pulling trains along tracks"}],
  "logistical": [{"partOfSpeech": "adjective", "definition": "Relating to the detailed coordination and organization of a complex operation"}],
  "loneliness": [{"partOfSpeech": "noun", "definition": "Sadness arising from a lack of companions or social connection; the state of being alone"}],
  "lubricants": [{"partOfSpeech": "noun", "definition": "Substances such as oil or grease used to reduce friction between moving surfaces"}],
  "magnifying": [{"partOfSpeech": "verb", "definition": "Making something appear larger than it is, especially through an optical lens; amplifying"}],
  "mainstream": [{"partOfSpeech": "adjective", "definition": "Considered normal and accepted by most people; belonging to the prevailing current of thought or activity"}],
  "maintained": [{"partOfSpeech": "verb", "definition": "Kept in good condition through regular care; continued to hold a state or position over time"}],
  "maintainer": [{"partOfSpeech": "noun", "definition": "A person or entity responsible for keeping something in proper working condition"}],
  "manageable": [{"partOfSpeech": "adjective", "definition": "Able to be controlled, handled, or dealt with without great difficulty"}],
  "management": [{"partOfSpeech": "noun", "definition": "The process of dealing with or controlling things or people; those in charge of running an organization"}],
  "managerial": [{"partOfSpeech": "adjective", "definition": "Relating to the role of directing and overseeing the operations of a business or organization"}],
  "manifested": [{"partOfSpeech": "verb", "definition": "Displayed or showed a quality, feeling, or condition clearly through appearance or actions"}],
  "manuscript": [{"partOfSpeech": "noun", "definition": "A handwritten or typed document, especially an author's original text before publication"}],
  "marginally": [{"partOfSpeech": "adverb", "definition": "To a small extent; slightly, by only a narrow margin or degree"}],
  "marguerite": [{"partOfSpeech": "noun", "definition": "A type of daisy-like flower with white petals and a yellow center, native to the Canary Islands"}],
  "marketable": [{"partOfSpeech": "adjective", "definition": "Able to be sold or traded; attractive to buyers or employers in a competitive setting"}],
  "marvellous": [{"partOfSpeech": "adjective", "definition": "Causing great wonder or astonishment; extremely good or pleasing"}],
  "masquerade": [{"partOfSpeech": "noun", "definition": "A false show or pretense; a party where guests wear masks and costumes to conceal their identity"}],
  "masturbate": [{"partOfSpeech": "verb", "definition": "To stimulate one's own body for sexual pleasure through self-touch"}],
  "matchmaker": [{"partOfSpeech": "noun", "definition": "A person who arranges romantic relationships or partnerships between others"}],
  "materially": [{"partOfSpeech": "adverb", "definition": "In a significant or substantial way; relating to physical possessions rather than spiritual matters"}],
  "mattresses": [{"partOfSpeech": "noun", "definition": "Fabric cases filled with soft or firm material, placed on bed frames for sleeping on"}],
  "maturation": [{"partOfSpeech": "noun", "definition": "The process of becoming fully developed or ripe, physically or mentally"}],
  "maximizing": [{"partOfSpeech": "verb", "definition": "Making as large or great as possible; increasing to the highest achievable level"}],
  "meaningful": [{"partOfSpeech": "adjective", "definition": "Having a serious, important, or useful quality or purpose; full of significance"}],
  "measurable": [{"partOfSpeech": "adjective", "definition": "Able to be quantified or assessed; large enough to be noticed or have a clear effect"}],
  "mechanical": [{"partOfSpeech": "adjective", "definition": "Relating to or operated by machines or physical forces; done without thought or spontaneity"}],
  "mechanisms": [{"partOfSpeech": "noun", "definition": "Systems of parts working together in a machine, or processes by which something takes place"}],
  "medication": [{"partOfSpeech": "noun", "definition": "A substance used for medical treatment, especially a drug taken to cure or relieve symptoms"}],
  "meditation": [{"partOfSpeech": "noun", "definition": "A practice of focused concentration or reflection, often used to achieve mental clarity and calm"}],
  "melancholy": [{"partOfSpeech": "noun", "definition": "A deep, persistent feeling of sadness and gloom, often with no obvious cause"}],
  "membership": [{"partOfSpeech": "noun", "definition": "The state of belonging to a group or organization; the total number of members in a body"}],
  "memorandum": [{"partOfSpeech": "noun", "definition": "A written message or note, especially in business or diplomacy, communicating policies or procedures"}],
  "meningitis": [{"partOfSpeech": "noun", "definition": "An acute inflammation of the protective membranes covering the brain and spinal cord"}],
  "mentioning": [{"partOfSpeech": "verb", "definition": "Referring to something briefly or casually in speech or writing without going into detail"}],
  "messengers": [{"partOfSpeech": "noun", "definition": "People or agents who carry messages, information, or communications between parties"}],
  "metabolism": [{"partOfSpeech": "noun", "definition": "The chemical processes occurring within a living organism to maintain life, converting food into energy"}],
  "metastasis": [{"partOfSpeech": "noun", "definition": "The spread of a disease, especially cancer, from one part of the body to another via blood or lymph"}],
  "metropolis": [{"partOfSpeech": "noun", "definition": "A very large, densely populated city, often the chief city of a country or region"}],
  "microdrive": [{"partOfSpeech": "noun", "definition": "A miniature hard disk storage device, originally designed for use in compact digital devices"}],
  "microphone": [{"partOfSpeech": "noun", "definition": "An instrument for converting sound waves into electrical energy signals, used for recording or amplifying audio"}],
  "microscope": [{"partOfSpeech": "noun", "definition": "An optical instrument used to view objects too small to be seen by the naked eye"}],
  "microwaves": [{"partOfSpeech": "noun", "definition": "Electromagnetic waves with short wavelengths, or appliances that use such waves to heat food"}],
  "midwestern": [{"partOfSpeech": "adjective", "definition": "Relating to the central region of the United States, between the Appalachians and the Rockies"}],
  "milestones": [{"partOfSpeech": "noun", "definition": "Significant stages or events in the development or progress of something"}],
  "millennium": [{"partOfSpeech": "noun", "definition": "A period of one thousand years, or an anniversary marking such a span of time"}],
  "milligrams": [{"partOfSpeech": "noun", "definition": "Units of mass equal to one thousandth of a gram, used to measure small quantities"}],
  "miniatures": [{"partOfSpeech": "noun", "definition": "Very small representations or models of something, often highly detailed despite their reduced size"}],
  "minimalist": [{"partOfSpeech": "adjective", "definition": "Characterized by the use of the fewest possible elements to achieve maximum effect; spare and simple"}],
  "minimizing": [{"partOfSpeech": "verb", "definition": "Reducing something to the smallest possible amount, extent, or degree"}],
  "ministries": [{"partOfSpeech": "noun", "definition": "Departments of a national or regional authority headed by a minister; religious service organizations"}],
  "minorities": [{"partOfSpeech": "noun", "definition": "Smaller groups within a community that differ from the dominant group in ethnicity, religion, or other factors"}],
  "miraculous": [{"partOfSpeech": "adjective", "definition": "Occurring through divine or supernatural power; remarkably extraordinary and seemingly impossible"}],
  "misconduct": [{"partOfSpeech": "noun", "definition": "Unacceptable or improper behavior, especially by a professional person or someone in authority"}],
  "misfortune": [{"partOfSpeech": "noun", "definition": "Bad luck, or an unfortunate event or circumstance that causes suffering or difficulty"}],
  "misleading": [{"partOfSpeech": "adjective", "definition": "Giving the wrong idea or a false impression; deceptive in nature"}],
  "missionary": [{"partOfSpeech": "noun", "definition": "A person sent on a religious mission, especially to promote a faith in a foreign country"}],
  "mistakenly": [{"partOfSpeech": "adverb", "definition": "In a way that is the result of an error; wrongly or incorrectly"}],
  "mitigating": [{"partOfSpeech": "verb", "definition": "Making something less severe, serious, or painful; lessening the impact of harm"}],
  "mitigation": [{"partOfSpeech": "noun", "definition": "The action of reducing the severity, seriousness, or painfulness of something"}],
  "modalities": [{"partOfSpeech": "noun", "definition": "Particular modes or methods of doing or experiencing something, especially in medical treatment"}],
  "moderately": [{"partOfSpeech": "adverb", "definition": "To a medium extent or degree; neither extremely nor slightly"}],
  "moderation": [{"partOfSpeech": "noun", "definition": "The avoidance of excess or extremes; the process of reviewing content for compliance with standards"}],
  "moderators": [{"partOfSpeech": "noun", "definition": "People who oversee discussions or forums and ensure participants follow established rules"}],
  "modulation": [{"partOfSpeech": "noun", "definition": "The process of varying a signal's properties, or the act of adjusting or regulating tone and pitch"}],
  "monitoring": [{"partOfSpeech": "verb", "definition": "Observing and checking the progress or quality of something over a period of time"}],
  "monoclonal": [{"partOfSpeech": "adjective", "definition": "Derived from a single cell clone, typically referring to antibodies produced by identical immune cells"}],
  "monographs": [{"partOfSpeech": "noun", "definition": "Detailed written studies or scholarly books on a single specialized subject or topic"}],
  "monumental": [{"partOfSpeech": "adjective", "definition": "Great in importance, extent, or size; serving as a lasting and impressive testament"}],
  "mosquitoes": [{"partOfSpeech": "noun", "definition": "Small flying insects that bite and suck blood, often transmitting diseases like malaria"}],
  "motherhood": [{"partOfSpeech": "noun", "definition": "The state or experience of being a female parent, encompassing the responsibilities of raising children"}],
  "motivating": [{"partOfSpeech": "verb", "definition": "Providing someone with a reason or incentive to act in a particular way; inspiring action"}],
  "motivation": [{"partOfSpeech": "noun", "definition": "The reason or desire that drives a person to act or accomplish something; inner drive"}],
  "motorbikes": [{"partOfSpeech": "noun", "definition": "Two-wheeled motor vehicles, smaller or lighter than full-sized cycles, used for transportation"}],
  "motorcycle": [{"partOfSpeech": "noun", "definition": "A two-wheeled vehicle powered by an engine, larger and faster than a standard pedal-driven cycle"}],
  "mouthpiece": [{"partOfSpeech": "noun", "definition": "The part of an instrument or device placed in or near the mouth, or a spokesperson for a group"}],
  "multimedia": [{"partOfSpeech": "noun", "definition": "Content that uses a combination of different forms such as text, audio, images, and video"}],
  "multiplied": [{"partOfSpeech": "verb", "definition": "Increased in number or quantity; performed the mathematical operation of combining equal groups"}],
  "multiplier": [{"partOfSpeech": "noun", "definition": "A factor by which a quantity is increased, or a device that amplifies a signal or force"}],
  "myocardial": [{"partOfSpeech": "adjective", "definition": "Relating to the muscular tissue of the heart wall responsible for pumping blood"}],
  "mysterious": [{"partOfSpeech": "adjective", "definition": "Difficult or impossible to understand, explain, or identify; full of secrets and intrigue"}]
};
const merged = { ...existing, ...newDefs };
const answers = JSON.parse(readFileSync("./data/words-answer.json", "utf-8"));
const covered = answers.filter(w => new Set(Object.keys(merged)).has(w));
console.log(`Coverage: ${covered.length}/${answers.length}`);
writeFileSync("./data/word-definitions.json", JSON.stringify(merged, null, 2) + "\n");
