import { readFileSync, writeFileSync } from "fs";
const existing = JSON.parse(readFileSync("./data/word-definitions.json", "utf-8"));
const newDefs = {
  "sacrificed": [{"partOfSpeech": "verb", "definition": "gave up something valuable for a greater cause or purpose"}],
  "sacrifices": [{"partOfSpeech": "noun", "definition": "acts of giving up something precious for a higher purpose or goal"}],
  "safeguards": [{"partOfSpeech": "noun", "definition": "protective measures or precautions against harm or risk"}],
  "sanctioned": [{"partOfSpeech": "verb", "definition": "officially approved or authorized; alternatively, penalized with restrictive measures"}],
  "sandwiches": [{"partOfSpeech": "noun", "definition": "food items consisting of fillings placed between two pieces of bread"}],
  "sanitation": [{"partOfSpeech": "noun", "definition": "conditions and practices relating to public health, especially clean drinking water and waste disposal"}],
  "satellites": [{"partOfSpeech": "noun", "definition": "objects orbiting a planet, either natural celestial bodies or manufactured devices launched into orbit"}],
  "satisfying": [{"partOfSpeech": "adjective", "definition": "giving fulfillment or pleasure; meeting expectations or needs"}],
  "saturation": [{"partOfSpeech": "noun", "definition": "the state of being thoroughly soaked or filled to capacity"}],
  "scattering": [{"partOfSpeech": "verb", "definition": "dispersing or spreading in various random directions"}],
  "scheduling": [{"partOfSpeech": "verb", "definition": "arranging or planning events, tasks, or activities for specific times"}],
  "schematics": [{"partOfSpeech": "noun", "definition": "detailed diagrams or technical drawings showing the layout of a circuit or mechanism"}],
  "schoolgirl": [{"partOfSpeech": "noun", "definition": "a young female student attending an educational institution"}],
  "scientific": [{"partOfSpeech": "adjective", "definition": "relating to or based on the methodical study of the natural world through observation and experimentation"}],
  "scientists": [{"partOfSpeech": "noun", "definition": "people who conduct research and study the natural world using methodical observation and experimentation"}],
  "scoreboard": [{"partOfSpeech": "noun", "definition": "a large display showing the current tally of points in a game or competition"}],
  "scrambling": [{"partOfSpeech": "verb", "definition": "moving hurriedly or awkwardly; mixing up or making unintelligible"}],
  "scratching": [{"partOfSpeech": "verb", "definition": "scraping or marking a surface with something sharp or rough"}],
  "screenings": [{"partOfSpeech": "noun", "definition": "showings of a film or program; examinations to detect disease or other conditions"}],
  "screenplay": [{"partOfSpeech": "noun", "definition": "a written text of a movie, including dialogue, stage directions, and scene descriptions"}],
  "scriptures": [{"partOfSpeech": "noun", "definition": "sacred writings or holy texts of a religion"}],
  "sculptures": [{"partOfSpeech": "noun", "definition": "three-dimensional works of art created by carving, molding, or assembling materials"}],
  "seamlessly": [{"partOfSpeech": "adverb", "definition": "in a smooth and continuous way, without visible joints or interruptions"}],
  "searchable": [{"partOfSpeech": "adjective", "definition": "capable of being queried or looked through to find specific information"}],
  "seasonally": [{"partOfSpeech": "adverb", "definition": "in a way that varies with or corresponds to particular times of year"}],
  "secondhand": [{"partOfSpeech": "adjective", "definition": "previously owned or used by another person; not new"}],
  "securities": [{"partOfSpeech": "noun", "definition": "financial instruments such as stocks and bonds that represent ownership or debt obligations"}],
  "segregated": [{"partOfSpeech": "adjective", "definition": "separated or divided along racial, ethnic, or other categorical lines"}],
  "selectable": [{"partOfSpeech": "adjective", "definition": "able to be chosen or picked from a set of options"}],
  "selections": [{"partOfSpeech": "noun", "definition": "items or options that have been chosen from a larger group"}],
  "sensations": [{"partOfSpeech": "noun", "definition": "physical feelings or perceptions resulting from stimulation of the body's receptors"}],
  "sentencing": [{"partOfSpeech": "noun", "definition": "the judicial process of declaring a punishment for a convicted person"}],
  "sentiments": [{"partOfSpeech": "noun", "definition": "feelings, attitudes, or opinions, especially those based on emotion rather than reason"}],
  "separately": [{"partOfSpeech": "adverb", "definition": "individually; apart from one another; not together"}],
  "separating": [{"partOfSpeech": "verb", "definition": "dividing, disconnecting, or moving apart from each other"}],
  "separation": [{"partOfSpeech": "noun", "definition": "the act of dividing or the state of being divided; distance between things"}],
  "sequencing": [{"partOfSpeech": "noun", "definition": "the process of determining the order of elements in a series, especially nucleotides in DNA"}],
  "sequential": [{"partOfSpeech": "adjective", "definition": "forming or following a logical order or progression, one after another"}],
  "serialized": [{"partOfSpeech": "verb", "definition": "converted into a format for storage or transmission; published in installments"}],
  "settlement": [{"partOfSpeech": "noun", "definition": "an agreement resolving a dispute; a community where people have established homes"}],
  "sharpening": [{"partOfSpeech": "verb", "definition": "making a blade or point keener; improving or refining a skill or quality"}],
  "shimmering": [{"partOfSpeech": "adjective", "definition": "gleaming with a soft, wavering light; glistening faintly"}],
  "shortening": [{"partOfSpeech": "noun", "definition": "a fat used in baking to make pastry crumbly; the act of making something briefer"}],
  "showcasing": [{"partOfSpeech": "verb", "definition": "displaying or presenting something in an attractive or favorable way"}],
  "signalling": [{"partOfSpeech": "verb", "definition": "communicating a message or instruction by means of gestures, lights, or other indicators"}],
  "signatures": [{"partOfSpeech": "noun", "definition": "handwritten names used to authorize documents; distinctive identifying marks or patterns"}],
  "silverware": [{"partOfSpeech": "noun", "definition": "eating utensils such as forks, knives, and spoons, typically made of metal"}],
  "similarity": [{"partOfSpeech": "noun", "definition": "the quality of being alike or having features in common with something else"}],
  "simplicity": [{"partOfSpeech": "noun", "definition": "the quality of being easy to understand or uncomplicated in form"}],
  "simplified": [{"partOfSpeech": "verb", "definition": "made less complex or easier to do or understand"}],
  "simplifies": [{"partOfSpeech": "verb", "definition": "makes less complex or easier to do or understand"}],
  "simplistic": [{"partOfSpeech": "adjective", "definition": "treating complex issues as if they were much less complicated than they really are"}],
  "simulating": [{"partOfSpeech": "verb", "definition": "imitating or reproducing the conditions or behavior of a real-world process"}],
  "simulation": [{"partOfSpeech": "noun", "definition": "an imitation of a real-world process or environment, often using a computer model"}],
  "simulators": [{"partOfSpeech": "noun", "definition": "devices or programs that replicate real-world conditions for training or testing purposes"}],
  "situations": [{"partOfSpeech": "noun", "definition": "sets of circumstances or conditions in which one finds oneself"}],
  "skateboard": [{"partOfSpeech": "noun", "definition": "a narrow board with wheels attached to its underside, used for riding and performing tricks"}],
  "skepticism": [{"partOfSpeech": "noun", "definition": "a doubting or questioning attitude toward accepted beliefs or claims"}],
  "snorkeling": [{"partOfSpeech": "noun", "definition": "the activity of swimming near the water's surface using a breathing tube and mask"}],
  "snowmobile": [{"partOfSpeech": "noun", "definition": "a motorized vehicle designed to travel over ice and packed winter precipitation"}],
  "soliciting": [{"partOfSpeech": "verb", "definition": "asking for or trying to obtain something from someone; seeking contributions or business"}],
  "solicitors": [{"partOfSpeech": "noun", "definition": "legal practitioners who advise clients and prepare documents, especially in British law"}],
  "solidarity": [{"partOfSpeech": "noun", "definition": "unity and mutual support within a group, especially in pursuit of a common goal"}],
  "soundtrack": [{"partOfSpeech": "noun", "definition": "the recorded music accompanying a film, television show, or video game"}],
  "spacecraft": [{"partOfSpeech": "noun", "definition": "a vehicle designed for travel or operation beyond Earth's atmosphere"}],
  "specialist": [{"partOfSpeech": "noun", "definition": "a person who concentrates on and has deep expertise in a particular field or subject"}],
  "specifying": [{"partOfSpeech": "verb", "definition": "stating or identifying something clearly, precisely, and in detail"}],
  "spectators": [{"partOfSpeech": "noun", "definition": "people who watch an event, game, or performance as an audience"}],
  "sponsoring": [{"partOfSpeech": "verb", "definition": "providing financial backing or support for an event, activity, or person"}],
  "spotlights": [{"partOfSpeech": "noun", "definition": "powerful beams of focused illumination directed at a particular person or area"}],
  "springtime": [{"partOfSpeech": "noun", "definition": "the period of the year between winter and summer, when new growth appears"}],
  "stabilized": [{"partOfSpeech": "verb", "definition": "made or became steady, firm, and unlikely to change or fluctuate"}],
  "stabilizer": [{"partOfSpeech": "noun", "definition": "a device or mechanism that keeps something steady and prevents unwanted movement"}],
  "staggering": [{"partOfSpeech": "adjective", "definition": "astonishingly large, overwhelming, or hard to believe"}],
  "standpoint": [{"partOfSpeech": "noun", "definition": "a particular perspective or position from which something is considered or evaluated"}],
  "starvation": [{"partOfSpeech": "noun", "definition": "severe suffering or death caused by prolonged lack of food and nourishment"}],
  "statements": [{"partOfSpeech": "noun", "definition": "formal declarations or accounts of facts, views, or financial records"}],
  "stationary": [{"partOfSpeech": "adjective", "definition": "not moving; remaining in one fixed position"}],
  "statistics": [{"partOfSpeech": "noun", "definition": "numerical data collected and analyzed to reveal patterns; the branch of math dealing with such data"}],
  "steakhouse": [{"partOfSpeech": "noun", "definition": "a restaurant that primarily serves grilled or broiled cuts of beef"}],
  "stereotype": [{"partOfSpeech": "noun", "definition": "a widely held but oversimplified and generalized image or idea of a particular type of person or thing"}],
  "stillwater": [{"partOfSpeech": "noun", "definition": "a body of water with no current or flow, such as a pond or lake"}],
  "stimulated": [{"partOfSpeech": "verb", "definition": "encouraged, excited, or prompted increased activity or interest in something"}],
  "stimulates": [{"partOfSpeech": "verb", "definition": "encourages, excites, or prompts increased activity or interest in something"}],
  "stipulated": [{"partOfSpeech": "verb", "definition": "demanded or specified as a required condition in an agreement or arrangement"}],
  "storefront": [{"partOfSpeech": "noun", "definition": "the facade or entrance of a retail shop facing the road or sidewalk"}],
  "straighten": [{"partOfSpeech": "verb", "definition": "make or become free from bends, curves, or irregularities; tidy up"}],
  "strategies": [{"partOfSpeech": "noun", "definition": "carefully devised plans of action designed to achieve long-term goals"}],
  "stratified": [{"partOfSpeech": "adjective", "definition": "arranged or organized in distinct horizontal layers or social levels"}],
  "strawberry": [{"partOfSpeech": "noun", "definition": "a sweet red fruit with tiny seeds on its surface, grown on low trailing plants"}],
  "streamline": [{"partOfSpeech": "verb", "definition": "make a process or organization more efficient by removing unnecessary steps or elements"}],
  "strengthen": [{"partOfSpeech": "verb", "definition": "make or become more powerful, resilient, or firmly established"}],
  "stretching": [{"partOfSpeech": "verb", "definition": "extending the body or limbs to full length; pulling something to make it longer or wider"}],
  "stronghold": [{"partOfSpeech": "noun", "definition": "a fortified place; an area where a particular group or belief is firmly established"}],
  "structural": [{"partOfSpeech": "adjective", "definition": "relating to or forming part of the framework or load-bearing arrangement of a building or object"}],
  "structured": [{"partOfSpeech": "adjective", "definition": "organized according to a plan or framework; arranged in a definite pattern"}],
  "structures": [{"partOfSpeech": "noun", "definition": "buildings or other constructed objects; organized arrangements of interrelated elements"}],
  "struggling": [{"partOfSpeech": "verb", "definition": "striving hard under difficulties; fighting or contending with great effort"}],
  "subclasses": [{"partOfSpeech": "noun", "definition": "categories that are subdivisions of a broader group, especially in taxonomy or programming"}],
  "subjective": [{"partOfSpeech": "adjective", "definition": "based on personal feelings, opinions, or interpretations rather than external facts"}],
  "subliminal": [{"partOfSpeech": "adjective", "definition": "below the threshold of conscious perception; influencing the mind without awareness"}],
  "submarines": [{"partOfSpeech": "noun", "definition": "watercraft designed to operate beneath the ocean's surface for extended periods"}],
  "submission": [{"partOfSpeech": "noun", "definition": "the act of presenting something for consideration or judgment; yielding to authority"}],
  "submissive": [{"partOfSpeech": "adjective", "definition": "ready to conform to the authority or will of others; meekly obedient"}],
  "submitting": [{"partOfSpeech": "verb", "definition": "presenting something for consideration, judgment, or approval; yielding to authority"}],
  "subroutine": [{"partOfSpeech": "noun", "definition": "a set of instructions within a program that performs a specific task and can be called repeatedly"}],
  "subscribed": [{"partOfSpeech": "verb", "definition": "arranged to receive a publication or service regularly; signed up for ongoing access"}],
  "subscriber": [{"partOfSpeech": "noun", "definition": "a person who has arranged to receive a publication or service on a regular basis"}],
  "subsection": [{"partOfSpeech": "noun", "definition": "a division or portion of a larger part, chapter, or document"}],
  "subsequent": [{"partOfSpeech": "adjective", "definition": "coming after something in time or order; following"}],
  "subsidiary": [{"partOfSpeech": "noun", "definition": "a company controlled by a larger parent corporation; something of lesser importance"}],
  "subsidized": [{"partOfSpeech": "verb", "definition": "financially supported by a government or organization to reduce costs"}],
  "substances": [{"partOfSpeech": "noun", "definition": "particular kinds of matter with uniform chemical properties; materials or compounds"}],
  "substitute": [{"partOfSpeech": "noun", "definition": "a person or thing acting in place of another; a replacement"}],
  "substrates": [{"partOfSpeech": "noun", "definition": "underlying layers or surfaces on which organisms grow or processes occur"}],
  "subsystems": [{"partOfSpeech": "noun", "definition": "self-contained components that function as parts of a larger integrated whole"}],
  "subtracted": [{"partOfSpeech": "verb", "definition": "took away a number or amount from another; removed a part from a total"}],
  "subversion": [{"partOfSpeech": "noun", "definition": "the undermining of the power and authority of an established institution or order"}],
  "succeeding": [{"partOfSpeech": "verb", "definition": "achieving a desired aim; coming after and taking the place of another"}],
  "successful": [{"partOfSpeech": "adjective", "definition": "having achieved a desired aim, fame, or prosperity"}],
  "succession": [{"partOfSpeech": "noun", "definition": "a number of things following one after the other in order; inheriting a title or position"}],
  "successive": [{"partOfSpeech": "adjective", "definition": "following one another without interruption; consecutive"}],
  "successors": [{"partOfSpeech": "noun", "definition": "people or things that come after and take the place of predecessors"}],
  "sufficient": [{"partOfSpeech": "adjective", "definition": "enough to meet the needs or requirements of a situation; adequate"}],
  "suggesting": [{"partOfSpeech": "verb", "definition": "putting forward an idea or proposal for consideration; implying or hinting at"}],
  "suggestion": [{"partOfSpeech": "noun", "definition": "an idea or proposal put forward for consideration; a slight indication or hint"}],
  "suggestive": [{"partOfSpeech": "adjective", "definition": "tending to imply or hint at something; evocative of a particular idea or association"}],
  "summarised": [{"partOfSpeech": "verb", "definition": "gave a brief account of the main points of something (British spelling)"}],
  "summarized": [{"partOfSpeech": "verb", "definition": "gave a brief account of the main points of something"}],
  "summarizes": [{"partOfSpeech": "verb", "definition": "gives a brief account of the main points of something"}],
  "summertime": [{"partOfSpeech": "noun", "definition": "the warmest period of the year, between late spring and early autumn"}],
  "sunglasses": [{"partOfSpeech": "noun", "definition": "tinted eyewear worn to protect the eyes from bright light and ultraviolet rays"}],
  "superpower": [{"partOfSpeech": "noun", "definition": "a nation with dominant global influence; an extraordinary or superhuman ability"}],
  "superseded": [{"partOfSpeech": "verb", "definition": "replaced by something newer, better, or more effective; made obsolete"}],
  "supersonic": [{"partOfSpeech": "adjective", "definition": "faster than the propagation of audible waves through air; exceeding Mach 1"}],
  "supervised": [{"partOfSpeech": "verb", "definition": "watched over and directed the performance or operation of a person or activity"}],
  "supervisor": [{"partOfSpeech": "noun", "definition": "a person who oversees and directs the work or activities of others"}],
  "supplement": [{"partOfSpeech": "noun", "definition": "something added to complete or enhance the whole; an additional dietary product"}],
  "supporters": [{"partOfSpeech": "noun", "definition": "people who advocate for or give assistance to a person, cause, or team"}],
  "supporting": [{"partOfSpeech": "verb", "definition": "giving assistance, encouragement, or financial aid; bearing weight or holding up"}],
  "supportive": [{"partOfSpeech": "adjective", "definition": "providing encouragement, emotional help, or practical assistance"}],
  "supposedly": [{"partOfSpeech": "adverb", "definition": "according to what is generally believed or claimed, but not necessarily confirmed"}],
  "suppressed": [{"partOfSpeech": "verb", "definition": "forcibly put an end to; restrained or held back from expression or publication"}],
  "suppressor": [{"partOfSpeech": "noun", "definition": "a device or agent that restrains, reduces, or eliminates something, such as noise or a signal"}],
  "surprising": [{"partOfSpeech": "adjective", "definition": "causing astonishment or wonder; unexpected and remarkable"}],
  "surrounded": [{"partOfSpeech": "verb", "definition": "enclosed on all sides; encircled by people or things"}],
  "suspension": [{"partOfSpeech": "noun", "definition": "a temporary removal from duty or privilege; a mechanism absorbing road shocks in a vehicle"}],
  "suspicions": [{"partOfSpeech": "noun", "definition": "feelings of doubt or mistrust about someone's intentions or the truth of something"}],
  "suspicious": [{"partOfSpeech": "adjective", "definition": "arousing distrust or doubt; feeling that something is wrong or dishonest"}],
  "sustaining": [{"partOfSpeech": "verb", "definition": "maintaining or keeping something going over a period of time; providing nourishment"}],
  "swallowing": [{"partOfSpeech": "verb", "definition": "causing food or drink to pass from the mouth down the throat into the stomach"}],
  "sweatshirt": [{"partOfSpeech": "noun", "definition": "a loose, warm garment made of cotton jersey, typically worn for casual or athletic activity"}],
  "sweetheart": [{"partOfSpeech": "noun", "definition": "a person who is very dear to another; a romantic partner or beloved companion"}],
  "sweetwater": [{"partOfSpeech": "noun", "definition": "fresh, non-saline water from a natural inland source such as a river or spring"}],
  "symphonies": [{"partOfSpeech": "noun", "definition": "elaborate musical compositions for a full orchestra, typically in multiple movements"}],
  "syndicated": [{"partOfSpeech": "adjective", "definition": "distributed or published through multiple outlets simultaneously by an agency or network"}],
  "synonymous": [{"partOfSpeech": "adjective", "definition": "having the same or nearly the same meaning; closely associated or identified with"}],
  "systematic": [{"partOfSpeech": "adjective", "definition": "done or acting according to a fixed plan or method; organized and methodical"}],
  "tablespoon": [{"partOfSpeech": "noun", "definition": "a large spoon used for serving; a unit of culinary measurement equal to about 15 milliliters"}],
  "tapestries": [{"partOfSpeech": "noun", "definition": "heavy fabric wall hangings with woven pictorial designs, often depicting historical scenes"}],
  "technician": [{"partOfSpeech": "noun", "definition": "a skilled worker who maintains, repairs, or operates equipment in a specialized field"}],
  "techniques": [{"partOfSpeech": "noun", "definition": "particular methods or ways of carrying out a task, especially involving practical skills"}],
  "technology": [{"partOfSpeech": "noun", "definition": "the application of scientific knowledge for practical purposes, especially in industry and computing"}],
  "telephones": [{"partOfSpeech": "noun", "definition": "devices for transmitting voice conversations over distances using electrical or wireless signals"}],
  "telescopes": [{"partOfSpeech": "noun", "definition": "optical instruments designed to magnify distant objects for closer observation"}],
  "television": [{"partOfSpeech": "noun", "definition": "an electronic device for receiving and displaying broadcast visual and audio programs"}],
  "temptation": [{"partOfSpeech": "noun", "definition": "the desire to do something unwise or wrong; something alluring that entices"}],
  "tendencies": [{"partOfSpeech": "noun", "definition": "inclinations or dispositions toward particular behaviors, actions, or patterns"}],
  "tenderness": [{"partOfSpeech": "noun", "definition": "the quality of being gentle, caring, and affectionate; sensitivity to pain when touched"}],
  "terminated": [{"partOfSpeech": "verb", "definition": "brought to an end; ceased operation; dismissed from employment"}],
  "terminates": [{"partOfSpeech": "verb", "definition": "brings to an end; ceases operation; concludes at a final point"}],
  "terminator": [{"partOfSpeech": "noun", "definition": "a person or thing that brings something to an end; a boundary between illuminated and dark regions"}],
  "terrifying": [{"partOfSpeech": "adjective", "definition": "causing extreme fear or dread; deeply frightening"}],
  "terrorists": [{"partOfSpeech": "noun", "definition": "individuals who use unlawful violence and intimidation against civilians for political aims"}],
  "thankfully": [{"partOfSpeech": "adverb", "definition": "in a grateful manner; fortunately or luckily"}],
  "theatrical": [{"partOfSpeech": "adjective", "definition": "relating to acting or the stage; exaggerated and dramatic in manner"}],
  "themselves": [{"partOfSpeech": "pronoun", "definition": "reflexive form referring back to the people or things previously mentioned as the subject"}],
  "therapists": [{"partOfSpeech": "noun", "definition": "trained professionals who treat mental, emotional, or physical conditions through non-surgical methods"}],
  "thereafter": [{"partOfSpeech": "adverb", "definition": "after that time or event; from that point onward"}],
  "thermostat": [{"partOfSpeech": "noun", "definition": "a device that automatically regulates temperature by switching heating or cooling on and off"}],
  "thirteenth": [{"partOfSpeech": "adjective", "definition": "coming after the twelfth in position or order; the ordinal form of thirteen"}],
  "thoroughly": [{"partOfSpeech": "adverb", "definition": "in a complete and careful manner; to the fullest extent"}],
  "thoughtful": [{"partOfSpeech": "adjective", "definition": "showing careful consideration or attention; kind and considerate of others"}],
  "threatened": [{"partOfSpeech": "verb", "definition": "expressed an intention to cause harm or danger; was at risk of becoming endangered"}],
  "threesomes": [{"partOfSpeech": "noun", "definition": "groups of three people engaged in an activity together"}],
  "thresholds": [{"partOfSpeech": "noun", "definition": "levels or points at which something begins or changes; strips of wood or stone at the bottom of doorways"}],
  "thrombosis": [{"partOfSpeech": "noun", "definition": "the formation of a blood clot inside a vessel, obstructing the flow of circulation"}],
  "throughout": [{"partOfSpeech": "preposition", "definition": "in every part of; during the whole time of; from beginning to end"}],
  "throughput": [{"partOfSpeech": "noun", "definition": "the amount of material or data processed or passing through a point in a given time period"}],
  "thumbnails": [{"partOfSpeech": "noun", "definition": "small reduced-size versions of images used as previews or quick references"}],
  "tightening": [{"partOfSpeech": "verb", "definition": "making or becoming firmer, more secure, or more restrictive"}],
  "timeliness": [{"partOfSpeech": "noun", "definition": "the quality of happening or being done at a suitable or opportune moment"}],
  "timeshares": [{"partOfSpeech": "noun", "definition": "vacation properties jointly owned by multiple parties who each use them for allotted periods"}],
  "timetables": [{"partOfSpeech": "noun", "definition": "charts or lists showing the planned times of departures, classes, or events"}],
  "toiletries": [{"partOfSpeech": "noun", "definition": "personal care items used for washing, grooming, and hygiene, such as soap and toothpaste"}],
  "tolerances": [{"partOfSpeech": "noun", "definition": "permitted amounts of variation in measurements; abilities to endure hardship or difference"}],
  "toothbrush": [{"partOfSpeech": "noun", "definition": "a small brush with a long handle used for cleaning one's teeth"}],
  "toothpaste": [{"partOfSpeech": "noun", "definition": "a paste or gel applied to a brush for cleaning and maintaining dental health"}],
  "touchdowns": [{"partOfSpeech": "noun", "definition": "scoring plays in American football worth six points; moments when an aircraft lands"}],
  "touchstone": [{"partOfSpeech": "noun", "definition": "a standard or criterion by which something is judged or recognized"}],
  "tournament": [{"partOfSpeech": "noun", "definition": "a series of competitive matches or games leading to a final winner"}],
  "townhouses": [{"partOfSpeech": "noun", "definition": "multi-story residential dwellings that share side walls with adjacent units"}],
  "trademarks": [{"partOfSpeech": "noun", "definition": "legally registered symbols, names, or phrases identifying a product or company"}],
  "traditions": [{"partOfSpeech": "noun", "definition": "customs or beliefs passed down through generations within a community or society"}],
  "trajectory": [{"partOfSpeech": "noun", "definition": "the curved path followed by a projectile in motion; the course of development over time"}],
  "trampoline": [{"partOfSpeech": "noun", "definition": "a strong fabric sheet connected by springs to a frame, used for bouncing and acrobatics"}],
  "transcript": [{"partOfSpeech": "noun", "definition": "a written or printed version of spoken material; an official academic record of courses and grades"}],
  "transforms": [{"partOfSpeech": "verb", "definition": "changes completely in form, appearance, or character; converts from one state to another"}],
  "transition": [{"partOfSpeech": "noun", "definition": "the process of changing from one state, condition, or phase to another"}],
  "translated": [{"partOfSpeech": "verb", "definition": "expressed the meaning of words or text in a different language"}],
  "translates": [{"partOfSpeech": "verb", "definition": "expresses the meaning of words or text in a different language"}],
  "translator": [{"partOfSpeech": "noun", "definition": "a person or program that converts text or speech from one language to another"}],
  "transplant": [{"partOfSpeech": "noun", "definition": "a surgical operation in which an organ or tissue is moved from one body or location to another"}],
  "transports": [{"partOfSpeech": "verb", "definition": "carries or conveys people or goods from one place to another"}],
  "transverse": [{"partOfSpeech": "adjective", "definition": "situated or extending across something; at right angles to the long axis"}],
  "travellers": [{"partOfSpeech": "noun", "definition": "people who are journeying, especially over long distances (British spelling)"}],
  "travelling": [{"partOfSpeech": "verb", "definition": "making a journey, typically over a considerable distance (British spelling)"}],
  "treadmills": [{"partOfSpeech": "noun", "definition": "exercise machines with a moving belt on which one walks or runs in place"}],
  "treatments": [{"partOfSpeech": "noun", "definition": "medical care given to a patient; ways of dealing with or handling something"}],
  "tremendous": [{"partOfSpeech": "adjective", "definition": "very great in amount, scale, or intensity; extraordinarily impressive"}],
  "triangular": [{"partOfSpeech": "adjective", "definition": "shaped like a figure with three sides and three angles"}],
  "triggering": [{"partOfSpeech": "verb", "definition": "causing a device to activate or an event to happen; setting off a reaction"}],
  "triumphant": [{"partOfSpeech": "adjective", "definition": "having won a battle or contest; feeling victorious and jubilant"}],
  "turbulence": [{"partOfSpeech": "noun", "definition": "violent or unsteady movement of air or water; a state of conflict or confusion"}],
  "turnaround": [{"partOfSpeech": "noun", "definition": "a reversal in direction or fortunes; the time needed to complete a process"}],
  "turntables": [{"partOfSpeech": "noun", "definition": "circular revolving platforms, especially those used for playing vinyl records"}],
  "typewriter": [{"partOfSpeech": "noun", "definition": "a mechanical device with keys that print individual characters onto paper through an inked ribbon"}],
  "ubiquitous": [{"partOfSpeech": "adjective", "definition": "present, appearing, or found everywhere; extremely widespread"}],
  "ultimately": [{"partOfSpeech": "adverb", "definition": "in the end; finally; at the most fundamental level"}],
  "unabridged": [{"partOfSpeech": "adjective", "definition": "not cut short or condensed; complete and full-length"}],
  "unaffected": [{"partOfSpeech": "adjective", "definition": "not changed or influenced by something; natural and genuine in manner"}],
  "unanswered": [{"partOfSpeech": "adjective", "definition": "not having received a reply or response; remaining without resolution"}],
  "unassigned": [{"partOfSpeech": "adjective", "definition": "not allocated or given to a particular person, task, or purpose"}],
  "unattached": [{"partOfSpeech": "adjective", "definition": "not connected or joined to anything; not in a romantic relationship"}],
  "unattended": [{"partOfSpeech": "adjective", "definition": "not watched over or looked after; left without supervision"}],
  "unbalanced": [{"partOfSpeech": "adjective", "definition": "not evenly distributed; lacking equilibrium or mental stability"}],
  "unbeatable": [{"partOfSpeech": "adjective", "definition": "impossible to surpass or defeat; exceptionally excellent"}],
  "uncensored": [{"partOfSpeech": "adjective", "definition": "not having had objectionable content removed; presented without editorial restriction"}],
  "undeclared": [{"partOfSpeech": "adjective", "definition": "not officially announced or acknowledged; not stated for tax or customs purposes"}],
  "undercover": [{"partOfSpeech": "adjective", "definition": "involving secret work to obtain information, especially by law enforcement agents in disguise"}],
  "undergoing": [{"partOfSpeech": "verb", "definition": "experiencing or being subjected to a process, change, or treatment"}],
  "underlined": [{"partOfSpeech": "verb", "definition": "drew a line beneath text for emphasis; highlighted the importance of something"}],
  "underlying": [{"partOfSpeech": "adjective", "definition": "existing beneath the surface; fundamental and forming the basis of something"}],
  "undermined": [{"partOfSpeech": "verb", "definition": "gradually weakened or eroded the foundation, confidence, or authority of something"}],
  "underneath": [{"partOfSpeech": "preposition", "definition": "directly below or beneath; on a lower level or layer than"}],
  "underscore": [{"partOfSpeech": "verb", "definition": "emphasize the importance of something; draw a line beneath text"}],
  "understand": [{"partOfSpeech": "verb", "definition": "perceive the intended meaning of words or a speaker; grasp the significance of something"}],
  "understood": [{"partOfSpeech": "verb", "definition": "perceived the intended meaning of; grasped the nature or significance of something"}],
  "undertaken": [{"partOfSpeech": "verb", "definition": "committed oneself to and begun a task, project, or responsibility"}],
  "undertakes": [{"partOfSpeech": "verb", "definition": "commits to and begins carrying out a task, project, or responsibility"}],
  "underwater": [{"partOfSpeech": "adjective", "definition": "situated, occurring, or used beneath the surface of a body of water"}],
  "underworld": [{"partOfSpeech": "noun", "definition": "the realm of the dead in mythology; the criminal element of society"}],
  "undisputed": [{"partOfSpeech": "adjective", "definition": "not challenged or questioned; universally accepted as true or valid"}],
  "undressing": [{"partOfSpeech": "verb", "definition": "removing clothing from oneself or another person"}],
  "unemployed": [{"partOfSpeech": "adjective", "definition": "without a paid job but available and seeking work"}],
  "unexpected": [{"partOfSpeech": "adjective", "definition": "not anticipated or foreseen; coming as a shock or revelation"}],
  "unfamiliar": [{"partOfSpeech": "adjective", "definition": "not known or recognized; strange or foreign to one's experience"}],
  "unfinished": [{"partOfSpeech": "adjective", "definition": "not brought to completion; lacking the final processing or polish"}],
  "unforeseen": [{"partOfSpeech": "adjective", "definition": "not anticipated or predicted; happening without prior warning"}],
  "uniformity": [{"partOfSpeech": "noun", "definition": "the quality of being the same in all cases; overall sameness or consistency"}],
  "unilateral": [{"partOfSpeech": "adjective", "definition": "performed by or affecting only one side, party, or group without agreement from others"}],
  "unintended": [{"partOfSpeech": "adjective", "definition": "not planned or meant; happening as an accidental byproduct"}],
  "uniqueness": [{"partOfSpeech": "noun", "definition": "the quality of being one of a kind; the state of having no equal or equivalent"}],
  "university": [{"partOfSpeech": "noun", "definition": "a higher education institution offering undergraduate and graduate degrees across many disciplines"}],
  "unlicensed": [{"partOfSpeech": "adjective", "definition": "not having official permission or certification to operate or practice"}],
  "unofficial": [{"partOfSpeech": "adjective", "definition": "not formally authorized or confirmed by the relevant authority"}],
  "unpleasant": [{"partOfSpeech": "adjective", "definition": "causing discomfort, unhappiness, or revulsion; disagreeable"}],
  "unreleased": [{"partOfSpeech": "adjective", "definition": "not yet made available to the public; still held back from distribution"}],
  "unreliable": [{"partOfSpeech": "adjective", "definition": "not able to be trusted or depended on; inconsistent in performance"}],
  "unresolved": [{"partOfSpeech": "adjective", "definition": "not yet settled, answered, or brought to a conclusion"}],
  "unsuitable": [{"partOfSpeech": "adjective", "definition": "not fitting or appropriate for a particular purpose or occasion"}],
  "usefulness": [{"partOfSpeech": "noun", "definition": "the quality of being practical, helpful, or able to serve a beneficial purpose"}],
  "valentines": [{"partOfSpeech": "noun", "definition": "cards or gifts exchanged on February 14th to express romantic affection"}],
  "validating": [{"partOfSpeech": "verb", "definition": "checking or proving the accuracy, soundness, or legitimacy of something"}],
  "validation": [{"partOfSpeech": "noun", "definition": "the act of confirming accuracy, legitimacy, or compliance with a standard"}],
  "valuations": [{"partOfSpeech": "noun", "definition": "assessments of monetary worth or estimated financial value of something"}],
  "variations": [{"partOfSpeech": "noun", "definition": "changes or slight differences in condition, amount, or level from a standard"}],
  "vegetables": [{"partOfSpeech": "noun", "definition": "edible plants or parts of plants used as food, such as carrots, broccoli, or spinach"}],
  "vegetation": [{"partOfSpeech": "noun", "definition": "plants collectively, especially those found growing in a particular area or habitat"}],
  "vegetative": [{"partOfSpeech": "adjective", "definition": "relating to plant growth; in medicine, describing a state of minimal brain function"}],
  "velocities": [{"partOfSpeech": "noun", "definition": "the speeds of objects in given directions; rates of change of position over time"}],
  "ventilated": [{"partOfSpeech": "adjective", "definition": "provided with fresh air circulation through an enclosed space"}],
  "versailles": [{"partOfSpeech": "noun", "definition": "a French city known for its opulent royal palace and historically significant treaty"}],
  "vertically": [{"partOfSpeech": "adverb", "definition": "in an upright direction; perpendicular to the horizon; from top to bottom"}],
  "vibrations": [{"partOfSpeech": "noun", "definition": "rapid back-and-forth oscillating movements; resonating tremors or trembling motions"}],
  "victorious": [{"partOfSpeech": "adjective", "definition": "having won a fight, contest, or war; triumphant and celebrating a win"}],
  "viewfinder": [{"partOfSpeech": "noun", "definition": "a small window on a camera through which the photographer looks to frame a shot"}],
  "viewpoints": [{"partOfSpeech": "noun", "definition": "particular attitudes, perspectives, or ways of considering a matter"}],
  "vigorously": [{"partOfSpeech": "adverb", "definition": "with great physical energy and force; in a strong and active manner"}],
  "violations": [{"partOfSpeech": "noun", "definition": "acts of breaking or failing to comply with a rule, law, or agreement"}],
  "visitation": [{"partOfSpeech": "noun", "definition": "an official or formal visit, especially for inspection; the right to visit one's children"}],
  "vocabulary": [{"partOfSpeech": "noun", "definition": "the body of words known and used by a person or within a particular language"}],
  "vocational": [{"partOfSpeech": "adjective", "definition": "relating to education or training directed at a particular occupation or trade"}],
  "volleyball": [{"partOfSpeech": "noun", "definition": "a team sport in which players hit a ball over a high net, aiming to ground it on the opponent's side"}],
  "volunteers": [{"partOfSpeech": "noun", "definition": "people who freely offer to do something without being paid or compelled"}],
  "vulnerable": [{"partOfSpeech": "adjective", "definition": "susceptible to physical or emotional harm; open to attack or damage"}],
  "wallpapers": [{"partOfSpeech": "noun", "definition": "decorative coverings applied to interior walls; background images on computer or phone displays"}],
  "warehouses": [{"partOfSpeech": "noun", "definition": "large buildings used for storing goods, merchandise, or raw materials"}],
  "warranties": [{"partOfSpeech": "noun", "definition": "written guarantees promising to repair or replace a product if it fails within a specified period"}],
  "wastewater": [{"partOfSpeech": "noun", "definition": "used or contaminated water from households, industry, or agriculture that requires treatment"}],
  "watercolor": [{"partOfSpeech": "noun", "definition": "a painting method using pigments dissolved in a water-based medium; artwork created this way"}],
  "waterfalls": [{"partOfSpeech": "noun", "definition": "cascades where a river or stream flows over a vertical drop or cliff edge"}],
  "waterfront": [{"partOfSpeech": "noun", "definition": "the area of a town or city alongside a body of water, such as a harbor or river"}],
  "watermelon": [{"partOfSpeech": "noun", "definition": "a large green-skinned fruit with sweet, juicy red or pink flesh and black seeds"}],
  "waterproof": [{"partOfSpeech": "adjective", "definition": "impervious to moisture; able to resist penetration by liquid"}],
  "watersheds": [{"partOfSpeech": "noun", "definition": "areas of land that drain into a common body of water; turning points or critical dividing lines"}],
  "wavelength": [{"partOfSpeech": "noun", "definition": "the distance between successive crests of a wave; a person's way of thinking or communicating"}],
  "weaknesses": [{"partOfSpeech": "noun", "definition": "qualities or features that are inadequate or flawed; areas of vulnerability"}],
  "wednesdays": [{"partOfSpeech": "noun", "definition": "the days of the week falling between Tuesday and Thursday"}],
  "whatsoever": [{"partOfSpeech": "adverb", "definition": "at all; used for emphasis after a negative statement to mean of any kind"}],
  "wheelchair": [{"partOfSpeech": "noun", "definition": "a chair mounted on wheels for people who cannot walk, propelled manually or by motor"}],
  "whispering": [{"partOfSpeech": "verb", "definition": "speaking very softly using one's breath rather than full vocal cords"}],
  "whitespace": [{"partOfSpeech": "noun", "definition": "blank areas on a page or in code, including spaces, tabs, and line breaks"}],
  "wholesaler": [{"partOfSpeech": "noun", "definition": "a merchant who sells goods in bulk to retailers rather than directly to consumers"}],
  "widespread": [{"partOfSpeech": "adjective", "definition": "found or distributed over a large area or among many people; prevalent"}],
  "wilderness": [{"partOfSpeech": "noun", "definition": "an uncultivated, uninhabited, and wild natural region left in its original condition"}],
  "windscreen": [{"partOfSpeech": "noun", "definition": "the front glass panel of a vehicle that protects occupants from wind and debris (British term)"}],
  "windshield": [{"partOfSpeech": "noun", "definition": "the front glass panel of a vehicle that protects occupants from wind and debris (American term)"}],
  "witchcraft": [{"partOfSpeech": "noun", "definition": "the practice of magic, especially involving spells, incantations, and alleged supernatural powers"}],
  "withdrawal": [{"partOfSpeech": "noun", "definition": "the act of removing or taking back; ceasing participation; symptoms from stopping a habit"}],
  "witnessing": [{"partOfSpeech": "verb", "definition": "seeing an event take place firsthand; being present as an observer during an occurrence"}],
  "wolverines": [{"partOfSpeech": "noun", "definition": "stocky, powerful carnivorous mammals of the weasel family found in northern forests and tundra"}],
  "wonderland": [{"partOfSpeech": "noun", "definition": "an imaginary or real place full of marvelous and enchanting things"}],
  "woodpecker": [{"partOfSpeech": "noun", "definition": "a bird with a strong bill that drums on tree trunks to find insects and excavate nesting holes"}],
  "worksheets": [{"partOfSpeech": "noun", "definition": "printed pages of exercises or problems for students; individual pages within a spreadsheet"}],
  "worthwhile": [{"partOfSpeech": "adjective", "definition": "sufficiently valuable or important to justify the time, effort, or money spent"}],
  "wristbands": [{"partOfSpeech": "noun", "definition": "bands worn around the wrist for identification, fashion, or to absorb perspiration"}],
  "youngsters": [{"partOfSpeech": "noun", "definition": "children, young people, or adolescents"}],
  "yourselves": [{"partOfSpeech": "pronoun", "definition": "reflexive form of 'you' when addressing multiple people as both subject and object"}],
  "zoological": [{"partOfSpeech": "adjective", "definition": "relating to the scientific study of animals and their behavior, habitats, and classification"}]
};
const merged = { ...existing, ...newDefs };
const answers = JSON.parse(readFileSync("./data/words-answer.json", "utf-8"));
const covered = answers.filter(w => new Set(Object.keys(merged)).has(w));
console.log(`Coverage: ${covered.length}/${answers.length}`);
writeFileSync("./data/word-definitions.json", JSON.stringify(merged, null, 2) + "\n");
