import { readFileSync, writeFileSync } from "fs";
const existing = JSON.parse(readFileSync("./data/word-definitions.json", "utf-8"));
const newDefs = {
"decorating": [{"partOfSpeech": "verb", "definition": "Adding ornaments or paint to make something look more attractive."}],
"decoration": [{"partOfSpeech": "noun", "definition": "An ornament or embellishment added to make something more attractive."}],
"decorative": [{"partOfSpeech": "adjective", "definition": "Serving to make something look more attractive rather than functional."}],
"decorators": [{"partOfSpeech": "noun", "definition": "People whose job is to paint and wallpaper the interior of buildings."}],
"decreasing": [{"partOfSpeech": "verb", "definition": "Becoming smaller or fewer in size, amount, or number."}],
"dedication": [{"partOfSpeech": "noun", "definition": "Devotion to a task or cause, or a message inscribing a work to someone."}],
"deductible": [{"partOfSpeech": "adjective", "definition": "Able to be subtracted, especially from taxable income or an insurance claim."}],
"deductions": [{"partOfSpeech": "noun", "definition": "Amounts subtracted from a total, or conclusions reached by reasoning."}],
"defamation": [{"partOfSpeech": "noun", "definition": "The action of damaging someone's reputation through false statements."}],
"defendants": [{"partOfSpeech": "noun", "definition": "People accused or sued in a court of law."}],
"deficiency": [{"partOfSpeech": "noun", "definition": "A lack or shortage of something needed; an inadequacy."}],
"definitely": [{"partOfSpeech": "adverb", "definition": "Without any doubt; in a clear and certain manner."}],
"definition": [{"partOfSpeech": "noun", "definition": "A statement of the exact meaning of a word or phrase."}],
"definitive": [{"partOfSpeech": "adjective", "definition": "Decisive and with authority; the most authoritative of its kind."}],
"deflection": [{"partOfSpeech": "noun", "definition": "The action of turning something aside from a straight course."}],
"delegation": [{"partOfSpeech": "noun", "definition": "A group of representatives, or the act of entrusting a task to another."}],
"delinquent": [{"partOfSpeech": "adjective", "definition": "Failing to fulfil an obligation, or tending to commit minor crimes."}],
"deliveries": [{"partOfSpeech": "noun", "definition": "Acts of bringing goods or mail to a destination."}],
"delivering": [{"partOfSpeech": "verb", "definition": "Bringing goods or letters to the intended recipient."}],
"demolished": [{"partOfSpeech": "verb", "definition": "Pulled down or destroyed a building or structure completely."}],
"demolition": [{"partOfSpeech": "noun", "definition": "The act of pulling down or destroying buildings or structures."}],
"department": [{"partOfSpeech": "noun", "definition": "A division of a larger organization dealing with a specific area."}],
"departures": [{"partOfSpeech": "noun", "definition": "Acts of leaving a place, especially to start a journey."}],
"dependable": [{"partOfSpeech": "adjective", "definition": "Trustworthy and reliable; able to be counted on."}],
"dependence": [{"partOfSpeech": "noun", "definition": "The state of relying on someone or something for support."}],
"dependents": [{"partOfSpeech": "noun", "definition": "People who rely on another for financial support, especially children."}],
"deployment": [{"partOfSpeech": "noun", "definition": "The movement of troops or resources into position for action."}],
"deposition": [{"partOfSpeech": "noun", "definition": "Sworn testimony given outside court, or the removal from power."}],
"depository": [{"partOfSpeech": "noun", "definition": "A place where things are stored for safekeeping."}],
"deprecated": [{"partOfSpeech": "adjective", "definition": "No longer recommended for use; outdated and likely to be removed."}],
"depressing": [{"partOfSpeech": "adjective", "definition": "Causing feelings of severe gloom or sadness."}],
"depression": [{"partOfSpeech": "noun", "definition": "A mental condition marked by persistent sadness, or an economic downturn."}],
"depressive": [{"partOfSpeech": "adjective", "definition": "Tending to cause feelings of hopelessness and low mood."}],
"derivation": [{"partOfSpeech": "noun", "definition": "The origin or source of something, especially a word."}],
"derivative": [{"partOfSpeech": "adjective", "definition": "Imitative of another's work; not original."}],
"dermatitis": [{"partOfSpeech": "noun", "definition": "Inflammation of the skin causing itchiness, redness, and swelling."}],
"descendant": [{"partOfSpeech": "noun", "definition": "A person born from a particular ancestor; offspring."}],
"descending": [{"partOfSpeech": "verb", "definition": "Moving downward; going from higher to lower."}],
"describing": [{"partOfSpeech": "verb", "definition": "Giving a spoken or written account of the appearance or nature of something."}],
"designated": [{"partOfSpeech": "verb", "definition": "Appointed or officially assigned to a particular position or purpose."}],
"designates": [{"partOfSpeech": "verb", "definition": "Officially assigns a particular status or role to something."}],
"despatched": [{"partOfSpeech": "verb", "definition": "Sent off to a destination or for a purpose (British variant)."}],
"destroying": [{"partOfSpeech": "verb", "definition": "Putting an end to the existence of something by damaging it beyond repair."}],
"detachable": [{"partOfSpeech": "adjective", "definition": "Able to be unfastened and removed from something."}],
"detachment": [{"partOfSpeech": "noun", "definition": "The state of being separate, or emotional objectivity and distance."}],
"detectable": [{"partOfSpeech": "adjective", "definition": "Able to be discovered or noticed."}],
"detectives": [{"partOfSpeech": "noun", "definition": "People whose job is to investigate crimes and gather evidence."}],
"determined": [{"partOfSpeech": "adjective", "definition": "Having made a firm decision and showing resolve not to change it."}],
"determines": [{"partOfSpeech": "verb", "definition": "Causes something to occur in a particular way; establishes something."}],
"devastated": [{"partOfSpeech": "adjective", "definition": "Severely damaged or destroyed; overwhelmed with shock or grief."}],
"developers": [{"partOfSpeech": "noun", "definition": "People who create software or build on land for commercial purposes."}],
"developing": [{"partOfSpeech": "verb", "definition": "Growing or becoming more advanced over time."}],
"deviations": [{"partOfSpeech": "noun", "definition": "Departures from an established course, standard, or norm."}],
"devotional": [{"partOfSpeech": "adjective", "definition": "Relating to religious worship or pious observance."}],
"diagnosing": [{"partOfSpeech": "verb", "definition": "Identifying the nature of an illness or problem by examining symptoms."}],
"dictionary": [{"partOfSpeech": "noun", "definition": "A book listing words with their meanings, typically in alphabetical order."}],
"difference": [{"partOfSpeech": "noun", "definition": "A way in which things are not the same."}],
"diligently": [{"partOfSpeech": "adverb", "definition": "In a way that shows careful and persistent effort."}],
"dimensions": [{"partOfSpeech": "noun", "definition": "Measurable extents such as length, width, and height."}],
"diminished": [{"partOfSpeech": "verb", "definition": "Made or became less in size, importance, or value."}],
"dinnerware": [{"partOfSpeech": "noun", "definition": "Dishes, plates, and bowls used for serving and eating meals."}],
"directions": [{"partOfSpeech": "noun", "definition": "Instructions for reaching a place, or the courses along which things move."}],
"directives": [{"partOfSpeech": "noun", "definition": "Official instructions or orders issued by an authority."}],
"disability": [{"partOfSpeech": "noun", "definition": "A physical or mental condition that limits movement, senses, or activities."}],
"disappears": [{"partOfSpeech": "verb", "definition": "Ceases to be visible or to exist."}],
"disappoint": [{"partOfSpeech": "verb", "definition": "To fail to fulfil someone's hopes or expectations."}],
"disapprove": [{"partOfSpeech": "verb", "definition": "To have an unfavorable opinion of something; to regard as wrong."}],
"disastrous": [{"partOfSpeech": "adjective", "definition": "Causing great damage, harm, or suffering; catastrophic."}],
"discerning": [{"partOfSpeech": "adjective", "definition": "Having or showing good judgement and refined taste."}],
"discharged": [{"partOfSpeech": "verb", "definition": "Released from duty, hospital, or obligation."}],
"discharges": [{"partOfSpeech": "noun", "definition": "Acts of releasing or emitting something, such as fluid or a patient."}],
"discipline": [{"partOfSpeech": "noun", "definition": "The practice of training people to follow rules and maintain order."}],
"disclaimer": [{"partOfSpeech": "noun", "definition": "A statement denying responsibility or liability."}],
"disclosing": [{"partOfSpeech": "verb", "definition": "Making previously secret information known to others."}],
"disclosure": [{"partOfSpeech": "noun", "definition": "The act of making new or secret information known."}],
"discomfort": [{"partOfSpeech": "noun", "definition": "Slight pain or a feeling of unease and awkwardness."}],
"disconnect": [{"partOfSpeech": "verb", "definition": "To break the link or connection between things."}],
"discounted": [{"partOfSpeech": "adjective", "definition": "Reduced in price, or regarded as unreliable."}],
"discourage": [{"partOfSpeech": "verb", "definition": "To cause someone to lose confidence or enthusiasm."}],
"discourses": [{"partOfSpeech": "noun", "definition": "Written or spoken communications or debates on a topic."}],
"discovered": [{"partOfSpeech": "verb", "definition": "Found or learned something for the first time."}],
"discretion": [{"partOfSpeech": "noun", "definition": "The quality of being careful about what one says or does; personal judgement."}],
"discussing": [{"partOfSpeech": "verb", "definition": "Talking about something in detail to exchange ideas."}],
"discussion": [{"partOfSpeech": "noun", "definition": "A conversation or debate about a particular topic."}],
"disgusting": [{"partOfSpeech": "adjective", "definition": "Arousing strong feelings of revulsion; extremely unpleasant."}],
"dishonesty": [{"partOfSpeech": "noun", "definition": "Deceitfulness; a willingness to lie, cheat, or mislead."}],
"dishwasher": [{"partOfSpeech": "noun", "definition": "A machine for cleaning plates, glasses, and cutlery automatically."}],
"dispatched": [{"partOfSpeech": "verb", "definition": "Sent off to a destination or for a purpose."}],
"dispatches": [{"partOfSpeech": "noun", "definition": "Official reports or messages sent with speed."}],
"dispensers": [{"partOfSpeech": "noun", "definition": "Devices that release measured quantities of a product."}],
"dispensing": [{"partOfSpeech": "verb", "definition": "Distributing or providing a service or product to a number of people."}],
"dispersion": [{"partOfSpeech": "noun", "definition": "The process of spreading things or people over a wide area."}],
"displaying": [{"partOfSpeech": "verb", "definition": "Showing something publicly or making it visible."}],
"disposable": [{"partOfSpeech": "adjective", "definition": "Intended to be used once and then thrown away."}],
"disruption": [{"partOfSpeech": "noun", "definition": "A disturbance that interrupts the normal course of an activity."}],
"disruptive": [{"partOfSpeech": "adjective", "definition": "Causing or tending to cause a disturbance or interruption."}],
"dissection": [{"partOfSpeech": "noun", "definition": "The act of cutting something apart for detailed examination."}],
"dissenting": [{"partOfSpeech": "adjective", "definition": "Holding or expressing opinions that differ from the majority."}],
"distinctly": [{"partOfSpeech": "adverb", "definition": "In a way that is clearly perceptible; unmistakably."}],
"distortion": [{"partOfSpeech": "noun", "definition": "A change in the original shape, sound, or meaning of something."}],
"distracted": [{"partOfSpeech": "adjective", "definition": "Unable to concentrate because one's mind is elsewhere."}],
"distressed": [{"partOfSpeech": "adjective", "definition": "Suffering from anxiety, sorrow, or pain."}],
"distribute": [{"partOfSpeech": "verb", "definition": "To hand out or deliver something to a number of recipients."}],
"disturbing": [{"partOfSpeech": "adjective", "definition": "Causing anxiety, worry, or unease."}],
"divergence": [{"partOfSpeech": "noun", "definition": "The process of becoming different or moving apart."}],
"diversions": [{"partOfSpeech": "noun", "definition": "Alternative routes, or activities that distract attention."}],
"divination": [{"partOfSpeech": "noun", "definition": "The practice of seeking to foretell the future by supernatural means."}],
"divisional": [{"partOfSpeech": "adjective", "definition": "Relating to a section or unit within a larger organization."}],
"documented": [{"partOfSpeech": "verb", "definition": "Recorded in detail with written or other evidence."}],
"dominating": [{"partOfSpeech": "verb", "definition": "Having power and influence over others; being the most prominent."}],
"domination": [{"partOfSpeech": "noun", "definition": "The exercise of power or control over others."}],
"downloaded": [{"partOfSpeech": "verb", "definition": "Copied data from a remote server to a local device."}],
"downstairs": [{"partOfSpeech": "adverb", "definition": "On or to a lower floor of a building."}],
"drawstring": [{"partOfSpeech": "noun", "definition": "A cord threaded through fabric to tighten or close an opening."}],
"drowsiness": [{"partOfSpeech": "noun", "definition": "A state of being sleepy and lethargic."}],
"duplicated": [{"partOfSpeech": "verb", "definition": "Made an exact copy of something."}],
"duplicates": [{"partOfSpeech": "noun", "definition": "Exact copies of things that already exist."}],
"duplicator": [{"partOfSpeech": "noun", "definition": "A machine or device for making copies of documents."}],
"durability": [{"partOfSpeech": "noun", "definition": "The ability to withstand wear, pressure, or damage over time."}],
"ecological": [{"partOfSpeech": "adjective", "definition": "Relating to the relationships between organisms and their environment."}],
"economical": [{"partOfSpeech": "adjective", "definition": "Giving good value in relation to money spent; thrifty."}],
"economists": [{"partOfSpeech": "noun", "definition": "Experts in the study of wealth production and consumption."}],
"ecosystems": [{"partOfSpeech": "noun", "definition": "Biological communities of interacting organisms and their environments."}],
"ecumenical": [{"partOfSpeech": "adjective", "definition": "Promoting unity among different Christian churches or religions."}],
"editorials": [{"partOfSpeech": "noun", "definition": "Newspaper articles expressing the editor's opinion on a topic."}],
"efficiency": [{"partOfSpeech": "noun", "definition": "The ability to achieve maximum output with minimum wasted effort."}],
"effortless": [{"partOfSpeech": "adjective", "definition": "Requiring no physical or mental exertion; appearing easy."}],
"elaborated": [{"partOfSpeech": "verb", "definition": "Developed or explained in greater detail."}],
"electrical": [{"partOfSpeech": "adjective", "definition": "Relating to or powered by the flow of charged particles."}],
"electrodes": [{"partOfSpeech": "noun", "definition": "Conductors through which current enters or leaves a device."}],
"elementary": [{"partOfSpeech": "adjective", "definition": "Relating to the most basic level; fundamental and straightforward."}],
"elevations": [{"partOfSpeech": "noun", "definition": "Heights above a given level, especially sea level."}],
"eliminated": [{"partOfSpeech": "verb", "definition": "Completely removed or got rid of something."}],
"eliminates": [{"partOfSpeech": "verb", "definition": "Completely removes or gets rid of something."}],
"eliminator": [{"partOfSpeech": "noun", "definition": "A person or thing that removes or defeats others in a contest."}],
"elliptical": [{"partOfSpeech": "adjective", "definition": "Oval in shape; or using speech that omits words for brevity."}],
"elongation": [{"partOfSpeech": "noun", "definition": "The process of making something longer or being stretched out."}],
"embodiment": [{"partOfSpeech": "noun", "definition": "A tangible or visible form of an idea, quality, or feeling."}],
"emigration": [{"partOfSpeech": "noun", "definition": "The act of leaving one's own country to settle permanently elsewhere."}],
"emphasised": [{"partOfSpeech": "verb", "definition": "Gave special importance or prominence to something (British spelling)."}],
"emphasized": [{"partOfSpeech": "verb", "definition": "Gave special importance or prominence to something."}],
"emphasizes": [{"partOfSpeech": "verb", "definition": "Gives special importance or prominence to something."}],
"employment": [{"partOfSpeech": "noun", "definition": "The condition of having paid work; the act of giving work to someone."}],
"empowering": [{"partOfSpeech": "verb", "definition": "Giving someone the authority or confidence to do something."}],
"enchanting": [{"partOfSpeech": "adjective", "definition": "Delightfully charming or attractive; captivating."}],
"enclosures": [{"partOfSpeech": "noun", "definition": "Areas surrounded by a barrier, or documents included with a letter."}],
"encounters": [{"partOfSpeech": "noun", "definition": "Unexpected or casual meetings with someone or something."}],
"encouraged": [{"partOfSpeech": "verb", "definition": "Gave someone support, confidence, or hope."}],
"encourages": [{"partOfSpeech": "verb", "definition": "Gives someone support or confidence to do something."}],
"encryption": [{"partOfSpeech": "noun", "definition": "The process of converting data into coded form to prevent unauthorized access."}],
"endangered": [{"partOfSpeech": "adjective", "definition": "Seriously at risk of extinction or harm."}],
"endogenous": [{"partOfSpeech": "adjective", "definition": "Having an internal origin; growing from within an organism."}],
"endowments": [{"partOfSpeech": "noun", "definition": "Donations of money or property to an institution, or natural qualities."}],
"engagement": [{"partOfSpeech": "noun", "definition": "A formal agreement to marry, or active participation in something."}],
"engineered": [{"partOfSpeech": "verb", "definition": "Designed and built using scientific principles; skillfully arranged."}],
"enormously": [{"partOfSpeech": "adverb", "definition": "To a very great degree; immensely."}],
"enrichment": [{"partOfSpeech": "noun", "definition": "The act of improving the quality or value of something."}],
"enrollment": [{"partOfSpeech": "noun", "definition": "The act of registering or being registered for something."}],
"enterprise": [{"partOfSpeech": "noun", "definition": "A business or company, or boldness and initiative in undertaking projects."}],
"entrenched": [{"partOfSpeech": "adjective", "definition": "Firmly established and difficult to change."}],
"enumerated": [{"partOfSpeech": "verb", "definition": "Mentioned items one by one in a list."}],
"envisioned": [{"partOfSpeech": "verb", "definition": "Imagined or pictured something as a future possibility."}],
"epithelial": [{"partOfSpeech": "adjective", "definition": "Relating to the thin tissue covering body surfaces and lining organs."}],
"equatorial": [{"partOfSpeech": "adjective", "definition": "Relating to or near the imaginary line around Earth's middle."}],
"equilibria": [{"partOfSpeech": "noun", "definition": "States of balance between opposing forces or influences (plural)."}],
"equipments": [{"partOfSpeech": "noun", "definition": "Tools, machinery, and other items needed for a particular purpose."}],
"ergonomics": [{"partOfSpeech": "noun", "definition": "The study of designing equipment to fit the human body comfortably."}],
"escalating": [{"partOfSpeech": "verb", "definition": "Increasing rapidly in intensity, seriousness, or extent."}],
"escalation": [{"partOfSpeech": "noun", "definition": "A rapid increase in the intensity or seriousness of something."}],
"esophageal": [{"partOfSpeech": "adjective", "definition": "Relating to the tube connecting the throat to the stomach."}],
"especially": [{"partOfSpeech": "adverb", "definition": "Used to single out one thing over all others; particularly."}],
"essentials": [{"partOfSpeech": "noun", "definition": "Things that are absolutely necessary and indispensable."}],
"estimating": [{"partOfSpeech": "verb", "definition": "Roughly calculating the value, number, or extent of something."}],
"estimation": [{"partOfSpeech": "noun", "definition": "A rough calculation or judgement of the value of something."}],
"eucalyptus": [{"partOfSpeech": "noun", "definition": "A fast-growing Australian tree with aromatic leaves, widely planted in warm climates."}],
"evacuation": [{"partOfSpeech": "noun", "definition": "The act of removing people from a dangerous place to safety."}],
"evaluating": [{"partOfSpeech": "verb", "definition": "Forming a judgement about the amount, value, or quality of something."}],
"evaluation": [{"partOfSpeech": "noun", "definition": "The making of a judgement about the value or quality of something."}],
"evangelism": [{"partOfSpeech": "noun", "definition": "The spreading of a particular doctrine or set of beliefs to others."}],
"evangelist": [{"partOfSpeech": "noun", "definition": "A person who seeks to convert others to a faith or cause."}],
"eventually": [{"partOfSpeech": "adverb", "definition": "In the end; after a period of time or series of events."}],
"everything": [{"partOfSpeech": "pronoun", "definition": "All things; the totality of what exists or is relevant."}],
"everywhere": [{"partOfSpeech": "adverb", "definition": "In or to all places; in every part."}],
"excavation": [{"partOfSpeech": "noun", "definition": "The process of digging, especially to uncover buried remains."}],
"excellence": [{"partOfSpeech": "noun", "definition": "The quality of being outstanding or extremely good."}],
"excellency": [{"partOfSpeech": "noun", "definition": "A title of honor given to high officials such as ambassadors and governors."}],
"exceptions": [{"partOfSpeech": "noun", "definition": "Cases that do not follow the general rule."}],
"exchanging": [{"partOfSpeech": "verb", "definition": "Giving one thing and receiving another in return."}],
"excitation": [{"partOfSpeech": "noun", "definition": "The process of producing increased energy or activity in something."}],
"excitement": [{"partOfSpeech": "noun", "definition": "A feeling of great enthusiasm and eagerness."}],
"exclusions": [{"partOfSpeech": "noun", "definition": "Acts of shutting out or leaving out certain things or people."}],
"excursions": [{"partOfSpeech": "noun", "definition": "Short trips or journeys taken for pleasure."}],
"executable": [{"partOfSpeech": "adjective", "definition": "Able to be run as a program by a computer."}],
"executions": [{"partOfSpeech": "noun", "definition": "Acts of carrying out a plan or sentence, including capital punishment."}],
"executives": [{"partOfSpeech": "noun", "definition": "Senior managers responsible for running an organization."}],
"exemptions": [{"partOfSpeech": "noun", "definition": "Cases of being freed from an obligation or payment others must fulfill."}],
"exercising": [{"partOfSpeech": "verb", "definition": "Engaging in physical activity, or making use of a power or right."}],
"exhaustion": [{"partOfSpeech": "noun", "definition": "A state of extreme physical or mental tiredness."}],
"exhaustive": [{"partOfSpeech": "adjective", "definition": "Including or considering all elements; thorough and comprehensive."}],
"exhibiting": [{"partOfSpeech": "verb", "definition": "Publicly displaying works of art or items of interest."}],
"exhibition": [{"partOfSpeech": "noun", "definition": "A public display of works of art or items of interest."}],
"exhibitors": [{"partOfSpeech": "noun", "definition": "People or companies that display items at a public show."}],
"expandable": [{"partOfSpeech": "adjective", "definition": "Capable of being made larger or more extensive."}],
"expansions": [{"partOfSpeech": "noun", "definition": "Increases in size, scope, or extent."}],
"expectancy": [{"partOfSpeech": "noun", "definition": "The state of anticipating something, or the probable duration of something."}],
"expedition": [{"partOfSpeech": "noun", "definition": "A journey undertaken for a specific purpose, often exploration."}],
"experience": [{"partOfSpeech": "noun", "definition": "Practical contact with events, or knowledge gained through involvement."}],
"experiment": [{"partOfSpeech": "noun", "definition": "A scientific test carried out to prove or discover something."}],
"expiration": [{"partOfSpeech": "noun", "definition": "The end of a period of validity; the act of breathing out."}],
"explaining": [{"partOfSpeech": "verb", "definition": "Making something clear by describing it in more detail."}],
"explicitly": [{"partOfSpeech": "adverb", "definition": "In a clear and detailed manner, leaving no room for doubt."}],
"exploiting": [{"partOfSpeech": "verb", "definition": "Making full use of a resource, or unfairly using someone for benefit."}],
"explosions": [{"partOfSpeech": "noun", "definition": "Sudden, violent bursts of energy releasing gas and noise."}],
"explosives": [{"partOfSpeech": "noun", "definition": "Substances that can be made to blow up with destructive force."}],
"exposition": [{"partOfSpeech": "noun", "definition": "A comprehensive description or explanation of a subject."}],
"expressing": [{"partOfSpeech": "verb", "definition": "Conveying thoughts or feelings in words, looks, or actions."}],
"expressive": [{"partOfSpeech": "adjective", "definition": "Effectively conveying thought or feeling; full of meaning."}],
"expressway": [{"partOfSpeech": "noun", "definition": "A high-speed divided highway designed for fast travel."}],
"extensible": [{"partOfSpeech": "adjective", "definition": "Capable of being extended or expanded in functionality."}],
"extensions": [{"partOfSpeech": "noun", "definition": "Parts added to enlarge or prolong something."}],
"externally": [{"partOfSpeech": "adverb", "definition": "On or from the outside; relating to outer appearance."}],
"extinction": [{"partOfSpeech": "noun", "definition": "The state of a species having no living members; complete disappearance."}],
"extracting": [{"partOfSpeech": "verb", "definition": "Removing or pulling something out, often with effort."}],
"extraction": [{"partOfSpeech": "noun", "definition": "The process of removing something from a source."}],
"extremists": [{"partOfSpeech": "noun", "definition": "People who hold radical political or religious views."}],
"eyeglasses": [{"partOfSpeech": "noun", "definition": "A pair of lenses set in a frame worn to correct vision."}],
"eyewitness": [{"partOfSpeech": "noun", "definition": "A person who has seen something happen and can describe it."}],
"fabricated": [{"partOfSpeech": "verb", "definition": "Invented false information, or manufactured something."}],
"facilities": [{"partOfSpeech": "noun", "definition": "Places or equipment provided for a particular purpose."}],
"faithfully": [{"partOfSpeech": "adverb", "definition": "In a loyal and devoted manner; accurately and reliably."}],
"fascinated": [{"partOfSpeech": "adjective", "definition": "Intensely interested and attracted by something."}],
"fatalities": [{"partOfSpeech": "noun", "definition": "Deaths resulting from an accident, war, or disease."}],
"favourable": [{"partOfSpeech": "adjective", "definition": "Expressing approval or support; advantageous (British spelling)."}],
"federalism": [{"partOfSpeech": "noun", "definition": "A system of government in which power is divided between central and regional authorities."}],
"federalist": [{"partOfSpeech": "noun", "definition": "A supporter of a system dividing power between central and regional government."}],
"federation": [{"partOfSpeech": "noun", "definition": "A union of states or organizations under a central authority."}],
"fertilizer": [{"partOfSpeech": "noun", "definition": "A substance added to soil to promote plant growth."}],
"fictitious": [{"partOfSpeech": "adjective", "definition": "Not real; existing only in the imagination or as an invention."}],
"figurative": [{"partOfSpeech": "adjective", "definition": "Using words in a non-literal sense to create imagery or effect."}],
"filibuster": [{"partOfSpeech": "noun", "definition": "A prolonged speech used to delay legislative proceedings."}],
"filmmaking": [{"partOfSpeech": "noun", "definition": "The process of producing motion pictures for cinema or television."}],
"filtration": [{"partOfSpeech": "noun", "definition": "The process of passing a liquid through a barrier to remove particles."}],
"fingertips": [{"partOfSpeech": "noun", "definition": "The ends of the fingers, used for touching and feeling."}],
"fireplaces": [{"partOfSpeech": "noun", "definition": "Structures where fires are lit for warmth in a room."}],
"flashlight": [{"partOfSpeech": "noun", "definition": "A portable battery-powered light for illumination in the dark."}],
"floodplain": [{"partOfSpeech": "noun", "definition": "A flat area of land next to a river that is prone to periodic flooding."}],
"footprints": [{"partOfSpeech": "noun", "definition": "Marks left by feet on a surface, or the impact of something."}],
"foreground": [{"partOfSpeech": "noun", "definition": "The part of a view nearest to the observer."}],
"foreigners": [{"partOfSpeech": "noun", "definition": "People from a country other than one's own."}],
"forfeiture": [{"partOfSpeech": "noun", "definition": "The loss of property or a right as a penalty for wrongdoing."}],
"forgetting": [{"partOfSpeech": "verb", "definition": "Failing to remember something."}],
"formations": [{"partOfSpeech": "noun", "definition": "Arrangements or patterns in which things are organized."}],
"formatting": [{"partOfSpeech": "noun", "definition": "The way in which text or data is arranged or presented."}],
"formidable": [{"partOfSpeech": "adjective", "definition": "Inspiring fear or respect through being impressively powerful."}],
"formulated": [{"partOfSpeech": "verb", "definition": "Created or prepared carefully according to a specific plan."}],
"forwarding": [{"partOfSpeech": "verb", "definition": "Sending a letter, email, or message on to a further destination."}],
"foundation": [{"partOfSpeech": "noun", "definition": "The base on which something is built, or an organization set up with an endowment."}],
"fourteenth": [{"partOfSpeech": "adjective", "definition": "Coming after the thirteenth in a numbered sequence."}],
"fractional": [{"partOfSpeech": "adjective", "definition": "Relating to a small or incomplete part of a whole."}],
"fragmented": [{"partOfSpeech": "adjective", "definition": "Broken into separate pieces or parts; incomplete."}],
"fragrances": [{"partOfSpeech": "noun", "definition": "Pleasant, sweet smells; perfumes or scented products."}],
"frameworks": [{"partOfSpeech": "noun", "definition": "Basic structures underlying systems, concepts, or texts."}],
"franchises": [{"partOfSpeech": "noun", "definition": "Licenses granted to sell goods or services in a particular area."}],
"fraudulent": [{"partOfSpeech": "adjective", "definition": "Obtained or done through deceit and dishonesty."}],
"frequently": [{"partOfSpeech": "adverb", "definition": "Regularly; at short intervals; often."}],
"freshwater": [{"partOfSpeech": "noun", "definition": "Water that is not salty, as found in rivers and lakes."}],
"friendship": [{"partOfSpeech": "noun", "definition": "A close bond of mutual affection between people."}],
"frightened": [{"partOfSpeech": "adjective", "definition": "Feeling afraid or anxious; scared."}],
"frustrated": [{"partOfSpeech": "adjective", "definition": "Feeling upset or annoyed because of inability to change something."}],
"fulfilling": [{"partOfSpeech": "adjective", "definition": "Making someone feel satisfied and happy because of full development."}],
"fulfilment": [{"partOfSpeech": "noun", "definition": "The achievement of something desired or the satisfaction gained from it."}],
"functional": [{"partOfSpeech": "adjective", "definition": "Designed to be practical and useful rather than decorative."}],
"furnishing": [{"partOfSpeech": "noun", "definition": "Furniture and fittings provided in a room or building."}],
};
const merged = { ...existing, ...newDefs };
const answers = JSON.parse(readFileSync("./data/words-answer.json", "utf-8"));
const covered = answers.filter(w => new Set(Object.keys(merged)).has(w));
console.log(`Coverage: ${covered.length}/${answers.length} (${(covered.length/answers.length*100).toFixed(1)}%)`);
writeFileSync("./data/word-definitions.json", JSON.stringify(merged, null, 2) + "\n");
console.log("Written D-F batch");
