import { readFileSync, writeFileSync } from "fs";
const existing = JSON.parse(readFileSync("./data/word-definitions.json", "utf-8"));
const newDefs = {
  "narratives": [{"partOfSpeech": "noun", "definition": "spoken or written accounts of connected events; stories told in detail"}],
  "nationally": [{"partOfSpeech": "adverb", "definition": "across an entire country; on a countrywide scale"}],
  "nationwide": [{"partOfSpeech": "adjective", "definition": "extending or occurring throughout a whole country"}],
  "naturalist": [{"partOfSpeech": "noun", "definition": "a person who studies plants, animals, and the physical world"}],
  "navigating": [{"partOfSpeech": "verb", "definition": "finding a way through or across a route, terrain, or complex situation"}],
  "navigation": [{"partOfSpeech": "noun", "definition": "the process or activity of plotting and following a course from one place to another"}],
  "negatively": [{"partOfSpeech": "adverb", "definition": "in a harmful, unfavorable, or pessimistic manner"}],
  "negligence": [{"partOfSpeech": "noun", "definition": "failure to take proper care or give adequate attention to a duty or responsibility"}],
  "negligible": [{"partOfSpeech": "adjective", "definition": "so small or unimportant as to be not worth considering; insignificant"}],
  "negotiable": [{"partOfSpeech": "adjective", "definition": "open to discussion, modification, or bargaining between parties"}],
  "negotiated": [{"partOfSpeech": "verb", "definition": "reached an agreement through discussion and compromise between parties"}],
  "neighbours": [{"partOfSpeech": "noun", "definition": "people living close to or next door to one another"}],
  "networking": [{"partOfSpeech": "noun", "definition": "the practice of building professional contacts or linking computer systems together"}],
  "neutrality": [{"partOfSpeech": "noun", "definition": "the state of being impartial and not taking sides in a conflict or dispute"}],
  "newsletter": [{"partOfSpeech": "noun", "definition": "a printed or electronic bulletin regularly distributed to subscribers with updates and information"}],
  "newspapers": [{"partOfSpeech": "noun", "definition": "printed or digital publications issued daily or weekly containing articles, reports, and commentary"}],
  "nightclubs": [{"partOfSpeech": "noun", "definition": "entertainment venues open late at night for dancing, drinking, and live music"}],
  "nightmares": [{"partOfSpeech": "noun", "definition": "frightening or deeply unpleasant dreams; terrifying experiences"}],
  "nineteenth": [{"partOfSpeech": "adjective", "definition": "coming after the eighteenth in position or order; the ordinal form of 19"}],
  "nominating": [{"partOfSpeech": "verb", "definition": "formally proposing someone as a candidate for a position, award, or honor"}],
  "nomination": [{"partOfSpeech": "noun", "definition": "the act of formally proposing someone for election, an award, or a role"}],
  "nonfiction": [{"partOfSpeech": "noun", "definition": "prose writing based on facts, real events, and actual people rather than imagined stories"}],
  "normalized": [{"partOfSpeech": "verb", "definition": "brought to a standard or usual state; made consistent with a baseline"}],
  "noteworthy": [{"partOfSpeech": "adjective", "definition": "deserving attention or recognition because of being remarkable or significant"}],
  "noticeable": [{"partOfSpeech": "adjective", "definition": "easily seen, heard, or detected; clearly apparent"}],
  "nutritious": [{"partOfSpeech": "adjective", "definition": "containing substances essential for growth and good health; nourishing"}],
  "obituaries": [{"partOfSpeech": "noun", "definition": "published notices announcing and summarizing the lives of people who have recently died"}],
  "objections": [{"partOfSpeech": "noun", "definition": "expressions of disagreement, disapproval, or opposition to something"}],
  "objectives": [{"partOfSpeech": "noun", "definition": "goals or targets that one is working to achieve"}],
  "obligation": [{"partOfSpeech": "noun", "definition": "a duty, commitment, or requirement that one is bound to fulfill"}],
  "obligatory": [{"partOfSpeech": "adjective", "definition": "required by law, rule, or moral duty; compulsory"}],
  "observable": [{"partOfSpeech": "adjective", "definition": "able to be seen, noticed, or measured; detectable"}],
  "observance": [{"partOfSpeech": "noun", "definition": "the practice of following a custom, law, or ritual; celebration of a holiday or ceremony"}],
  "obstetrics": [{"partOfSpeech": "noun", "definition": "the branch of medicine dealing with childbirth and the care of women during pregnancy and delivery"}],
  "occasional": [{"partOfSpeech": "adjective", "definition": "happening from time to time; not frequent or regular"}],
  "occidental": [{"partOfSpeech": "adjective", "definition": "relating to the countries and cultures of the West, especially Europe and the Americas"}],
  "occupation": [{"partOfSpeech": "noun", "definition": "a person's job or profession; also, the act of taking control of a territory by force"}],
  "occurrence": [{"partOfSpeech": "noun", "definition": "an event or incident that takes place; the fact of something happening"}],
  "oceanfront": [{"partOfSpeech": "adjective", "definition": "situated directly alongside or facing the sea"}],
  "officially": [{"partOfSpeech": "adverb", "definition": "in a formal or authoritative manner; as sanctioned by those in authority"}],
  "ontologies": [{"partOfSpeech": "noun", "definition": "sets of concepts and categories within a domain that define the relationships between entities"}],
  "operations": [{"partOfSpeech": "noun", "definition": "organized activities or processes carried out to achieve a purpose; surgical procedures"}],
  "operatives": [{"partOfSpeech": "noun", "definition": "workers or agents, especially those engaged in secret or covert activities"}],
  "opposition": [{"partOfSpeech": "noun", "definition": "resistance, hostility, or active disagreement against a plan, policy, or group"}],
  "oppression": [{"partOfSpeech": "noun", "definition": "prolonged cruel or unjust treatment, especially by those in power; systematic subjugation"}],
  "oppressive": [{"partOfSpeech": "adjective", "definition": "unjustly harsh and authoritarian; weighing heavily on the mind or spirits"}],
  "optimistic": [{"partOfSpeech": "adjective", "definition": "hopeful and confident about the future or a positive outcome"}],
  "optimizing": [{"partOfSpeech": "verb", "definition": "making something as effective or functional as possible; improving for best results"}],
  "optionally": [{"partOfSpeech": "adverb", "definition": "in a way that is not required; as a matter of choice rather than necessity"}],
  "orchestral": [{"partOfSpeech": "adjective", "definition": "relating to or composed for a large ensemble of musical instruments"}],
  "orchestras": [{"partOfSpeech": "noun", "definition": "large groups of musicians playing various instruments together under a conductor"}],
  "ordinances": [{"partOfSpeech": "noun", "definition": "official laws or regulations enacted by a municipal authority or government body"}],
  "ordinarily": [{"partOfSpeech": "adverb", "definition": "under normal or usual circumstances; as a general rule"}],
  "ordination": [{"partOfSpeech": "noun", "definition": "the ceremonial conferring of holy orders or ministerial authority upon a member of the clergy"}],
  "organising": [{"partOfSpeech": "verb", "definition": "arranging, coordinating, or structuring elements into an orderly system"}],
  "organizers": [{"partOfSpeech": "noun", "definition": "people who arrange and coordinate events, activities, or groups"}],
  "organizing": [{"partOfSpeech": "verb", "definition": "arranging systematically; coordinating elements into a structured whole"}],
  "orientated": [{"partOfSpeech": "verb", "definition": "aligned or directed toward a particular goal, direction, or interest"}],
  "originally": [{"partOfSpeech": "adverb", "definition": "at first; in the beginning or from the start"}],
  "originated": [{"partOfSpeech": "verb", "definition": "began or arose from a particular source, place, or time"}],
  "originates": [{"partOfSpeech": "verb", "definition": "begins or comes into being from a particular source or cause"}],
  "originator": [{"partOfSpeech": "noun", "definition": "the person who first creates, invents, or initiates something"}],
  "ornamental": [{"partOfSpeech": "adjective", "definition": "serving as decoration rather than having a practical function; decorative"}],
  "orthogonal": [{"partOfSpeech": "adjective", "definition": "at right angles to each other; statistically independent or unrelated"}],
  "oscillator": [{"partOfSpeech": "noun", "definition": "a device or circuit that produces a repetitive, alternating signal or vibration"}],
  "outfitters": [{"partOfSpeech": "noun", "definition": "businesses or individuals that supply equipment and clothing for outdoor activities or expeditions"}],
  "outpatient": [{"partOfSpeech": "noun", "definition": "a person receiving medical treatment without being admitted to a hospital overnight"}],
  "outrageous": [{"partOfSpeech": "adjective", "definition": "shockingly bad, excessive, or offensive; wildly beyond acceptable limits"}],
  "overcoming": [{"partOfSpeech": "verb", "definition": "successfully dealing with or gaining control of a difficulty or obstacle"}],
  "overloaded": [{"partOfSpeech": "verb", "definition": "burdened with too much weight, work, or demand beyond capacity"}],
  "overlooked": [{"partOfSpeech": "verb", "definition": "failed to notice or consider something; disregarded inadvertently"}],
  "overriding": [{"partOfSpeech": "adjective", "definition": "more important than all other considerations; dominant and superseding"}],
  "overseeing": [{"partOfSpeech": "verb", "definition": "supervising and directing the work or activities of others"}],
  "overturned": [{"partOfSpeech": "verb", "definition": "reversed a decision or ruling; flipped upside down"}],
  "overweight": [{"partOfSpeech": "adjective", "definition": "above a healthy or acceptable body mass; heavier than what is considered standard"}],
  "palliative": [{"partOfSpeech": "adjective", "definition": "providing relief from symptoms without curing the underlying condition; soothing"}],
  "paperbacks": [{"partOfSpeech": "noun", "definition": "books bound with a flexible cover made of thick paper or card"}],
  "paragraphs": [{"partOfSpeech": "noun", "definition": "distinct sections of written text dealing with a single theme, beginning on a new line"}],
  "parameters": [{"partOfSpeech": "noun", "definition": "measurable factors or limits that define the scope of a system or process"}],
  "paranormal": [{"partOfSpeech": "adjective", "definition": "beyond the range of scientific explanation; relating to supernatural phenomena"}],
  "parenthood": [{"partOfSpeech": "noun", "definition": "the state or experience of being a mother or father; raising children"}],
  "parliament": [{"partOfSpeech": "noun", "definition": "the supreme legislative body of a country, especially in the United Kingdom"}],
  "particular": [{"partOfSpeech": "adjective", "definition": "specific, distinct, or individual rather than general; especially notable or demanding"}],
  "partitions": [{"partOfSpeech": "noun", "definition": "structures or dividers that separate spaces into distinct sections"}],
  "partnering": [{"partOfSpeech": "verb", "definition": "joining forces with another person or entity for a shared purpose or venture"}],
  "passengers": [{"partOfSpeech": "noun", "definition": "people traveling in a vehicle, aircraft, or vessel who are not the driver or crew"}],
  "passionate": [{"partOfSpeech": "adjective", "definition": "showing or expressing strong feelings, enthusiasm, or intense emotion"}],
  "pathfinder": [{"partOfSpeech": "noun", "definition": "a person who goes ahead and discovers a new route or way forward; a trailblazer"}],
  "patriotism": [{"partOfSpeech": "noun", "definition": "devoted love, support, and defense of one's country and its values"}],
  "peacefully": [{"partOfSpeech": "adverb", "definition": "in a calm, tranquil, and nonviolent manner; without disturbance"}],
  "pedestrian": [{"partOfSpeech": "noun", "definition": "a person walking along a road or in a developed area on foot"}],
  "pediatrics": [{"partOfSpeech": "noun", "definition": "the branch of medicine concerned with the health and diseases of children and infants"}],
  "penetrated": [{"partOfSpeech": "verb", "definition": "entered or passed through something; pierced or broke into a barrier or surface"}],
  "pensioners": [{"partOfSpeech": "noun", "definition": "retired individuals who receive a regular payment from a fund built up during their working years"}],
  "peppermint": [{"partOfSpeech": "noun", "definition": "a fragrant herb of the mint family used in flavoring food, drinks, and confections"}],
  "percentile": [{"partOfSpeech": "noun", "definition": "a value below which a given percentage of observations in a data set falls"}],
  "perception": [{"partOfSpeech": "noun", "definition": "the ability to see, hear, or become aware of something through the senses; a way of understanding"}],
  "perceptual": [{"partOfSpeech": "adjective", "definition": "relating to the ability to interpret or become aware of sensory information"}],
  "percussion": [{"partOfSpeech": "noun", "definition": "musical instruments played by striking, shaking, or scraping, such as drums and cymbals"}],
  "perennials": [{"partOfSpeech": "noun", "definition": "plants that live for more than two years, regrowing each season from their rootstock"}],
  "perfection": [{"partOfSpeech": "noun", "definition": "the state of being flawless or as good as it is possible to be"}],
  "perforated": [{"partOfSpeech": "adjective", "definition": "pierced with a series of small holes to allow tearing, passage of air, or drainage"}],
  "performers": [{"partOfSpeech": "noun", "definition": "people who entertain an audience through acting, singing, dancing, or other artistic expression"}],
  "performing": [{"partOfSpeech": "verb", "definition": "carrying out an action or presenting entertainment before an audience"}],
  "periodical": [{"partOfSpeech": "noun", "definition": "a magazine or journal published at regular intervals, such as weekly or monthly"}],
  "peripheral": [{"partOfSpeech": "adjective", "definition": "relating to or situated on the edge or outskirts; of secondary importance"}],
  "permission": [{"partOfSpeech": "noun", "definition": "official authorization or consent to do something; formal approval granted by an authority"}],
  "permitting": [{"partOfSpeech": "verb", "definition": "allowing or giving authorization for something to happen or be done"}],
  "persecuted": [{"partOfSpeech": "verb", "definition": "subjected to hostility, cruel treatment, or systematic mistreatment, especially for beliefs or identity"}],
  "persistent": [{"partOfSpeech": "adjective", "definition": "continuing firmly despite difficulty or opposition; enduring over a long period"}],
  "personally": [{"partOfSpeech": "adverb", "definition": "in a way that involves direct individual involvement; from one's own viewpoint"}],
  "persuasion": [{"partOfSpeech": "noun", "definition": "the act of convincing someone to do or believe something through reasoning or argument"}],
  "persuasive": [{"partOfSpeech": "adjective", "definition": "effective at convincing others; compelling in argument or presentation"}],
  "pertaining": [{"partOfSpeech": "verb", "definition": "relating or having relevance to a particular subject or matter"}],
  "pesticides": [{"partOfSpeech": "noun", "definition": "chemical substances used to kill insects, weeds, or other organisms harmful to crops"}],
  "petitioner": [{"partOfSpeech": "noun", "definition": "a person who formally requests something from an authority, especially through a signed document"}],
  "pharmacies": [{"partOfSpeech": "noun", "definition": "establishments where medicinal drugs are dispensed and sold"}],
  "pharmacist": [{"partOfSpeech": "noun", "definition": "a licensed professional who prepares and dispenses medicinal drugs"}],
  "phenomenal": [{"partOfSpeech": "adjective", "definition": "remarkably great or extraordinary; exceptionally impressive"}],
  "philosophy": [{"partOfSpeech": "noun", "definition": "the study of fundamental questions about existence, knowledge, values, and reason"}],
  "phosphorus": [{"partOfSpeech": "noun", "definition": "a chemical element essential to living organisms, used in fertilizers and matches"}],
  "photograph": [{"partOfSpeech": "noun", "definition": "an image captured by a camera using light exposure on a sensitive surface or digital sensor"}],
  "physically": [{"partOfSpeech": "adverb", "definition": "in a way that relates to the body or material things rather than the mind"}],
  "physicians": [{"partOfSpeech": "noun", "definition": "qualified doctors of medicine who diagnose and treat illness and injury"}],
  "physicists": [{"partOfSpeech": "noun", "definition": "scientists who study matter, energy, and the fundamental forces of the universe"}],
  "pilgrimage": [{"partOfSpeech": "noun", "definition": "a journey to a sacred or meaningful place undertaken for spiritual or devotional reasons"}],
  "pioneering": [{"partOfSpeech": "adjective", "definition": "involving new ideas or methods; leading the way in a field of activity"}],
  "placements": [{"partOfSpeech": "noun", "definition": "the action of putting something in a particular position; temporary work assignments"}],
  "plagiarism": [{"partOfSpeech": "noun", "definition": "the practice of taking someone else's work or ideas and passing them off as one's own"}],
  "plaintiffs": [{"partOfSpeech": "noun", "definition": "people who bring a case against another in a court of law"}],
  "plantation": [{"partOfSpeech": "noun", "definition": "a large estate where crops such as coffee, sugar, or tobacco are cultivated"}],
  "playground": [{"partOfSpeech": "noun", "definition": "an outdoor area with equipment and space for children to play on and explore"}],
  "playwright": [{"partOfSpeech": "noun", "definition": "a person who writes scripts for theatrical stage productions"}],
  "pleasantly": [{"partOfSpeech": "adverb", "definition": "in an enjoyable, agreeable, or friendly manner"}],
  "politician": [{"partOfSpeech": "noun", "definition": "a person actively involved in party politics or holding a government office"}],
  "pollutants": [{"partOfSpeech": "noun", "definition": "harmful substances introduced into the environment that contaminate air, water, or soil"}],
  "polynomial": [{"partOfSpeech": "noun", "definition": "a mathematical expression consisting of variables and coefficients combined using addition, subtraction, and multiplication"}],
  "popularity": [{"partOfSpeech": "noun", "definition": "the state of being widely admired, liked, or supported by many people"}],
  "population": [{"partOfSpeech": "noun", "definition": "the total number of people or inhabitants living in a particular area or country"}],
  "portfolios": [{"partOfSpeech": "noun", "definition": "collections of work samples, investments, or documents assembled to showcase holdings or achievements"}],
  "positional": [{"partOfSpeech": "adjective", "definition": "relating to or determined by a specific location or placement within a sequence"}],
  "positioned": [{"partOfSpeech": "verb", "definition": "placed or arranged in a particular location or strategic spot"}],
  "positively": [{"partOfSpeech": "adverb", "definition": "in an affirmative, constructive, or favorable manner; with certainty"}],
  "possessing": [{"partOfSpeech": "verb", "definition": "having or owning something; holding as property or a characteristic"}],
  "possession": [{"partOfSpeech": "noun", "definition": "the state of having, owning, or controlling something; an item that belongs to someone"}],
  "postmaster": [{"partOfSpeech": "noun", "definition": "an official in charge of a local mail delivery office"}],
  "postscript": [{"partOfSpeech": "noun", "definition": "an additional remark or message added at the end of a letter after the signature"}],
  "postseason": [{"partOfSpeech": "noun", "definition": "the period of tournament or championship games played after the regular sporting season ends"}],
  "potentials": [{"partOfSpeech": "noun", "definition": "latent qualities or abilities that may be developed to produce future success or capability"}],
  "powerfully": [{"partOfSpeech": "adverb", "definition": "with great strength, force, or intensity; in a commanding way"}],
  "powerhouse": [{"partOfSpeech": "noun", "definition": "a person, team, or organization with great energy, strength, or influence"}],
  "practicing": [{"partOfSpeech": "verb", "definition": "repeatedly doing an activity to improve skill; carrying out a profession or belief"}],
  "practising": [{"partOfSpeech": "verb", "definition": "repeatedly carrying out an activity or exercising a skill to gain proficiency"}],
  "precaution": [{"partOfSpeech": "noun", "definition": "a measure taken in advance to guard against possible danger or failure"}],
  "precedence": [{"partOfSpeech": "noun", "definition": "the condition of being considered more important than something else; priority in order or rank"}],
  "precursors": [{"partOfSpeech": "noun", "definition": "things that come before and lead to the development of something else; forerunners"}],
  "predefined": [{"partOfSpeech": "adjective", "definition": "established or specified in advance before being used or applied"}],
  "predicates": [{"partOfSpeech": "noun", "definition": "the parts of a sentence that state something about the subject; logical assertions"}],
  "predicting": [{"partOfSpeech": "verb", "definition": "saying or estimating that something will happen in the future based on evidence or reasoning"}],
  "prediction": [{"partOfSpeech": "noun", "definition": "a forecast or statement about what will happen in the future"}],
  "predictive": [{"partOfSpeech": "adjective", "definition": "relating to or able to forecast future events or outcomes based on data or patterns"}],
  "predictors": [{"partOfSpeech": "noun", "definition": "factors or variables used to forecast a future event or outcome"}],
  "prefecture": [{"partOfSpeech": "noun", "definition": "an administrative district or region governed by an appointed or elected official"}],
  "preferable": [{"partOfSpeech": "adjective", "definition": "more desirable or suitable than other available choices"}],
  "preferably": [{"partOfSpeech": "adverb", "definition": "ideally; if possible, as the first choice among alternatives"}],
  "preference": [{"partOfSpeech": "noun", "definition": "a greater liking for one alternative over another; a favored choice"}],
  "prejudices": [{"partOfSpeech": "noun", "definition": "preconceived opinions not based on reason or experience; unfair biases against groups"}],
  "prepayment": [{"partOfSpeech": "noun", "definition": "payment made for goods or services before they are received or due"}],
  "prescribed": [{"partOfSpeech": "verb", "definition": "officially recommended or authorized, especially a medical treatment by a doctor"}],
  "presenters": [{"partOfSpeech": "noun", "definition": "people who introduce or host a show, program, or conference session"}],
  "presenting": [{"partOfSpeech": "verb", "definition": "showing, delivering, or introducing something to an audience or group"}],
  "preserving": [{"partOfSpeech": "verb", "definition": "maintaining something in its existing state; protecting from harm or decay"}],
  "presidency": [{"partOfSpeech": "noun", "definition": "the office, role, or term of a head of state or organization leader"}],
  "presidents": [{"partOfSpeech": "noun", "definition": "heads of state, organizations, or institutions who hold the highest authority"}],
  "presumably": [{"partOfSpeech": "adverb", "definition": "used to convey that something is very likely true based on available evidence"}],
  "pretending": [{"partOfSpeech": "verb", "definition": "acting as though something is the case when it is not; feigning or simulating"}],
  "prevailing": [{"partOfSpeech": "adjective", "definition": "most common or widespread at a particular time; dominant or current"}],
  "prevalence": [{"partOfSpeech": "noun", "definition": "the condition of being widespread or commonly occurring in a particular area or population"}],
  "preventing": [{"partOfSpeech": "verb", "definition": "stopping something from happening or arising; keeping someone from doing something"}],
  "prevention": [{"partOfSpeech": "noun", "definition": "the act of stopping something undesirable from occurring; protective measures taken in advance"}],
  "preventive": [{"partOfSpeech": "adjective", "definition": "designed to stop something harmful or unwanted from happening; protective in nature"}],
  "previously": [{"partOfSpeech": "adverb", "definition": "at an earlier time; before the present moment or event in question"}],
  "priesthood": [{"partOfSpeech": "noun", "definition": "the office, position, or collective body of ordained religious ministers or clergy"}],
  "primitives": [{"partOfSpeech": "noun", "definition": "basic or fundamental building blocks in computing, art, or mathematics"}],
  "principals": [{"partOfSpeech": "noun", "definition": "heads of schools or leading figures in an organization, transaction, or legal matter"}],
  "principles": [{"partOfSpeech": "noun", "definition": "fundamental truths, rules, or moral standards that guide behavior or reasoning"}],
  "priorities": [{"partOfSpeech": "noun", "definition": "things regarded as more important than others; items given special attention first"}],
  "prioritize": [{"partOfSpeech": "verb", "definition": "to designate or treat something as more important; to rank tasks by urgency"}],
  "privileged": [{"partOfSpeech": "adjective", "definition": "having special advantages, rights, or immunities not available to everyone"}],
  "privileges": [{"partOfSpeech": "noun", "definition": "special rights, advantages, or immunities granted to a particular person or group"}],
  "procedural": [{"partOfSpeech": "adjective", "definition": "relating to an established or official series of steps for accomplishing a task"}],
  "procedures": [{"partOfSpeech": "noun", "definition": "established series of actions or steps followed in a regular, defined order"}],
  "proceeding": [{"partOfSpeech": "noun", "definition": "a legal action or formal course of events; the act of moving forward"}],
  "processing": [{"partOfSpeech": "noun", "definition": "the act of handling, treating, or converting data or materials through a series of steps"}],
  "procession": [{"partOfSpeech": "noun", "definition": "a group of people or vehicles moving forward in an orderly line, often ceremonially"}],
  "processors": [{"partOfSpeech": "noun", "definition": "devices or units that carry out computational operations; entities that handle and transform data"}],
  "proclaimed": [{"partOfSpeech": "verb", "definition": "announced officially or publicly; declared something with confidence or authority"}],
  "production": [{"partOfSpeech": "noun", "definition": "the process of making, manufacturing, or creating goods, content, or artistic works"}],
  "productive": [{"partOfSpeech": "adjective", "definition": "achieving a significant amount of output or results; yielding favorable outcomes"}],
  "profession": [{"partOfSpeech": "noun", "definition": "a paid occupation requiring specialized education, training, or formal qualifications"}],
  "professors": [{"partOfSpeech": "noun", "definition": "senior academic teachers or scholars holding a high rank at a university or college"}],
  "proficient": [{"partOfSpeech": "adjective", "definition": "highly competent or skilled through training and practice; adept"}],
  "profitable": [{"partOfSpeech": "adjective", "definition": "yielding financial gain or useful results; commercially successful"}],
  "profoundly": [{"partOfSpeech": "adverb", "definition": "to a very great or intense degree; in a deeply meaningful way"}],
  "programmed": [{"partOfSpeech": "verb", "definition": "given a set of coded instructions to carry out automatically; configured to function"}],
  "programmer": [{"partOfSpeech": "noun", "definition": "a person who writes and develops software code for computers or other devices"}],
  "programmes": [{"partOfSpeech": "noun", "definition": "planned series of events, activities, or broadcast shows; British spelling of programs"}],
  "progressed": [{"partOfSpeech": "verb", "definition": "moved forward or advanced toward a goal or more developed state"}],
  "progresses": [{"partOfSpeech": "verb", "definition": "moves forward or develops toward a more advanced or improved state"}],
  "prohibited": [{"partOfSpeech": "adjective", "definition": "formally forbidden by law, rule, or authority; banned"}],
  "projecting": [{"partOfSpeech": "verb", "definition": "extending outward; estimating future trends; casting an image onto a surface"}],
  "projection": [{"partOfSpeech": "noun", "definition": "an estimate or forecast based on current data; the display of an image on a surface"}],
  "projectors": [{"partOfSpeech": "noun", "definition": "devices that cast images or video onto a screen or wall for viewing"}],
  "prominence": [{"partOfSpeech": "noun", "definition": "the state of being important, famous, or widely known; high visibility"}],
  "promotions": [{"partOfSpeech": "noun", "definition": "advancements in rank or position; activities aimed at publicizing a product or event"}],
  "pronounced": [{"partOfSpeech": "adjective", "definition": "very noticeable or marked; clearly and distinctly evident"}],
  "propaganda": [{"partOfSpeech": "noun", "definition": "biased or misleading information spread to promote a political cause or viewpoint"}],
  "propagated": [{"partOfSpeech": "verb", "definition": "spread or transmitted widely; bred or reproduced organisms from a parent stock"}],
  "propensity": [{"partOfSpeech": "noun", "definition": "a natural inclination or tendency to behave in a particular way"}],
  "properties": [{"partOfSpeech": "noun", "definition": "characteristics, qualities, or attributes of something; also, buildings or land owned"}],
  "prophecies": [{"partOfSpeech": "noun", "definition": "predictions or declarations about what will happen in the future, often divinely inspired"}],
  "proponents": [{"partOfSpeech": "noun", "definition": "people who advocate for or support a particular theory, proposal, or cause"}],
  "proportion": [{"partOfSpeech": "noun", "definition": "a part, share, or number considered in relation to a whole; comparative ratio"}],
  "proprietor": [{"partOfSpeech": "noun", "definition": "the owner of a business, property, or establishment"}],
  "propulsion": [{"partOfSpeech": "noun", "definition": "the force or process that drives something forward, especially a vehicle or rocket"}],
  "prosecuted": [{"partOfSpeech": "verb", "definition": "brought legal proceedings against someone in a court of law for a criminal offense"}],
  "prosecutor": [{"partOfSpeech": "noun", "definition": "a legal official who conducts criminal cases against defendants on behalf of the state"}],
  "prospectus": [{"partOfSpeech": "noun", "definition": "a formal document describing the details of an investment offering or educational institution"}],
  "prosperity": [{"partOfSpeech": "noun", "definition": "the state of being financially successful and thriving; economic well-being"}],
  "prosperous": [{"partOfSpeech": "adjective", "definition": "successful in material terms; flourishing financially; wealthy and thriving"}],
  "prosthetic": [{"partOfSpeech": "adjective", "definition": "relating to an artificial device that replaces a missing body part"}],
  "prostitute": [{"partOfSpeech": "noun", "definition": "a person who engages in sexual activity in exchange for payment"}],
  "protecting": [{"partOfSpeech": "verb", "definition": "keeping safe from harm, injury, or damage; shielding or guarding"}],
  "protection": [{"partOfSpeech": "noun", "definition": "the act of keeping someone or something safe from harm, damage, or loss"}],
  "protective": [{"partOfSpeech": "adjective", "definition": "serving or intended to shield from harm, danger, or damage"}],
  "protectors": [{"partOfSpeech": "noun", "definition": "people or things that guard, shield, or defend others from harm or danger"}],
  "protestant": [{"partOfSpeech": "noun", "definition": "a member or follower of any Western Christian church that separated from Roman Catholicism during the Reformation"}],
  "protesters": [{"partOfSpeech": "noun", "definition": "people who publicly express disapproval or objection through organized demonstrations"}],
  "protesting": [{"partOfSpeech": "verb", "definition": "expressing strong disapproval or objection publicly through demonstrations or statements"}],
  "prototypes": [{"partOfSpeech": "noun", "definition": "first or preliminary models of something from which later versions are developed"}],
  "provenance": [{"partOfSpeech": "noun", "definition": "the place of origin or earliest known history of something, especially an artwork or artifact"}],
  "providence": [{"partOfSpeech": "noun", "definition": "the protective care of a higher power or nature; timely preparation for the future"}],
  "provincial": [{"partOfSpeech": "adjective", "definition": "relating to a province or region outside the capital; unsophisticated or narrow-minded"}],
  "provisions": [{"partOfSpeech": "noun", "definition": "supplies of food and necessities; clauses or conditions within a legal document"}],
  "prudential": [{"partOfSpeech": "adjective", "definition": "involving or showing care and thought for the future; exercising sound judgment"}],
  "publicized": [{"partOfSpeech": "verb", "definition": "made widely known through media or promotional efforts; given public attention"}],
  "publishers": [{"partOfSpeech": "noun", "definition": "companies or individuals that produce and distribute books, journals, or other media"}],
  "publishing": [{"partOfSpeech": "noun", "definition": "the business or activity of preparing and issuing books, newspapers, or other media for sale"}],
  "punishable": [{"partOfSpeech": "adjective", "definition": "liable to or deserving a penalty or sanction under law or rules"}],
  "punishment": [{"partOfSpeech": "noun", "definition": "a penalty imposed for breaking a law, rule, or norm; the infliction of a consequence"}],
  "purchasers": [{"partOfSpeech": "noun", "definition": "people or entities that buy goods or services; buyers"}],
  "purchasing": [{"partOfSpeech": "verb", "definition": "buying or acquiring goods or services in exchange for payment"}],
  "quadrangle": [{"partOfSpeech": "noun", "definition": "a four-sided geometrical figure; a rectangular courtyard enclosed by buildings"}],
  "qualifiers": [{"partOfSpeech": "noun", "definition": "words or phrases that modify the meaning of another element; preliminary rounds that determine eligibility"}],
  "qualifying": [{"partOfSpeech": "verb", "definition": "meeting the required standards or conditions to be eligible for something"}],
  "quantified": [{"partOfSpeech": "verb", "definition": "expressed or measured as a numerical amount or quantity"}],
  "quantities": [{"partOfSpeech": "noun", "definition": "amounts or numbers of things; measurable portions or totals"}],
  "quarantine": [{"partOfSpeech": "noun", "definition": "a period of isolation imposed to stop the spread of disease or infection"}],
  "questioned": [{"partOfSpeech": "verb", "definition": "asked someone for information; expressed doubt or uncertainty about something"}],
  "quotations": [{"partOfSpeech": "noun", "definition": "exact phrases or passages repeated from a source; formal statements of price for goods or services"}],
  "rainforest": [{"partOfSpeech": "noun", "definition": "a dense tropical woodland with consistently heavy rainfall and lush biodiversity"}],
  "randomized": [{"partOfSpeech": "verb", "definition": "arranged or selected in a deliberately unpredictable order to avoid bias"}],
  "randomness": [{"partOfSpeech": "noun", "definition": "the quality of lacking any pattern, order, or predictability"}],
  "readership": [{"partOfSpeech": "noun", "definition": "the collective audience or number of people who regularly read a publication"}],
  "reasonable": [{"partOfSpeech": "adjective", "definition": "fair, sensible, and appropriate; within the bounds of sound judgment"}],
  "reasonably": [{"partOfSpeech": "adverb", "definition": "to a fair or moderate degree; in a logical and sensible manner"}],
  "reassuring": [{"partOfSpeech": "adjective", "definition": "serving to remove doubts or fears; comforting and confidence-building"}],
  "rebuilding": [{"partOfSpeech": "verb", "definition": "constructing again after damage or destruction; restoring to a former state"}],
  "receivable": [{"partOfSpeech": "adjective", "definition": "able to be collected as payment; designating money owed to a business"}],
  "receptacle": [{"partOfSpeech": "noun", "definition": "a container or holder used for storing or collecting items"}],
  "receptions": [{"partOfSpeech": "noun", "definition": "formal social gatherings to welcome guests; the way something is received or greeted"}],
  "recipients": [{"partOfSpeech": "noun", "definition": "people who receive or are awarded something, such as a gift, prize, or payment"}],
  "reciprocal": [{"partOfSpeech": "adjective", "definition": "given, felt, or done in return; mutual and shared between two parties"}],
  "recognised": [{"partOfSpeech": "verb", "definition": "identified from prior knowledge or experience; acknowledged as valid or notable"}],
  "recognized": [{"partOfSpeech": "verb", "definition": "identified or acknowledged as known, valid, or worthy of attention"}],
  "recognizes": [{"partOfSpeech": "verb", "definition": "identifies or acknowledges someone or something from previous experience or knowledge"}],
  "recommends": [{"partOfSpeech": "verb", "definition": "suggests as being suitable, worthy, or beneficial; endorses a course of action"}],
  "reconciled": [{"partOfSpeech": "verb", "definition": "restored friendly relations; made compatible or brought into agreement"}],
  "reconsider": [{"partOfSpeech": "verb", "definition": "think about something again, especially with the possibility of changing a decision"}],
  "recordable": [{"partOfSpeech": "adjective", "definition": "capable of being captured on a storage medium for later playback or review"}],
  "recordings": [{"partOfSpeech": "noun", "definition": "captured audio or video stored on a medium for later playback"}],
  "recovering": [{"partOfSpeech": "verb", "definition": "regaining health, composure, or a normal state after illness, setback, or loss"}],
  "recreation": [{"partOfSpeech": "noun", "definition": "leisure activities done for enjoyment and relaxation during free time"}],
  "recruiters": [{"partOfSpeech": "noun", "definition": "people whose job is to find and hire new staff or enlist new members"}],
  "recruiting": [{"partOfSpeech": "verb", "definition": "seeking out and enrolling new members, employees, or participants"}],
  "recurrence": [{"partOfSpeech": "noun", "definition": "the fact of happening again or repeatedly; a repeated instance of something"}],
  "redemption": [{"partOfSpeech": "noun", "definition": "the act of being saved from sin, error, or evil; the recovery or exchange of something for value"}],
  "redesigned": [{"partOfSpeech": "verb", "definition": "created a new look or structure for something that already existed; reworked the layout"}],
  "redirected": [{"partOfSpeech": "verb", "definition": "sent or channeled in a different direction or to an alternative destination"}],
  "reductions": [{"partOfSpeech": "noun", "definition": "decreases in size, amount, or degree; the acts of making something smaller or less"}],
  "redundancy": [{"partOfSpeech": "noun", "definition": "the state of being no longer needed or useful; duplication as a safety backup"}],
  "referenced": [{"partOfSpeech": "verb", "definition": "mentioned, cited, or alluded to as a source of information"}],
  "references": [{"partOfSpeech": "noun", "definition": "sources cited for information; also, letters or statements attesting to someone's character or ability"}],
  "referendum": [{"partOfSpeech": "noun", "definition": "a direct vote by the electorate on a specific political question or proposed law"}],
  "refinement": [{"partOfSpeech": "noun", "definition": "the process of improving something by making small changes; elegance and polish"}],
  "refineries": [{"partOfSpeech": "noun", "definition": "industrial plants where raw materials such as oil or sugar are purified into usable products"}],
  "reflecting": [{"partOfSpeech": "verb", "definition": "throwing back light or an image; thinking deeply or carefully about something"}],
  "reflection": [{"partOfSpeech": "noun", "definition": "an image seen in a mirror or shiny surface; serious thought or contemplation"}],
  "reflective": [{"partOfSpeech": "adjective", "definition": "capable of throwing back light or images; given to deep thought and consideration"}],
  "refractive": [{"partOfSpeech": "adjective", "definition": "relating to the bending of light or other waves as they pass between different media"}],
  "refractory": [{"partOfSpeech": "adjective", "definition": "resistant to treatment or control; stubbornly unresponsive; able to withstand high temperatures"}],
  "refreshing": [{"partOfSpeech": "adjective", "definition": "pleasantly new, different, or invigorating; restoring strength or energy"}],
  "refundable": [{"partOfSpeech": "adjective", "definition": "eligible to be returned for a full or partial repayment of the purchase price"}],
  "regardless": [{"partOfSpeech": "adverb", "definition": "without being affected by any other factor; despite everything; in any case"}],
  "regionally": [{"partOfSpeech": "adverb", "definition": "in a way that relates to or affects a particular geographic area or district"}],
  "registered": [{"partOfSpeech": "adjective", "definition": "officially recorded or enrolled on a formal list or database"}],
  "registrant": [{"partOfSpeech": "noun", "definition": "a person who has officially enrolled or signed up for something"}],
  "registrars": [{"partOfSpeech": "noun", "definition": "officials responsible for keeping official records, especially at institutions or domain authorities"}],
  "registries": [{"partOfSpeech": "noun", "definition": "official lists, databases, or places where records are kept and maintained"}],
  "regression": [{"partOfSpeech": "noun", "definition": "a return to a less developed state; a statistical method for estimating relationships between variables"}],
  "regularity": [{"partOfSpeech": "noun", "definition": "the quality of occurring at uniform intervals or following a consistent pattern"}],
  "regulating": [{"partOfSpeech": "verb", "definition": "controlling or maintaining the rate, speed, or standard of a process or system"}],
  "regulation": [{"partOfSpeech": "noun", "definition": "an official rule or directive made and maintained by an authority"}],
  "regulators": [{"partOfSpeech": "noun", "definition": "bodies or devices that control, supervise, or maintain standards within an industry or system"}],
  "regulatory": [{"partOfSpeech": "adjective", "definition": "relating to or serving the purpose of official rules and oversight of an industry or process"}],
  "rehearsals": [{"partOfSpeech": "noun", "definition": "practice sessions in preparation for a public performance or ceremony"}],
  "reimbursed": [{"partOfSpeech": "verb", "definition": "repaid money that was spent or lost; compensated someone for an expense incurred"}],
  "reinforced": [{"partOfSpeech": "verb", "definition": "strengthened or supported with additional material, personnel, or emphasis"}],
  "reinforces": [{"partOfSpeech": "verb", "definition": "strengthens or adds support to something; makes a belief or behavior firmer"}],
  "reinstated": [{"partOfSpeech": "verb", "definition": "restored to a former position, right, or state after removal or suspension"}],
  "reiterated": [{"partOfSpeech": "verb", "definition": "said or stated again for emphasis or clarity; repeated a point firmly"}],
  "relational": [{"partOfSpeech": "adjective", "definition": "concerning the way in which two or more things are connected or associated"}],
  "relatively": [{"partOfSpeech": "adverb", "definition": "in comparison or proportion to something else; to a moderate degree"}],
  "relativity": [{"partOfSpeech": "noun", "definition": "the quality of being judged in comparison to other things; Einstein's theory of space, time, and gravity"}],
  "relaxation": [{"partOfSpeech": "noun", "definition": "the state of being free from tension and anxiety; rest and leisure"}],
  "relentless": [{"partOfSpeech": "adjective", "definition": "unceasingly intense, harsh, or determined; showing no sign of letting up"}],
  "relocating": [{"partOfSpeech": "verb", "definition": "moving to a new place of residence or business; transferring to a different location"}],
  "relocation": [{"partOfSpeech": "noun", "definition": "the act of moving to a different place of residence or business operation"}],
  "reluctance": [{"partOfSpeech": "noun", "definition": "unwillingness or hesitation to do something; lack of enthusiasm for a task"}],
  "remarkable": [{"partOfSpeech": "adjective", "definition": "worthy of attention; striking and extraordinary; notably unusual"}],
  "remarkably": [{"partOfSpeech": "adverb", "definition": "to an extraordinary or surprising degree; in a way that draws attention"}],
  "remembered": [{"partOfSpeech": "verb", "definition": "recalled or brought back to mind from memory; kept in one's thoughts"}],
  "remittance": [{"partOfSpeech": "noun", "definition": "a sum of money sent as payment, especially to another country or distant location"}],
  "remodeling": [{"partOfSpeech": "noun", "definition": "the process of renovating or altering the structure and appearance of a building or room"}],
  "remortgage": [{"partOfSpeech": "verb", "definition": "to take out a different or additional loan secured against a property already mortgaged"}],
  "rendezvous": [{"partOfSpeech": "noun", "definition": "a prearranged meeting at a specific time and place; a popular gathering spot"}],
  "renovation": [{"partOfSpeech": "noun", "definition": "the act of restoring a building or structure to good condition through repair and updating"}],
  "repayments": [{"partOfSpeech": "noun", "definition": "amounts of money paid back over time to settle a debt or loan"}],
  "repeatedly": [{"partOfSpeech": "adverb", "definition": "over and over again; on multiple occasions in succession"}],
  "repentance": [{"partOfSpeech": "noun", "definition": "sincere regret or remorse for wrongdoing; the act of feeling sorry and seeking forgiveness"}],
  "repetition": [{"partOfSpeech": "noun", "definition": "the act of doing or saying something again; recurrence of an action or event"}],
  "repetitive": [{"partOfSpeech": "adjective", "definition": "involving or characterized by the same actions or elements being done over and over"}],
  "replicated": [{"partOfSpeech": "verb", "definition": "copied, reproduced, or duplicated something exactly; repeated an experiment or result"}],
  "reportedly": [{"partOfSpeech": "adverb", "definition": "according to what has been stated or claimed by others, though not confirmed firsthand"}],
  "repository": [{"partOfSpeech": "noun", "definition": "a central location where data, code, or items are stored and managed"}],
  "represents": [{"partOfSpeech": "verb", "definition": "stands for, symbolizes, or acts on behalf of someone or something"}],
  "repression": [{"partOfSpeech": "noun", "definition": "the act of subduing or restraining by force; the suppression of thoughts, feelings, or dissent"}],
  "reproduced": [{"partOfSpeech": "verb", "definition": "created a copy or close imitation of something; generated offspring"}],
  "republican": [{"partOfSpeech": "adjective", "definition": "relating to or supporting a form of government in which power is held by elected representatives"}],
  "repurchase": [{"partOfSpeech": "verb", "definition": "to buy back something that was previously sold or owned"}],
  "reputation": [{"partOfSpeech": "noun", "definition": "the beliefs or opinions generally held about someone or something; overall public standing"}],
  "requesting": [{"partOfSpeech": "verb", "definition": "formally asking for something; making a polite or official demand"}],
  "requisites": [{"partOfSpeech": "noun", "definition": "things that are necessary or essential for a particular purpose or outcome"}],
  "researched": [{"partOfSpeech": "verb", "definition": "investigated systematically to establish facts or gather information on a subject"}],
  "researcher": [{"partOfSpeech": "noun", "definition": "a person who conducts systematic investigation and study to discover new knowledge"}],
  "researches": [{"partOfSpeech": "verb", "definition": "conducts systematic investigation into a subject to discover facts or principles"}],
  "resembling": [{"partOfSpeech": "verb", "definition": "looking or seeming similar to something or someone else; bearing a likeness"}],
  "resentment": [{"partOfSpeech": "noun", "definition": "bitter indignation at having been treated unfairly; lingering anger or displeasure"}],
  "reservoirs": [{"partOfSpeech": "noun", "definition": "large natural or artificial lakes used for storing water; supplies held in reserve"}],
  "residences": [{"partOfSpeech": "noun", "definition": "places where people live; homes, dwellings, or houses"}],
  "resilience": [{"partOfSpeech": "noun", "definition": "the ability to recover quickly from difficulties; toughness and adaptability under stress"}],
  "resistance": [{"partOfSpeech": "noun", "definition": "the refusal to accept or comply with something; opposition or the ability to withstand force"}],
  "resolution": [{"partOfSpeech": "noun", "definition": "a firm decision to do something; the solving of a problem; the detail an image or screen can display"}],
  "respectful": [{"partOfSpeech": "adjective", "definition": "showing politeness, courtesy, and high regard for others"}],
  "respecting": [{"partOfSpeech": "preposition", "definition": "with regard to; concerning a particular matter or subject"}],
  "respective": [{"partOfSpeech": "adjective", "definition": "belonging or relating separately to each of the people or things already mentioned"}],
  "respirator": [{"partOfSpeech": "noun", "definition": "a device worn over the mouth and nose to filter air or assist breathing"}],
  "responders": [{"partOfSpeech": "noun", "definition": "people who react to an event or situation, especially emergency personnel"}],
  "responding": [{"partOfSpeech": "verb", "definition": "replying or reacting to something; answering a question or acting in return"}],
  "responsive": [{"partOfSpeech": "adjective", "definition": "reacting quickly and favorably; adapting readily to different conditions or inputs"}],
  "restaurant": [{"partOfSpeech": "noun", "definition": "a commercial establishment where meals are prepared and served to customers"}],
  "restocking": [{"partOfSpeech": "verb", "definition": "replenishing supplies or inventory that have been depleted or sold"}],
  "restrained": [{"partOfSpeech": "adjective", "definition": "held back or kept under control; characterized by moderation and self-discipline"}],
  "restraints": [{"partOfSpeech": "noun", "definition": "measures or devices that limit, control, or hold back movement or behavior"}],
  "restricted": [{"partOfSpeech": "adjective", "definition": "limited in extent, number, or scope; subject to special rules or access controls"}],
  "resumption": [{"partOfSpeech": "noun", "definition": "the act of beginning again after a pause or interruption"}],
  "rethinking": [{"partOfSpeech": "verb", "definition": "reconsidering or reassessing a plan, idea, or approach with fresh perspective"}],
  "retirement": [{"partOfSpeech": "noun", "definition": "the period of life after leaving one's career or profession; withdrawal from active working life"}],
  "retrospect": [{"partOfSpeech": "noun", "definition": "a look back at events or situations in the past, especially with fresh insight"}],
  "revelation": [{"partOfSpeech": "noun", "definition": "a surprising and previously unknown fact that is made known; a divine disclosure"}],
  "reversible": [{"partOfSpeech": "adjective", "definition": "able to be undone, changed back, or turned to the opposite state"}],
  "revocation": [{"partOfSpeech": "noun", "definition": "the official cancellation or withdrawal of a decree, decision, license, or privilege"}],
  "revolution": [{"partOfSpeech": "noun", "definition": "a forcible overthrow of a government or social order; a dramatic and wide-reaching change"}],
  "rhetorical": [{"partOfSpeech": "adjective", "definition": "relating to the art of effective or persuasive speaking or writing; asked for effect rather than an answer"}],
  "ridiculous": [{"partOfSpeech": "adjective", "definition": "deserving or inviting mockery; absurd and unreasonable to the point of being laughable"}],
  "riverfront": [{"partOfSpeech": "noun", "definition": "the area of land alongside a flowing body of water in an urban setting"}],
  "roadrunner": [{"partOfSpeech": "noun", "definition": "a fast-running ground bird of the cuckoo family found in arid regions of North America"}],
  "robustness": [{"partOfSpeech": "noun", "definition": "the quality of being strong, sturdy, and able to withstand adverse conditions"}],
  "rockabilly": [{"partOfSpeech": "noun", "definition": "an early style of rock and roll music blending elements of country and rhythm and blues"}],
  "rotational": [{"partOfSpeech": "adjective", "definition": "relating to or involving circular movement around a central axis or point"}],
  "roundabout": [{"partOfSpeech": "noun", "definition": "a circular junction where traffic flows in one direction around a central island"}],
  "roundtable": [{"partOfSpeech": "noun", "definition": "a meeting or discussion in which all participants have equal status and share ideas freely"}]
};
const merged = { ...existing, ...newDefs };
const answers = JSON.parse(readFileSync("./data/words-answer.json", "utf-8"));
const covered = answers.filter(w => new Set(Object.keys(merged)).has(w));
console.log(`Coverage: ${covered.length}/${answers.length}`);
writeFileSync("./data/word-definitions.json", JSON.stringify(merged, null, 2) + "\n");
